export const nityaNemavaliIndex = [
  { id: 'section_1', title: '१. निवेदन (सतराव्या आवृत्तीसंबंधी)' },
  { id: 'section_2', title: '२. प्रस्तावना (पहिल्या आवृत्तीची)' },
  { id: 'section_3', title: '३. श्री भाऊसाहेबमहाराजांच्या निर्याणाचा अभंग' },
  { id: 'section_4', title: '४. दैनंदिन कार्यक्रम / सप्ताह' },
  { id: 'section_5', title: '५. काकडआरती व भुपाळ्या' },
  { id: 'section_6', title: '६. सकाळच्या नेमापूर्वी म्हटले जाणारे श्लोक व गजर' },
  { id: 'section_7', title: '७. सकाळचे भजन' },
  { id: 'section_8', title: '८. दुपारचे भजन (मंगळवार व शुक्रवार)' },
  { id: 'section_9', title: '९. दुपारचे भजन (सोम. बुध. गुरु. शनी. रवी.)' },
  {
    id: 'section_10',
    title: '१०. रात्रीचे भजन',
    subsections: [
      { id: 'section_10_sub_1', title: 'विडा' },
      { id: 'section_10_sub_2', title: 'आरत्या' },
      { id: 'section_10_sub_3', title: 'शेजारती' },
      { id: 'section_10_sub_4', title: 'धांवा' },
      { id: 'section_10_sub_5', title: 'करुणाष्टके' },
      { id: 'section_10_sub_6', title: 'पाळणे' },
    ],
  },
  { id: 'section_11', title: '११. भारूडे' },
  { id: 'section_12', title: '१२. पंचसमासी' },
  { id: 'section_13', title: '१३. सहावा समास (श्री अंबुरावमहाराज यांचे चरित्र)' },
  { id: 'section_14', title: '१४. सातवा समास (श्री गुरुदेव रानडे यांचे चरित्र)' },
  { id: 'section_15', title: '१५. पंचपदी' },
  { id: 'section_16', title: '१६. दासबोध दशक ४, समास ३ रा' },
  { id: 'section_17', title: '१७. दासबोध दशक ४, समास ८ वा' },
  { id: 'section_18', title: '१८. मनाचे श्लोक (१ ते १०)' },
  { id: 'section_19', title: '१९. नारायण स्तोत्र' },
  { id: 'section_20', title: '२०. निर्वाणषटकम्' },
  { id: 'section_21', title: '२१. आरती नंतर म्हटले जाणारे श्लोक व पदे' },
];