// constants/nityaNemavaliIndex.ts
export const nityaNemavaliIndex = [
  { id: 'section_1', title: 'निवेदन (सतराव्या आवृत्तीसंबंधी)' },
  { id: 'section_2', title: 'प्रस्तावना (पहिल्या आवृत्तीची)' },
  { id: 'section_3', title: 'श्री भाऊसाहेबमहाराजांच्या निर्याणाचा अभंग' },
  { id: 'section_4', title: 'दैनंदिन कार्यक्रम / सप्ताह' },
  { id: 'section_5', title: 'काकडआरती व भुपाळ्या' },
  { id: 'section_6', title: 'सकाळच्या नेमापूर्वी म्हटले जाणारे श्लोक व गजर' },
  { id: 'section_7', title: 'सकाळचे भजन' },
  { id: 'section_8', title: 'दुपारचे भजन (मंगळवार व शुक्रवार)' },
  { id: 'section_9', title: 'दुपारचे भजन (सोम. बुध. गुरु. शनी. रवी.)' },
  {
    id: 'section_10',
    title: 'रात्रीचे भजन',
    subsections: [
      { id: 'section_10_sub_1', title: 'विडा' },
      { id: 'section_10_sub_2', title: 'आरत्या' },
      { id: 'section_10_sub_3', title: 'शेजारती' },
      { id: 'section_10_sub_4', title: 'धांवा' },
      { id: 'section_10_sub_5', title: 'करुणाष्टके' },
      { id: 'section_10_sub_6', title: 'पाळणे' },
    ],
  },
  { id: 'section_11', title: 'भारूडे' },
  { id: 'section_12', title: 'पंचसमासी' },
  { id: 'section_13', title: 'सहावा समास (श्री अंबुरावमहाराज यांचे चरित्र)' },
  { id: 'section_14', title: 'सातवा समास (श्री गुरुदेव रानडे यांचे चरित्र)' },
  { id: 'section_15', title: 'पंचपदी' },
  { id: 'section_16', title: 'दासबोध दशक ४, समास ३ रा' },
  { id: 'section_17', title: 'दासबोध दशक ४, समास ८ वा' },
  { id: 'section_18', title: 'मनाचे श्लोक (१ ते १०)' },
  { id: 'section_19', title: 'नारायण स्तोत्र' },
  { id: 'section_20', title: 'निर्वाणषटकम्' },
  { id: 'section_21', title: 'आरती नंतर म्हटले जाणारे श्लोक व पदे' },
];