export const parmarthMandirIndex = [
  { id: 'section_1', title: '१. अर्पणपत्रिका' },
  { id: 'section_2', title: '२. द्वितीय आवृत्तीसंबंधी निवेदन' },
  { id: 'section_3', title: '३. निवेदन (प्रथमावृत्ती)' },
  { id: 'section_4', title: '४. प्रस्तावना (प्रथमावृत्ती )' },
  { id: 'section_5', title: '५. संप्रदायाचे चार महापुरुष - छायाचित्रे, संक्षिप्त बोधवचनांसह' },
  { id: 'section_6', title: '६. श्री भाऊसाहेब उमदीकर महाराज यांचे बोधवचनामृत' },
  { id: 'section_7', title: '७. श्री सद्गुरुनाथ निंबर्गी महाराजांची १३ पदे' },
  {
    id: 'section_8',
    title: '८. अनुभव-पदे',
    subsections: [
        { id: 'section_8_a', title: 'अ' },
        { id: 'section_8_aa', title: 'आ' },
        { id: 'section_8_i', title: 'इ' },
        { id: 'section_8_ii', title: 'ई' },
        { id: 'section_8_u', title: 'उ' },
        { id: 'section_8_uu', title: 'ऊ' },
        { id: 'section_8_e', title: 'ए' },
        { id: 'section_8_ai', title: 'ऐ' },
        { id: 'section_8_o', title: 'ओ' },
        { id: 'section_8_au', title: 'औ' },
        { id: 'section_8_am', title: 'अं' },
        { id: 'section_8_aha', title: 'अः' },
        { id: 'section_8_ru', title: 'ऋ' },
        { id: 'section_8_ka', title: 'क' },
        { id: 'section_8_kha', title: 'ख' },
        { id: 'section_8_ga', title: 'ग' },
        { id: 'section_8_gha', title: 'घ' },
        { id: 'section_8_na', title: 'ङ' },
        { id: 'section_8_cha', title: 'च' },
        { id: 'section_8_chha', title: 'छ' },
        { id: 'section_8_ja', title: 'ज' },
        { id: 'section_8_jha', title: 'झ' },
        { id: 'section_8_nya', title: 'ञ' },
        { id: 'section_8_ta', title: 'ट' },
        { id: 'section_8_tha', title: 'ठ' },
        { id: 'section_8_da', title: 'ड' },
        { id: 'section_8_dha', title: 'ढ' },
        { id: 'section_8_nna', title: 'ण' },
        { id: 'section_8_tta', title: 'त' },
        { id: 'section_8_ttha', title: 'थ' },
        { id: 'section_8_dda', title: 'द' },
        { id: 'section_8_ddha', title: 'ध' },
        { id: 'section_8_n', title: 'न' },
        { id: 'section_8_pa', title: 'प' },
        { id: 'section_8_pha', title: 'फ' },
        { id: 'section_8_ba', title: 'ब' },
        { id: 'section_8_bha', title: 'भ' },
        { id: 'section_8_ma', title: 'म' },
        { id: 'section_8_ya', title: 'य' },
        { id: 'section_8_ra', title: 'र' },
        { id: 'section_8_la', title: 'ल' },
        { id: 'section_8_va', title: 'व' },
        { id: 'section_8_sha', title: 'श' },
        { id: 'section_8_ssha', title: 'ष' },
        { id: 'section_8_sa', title: 'स' },
        { id: 'section_8_ha', title: 'ह' },
        { id: 'section_8_lla', title: 'ळ' },
        { id: 'section_8_ksha', title: 'क्ष' },
        { id: 'section_8_dnya', title: 'ज्ञ' },
        { id: 'section_8_shra', title: 'श्र' },
    ],
  },
  { id: 'section_9', title: '९. भुपाळ्या' },
  { id: 'section_10', title: '१०. आरत्या' },
  { id: 'section_11', title: '११. प्रार्थना' },
  { id: 'section_12', title: '१२. स्तवने' },
  { id: 'section_13', title: '१३. भारुडे' },
];