export const parmarthMandirIndex = [
  { id: 'section_1', title: '१. अर्पणपत्रिका' },
  { id: 'section_2', title: '२. द्वितीय आवृत्तीसंबंधी निवेदन' },
  { id: 'section_3', title: '३. निवेदन (प्रथमावृत्ती)' },
  { id: 'section_4', title: '४. प्रस्तावना (प्रथमावृत्ती )' },
  { id: 'section_5', title: '५. संप्रदायाचे चार महापुरुष - छायाचित्रे, संक्षिप्त बोधवचनांसह' },
  { id: 'section_6', title: '६. श्री भाऊसाहेब उमदीकर महाराज यांचे बोधवचनामृत' },
  {
    id: 'section_7',
    title: '७. श्री सद्गुरुनाथ निंबरगी महाराजांची १३ पदे',
    subsections: [
        { id: 'section_7_sub_1', title: '१. गुरुचरणकमलदल्लि', author: '' },
        { id: 'section_7_sub_2', title: '२. ॐ नाम कायुवदु', author: '' },
        { id: 'section_7_sub_3', title: '३. नोयिसि नुडिदन्याके', author: '' },
        { id: 'section_7_sub_4', title: '४. केळु चातुरा हक्की (कलगी-तुरा)', author: '' },
        { id: 'section_7_sub_5', title: '५. केळु शाहिरा हिडियो खून ई (कलगी-तुरा)', author: '' },
        { id: 'section_7_sub_6', title: '६. ईसु दिन ई नाल्कु वेद', author: '' },
        { id: 'section_7_sub_7', title: '७. मनसिन मुरगिय तिहिसो देवा', author: '' },
        { id: 'section_7_sub_8', title: '८. एनु माडिदि केळेन्न, देवा', author: '' },
        { id: 'section_7_sub_9', title: '९. चिंत्याक माडती शिवने इद्दानेछु प्राणी', author: '' },
        { id: 'section_7_sub_10', title: '१०. कल्लु मेत्तगे माडिकोळ्ळण्णा', author: '' },
        { id: 'section_7_sub_11', title: '११. ना ह्यांग बडव । ना ह्यांग परदेशि', author: '' },
        { id: 'section_7_sub_12', title: '१२. नेल्लु कुटुणु बारम्मा', author: '' },
        { id: 'section_7_sub_13', title: '१३. अंदिल्ल स्वामि इंदिल्ल', author: '' },
    ]
  },
  {
    id: 'section_8',
    title: '८. अनुभव-पदे',
    subsections: [
      {
        id: 'section_8_a',
        title: 'अ',
        subsections: [
            { id: 'section_8_a_1', title: '१. अ एंब वर्ण', author: 'हरिहर' },
            { id: 'section_8_a_2', title: '२. अक्कतंगेरु नावु', author: 'रामेश्वर' },
            { id: 'section_8_a_3', title: '३. अगडबंबं बंबं बाजे डमरू', author: 'अज्ञात' },
            { id: 'section_8_a_4', title: '४. अगर है शौक मिलने का', author: 'मन्सूर' },
            { id: 'section_8_a_5', title: '५. अजर अमर इक नाम है', author: 'कबीर' },
            { id: 'section_8_a_6', title: '६. अनुगालवु चिंतेयु मनुजरिगे', author: 'पुरंदरदास' },
            { id: 'section_8_a_7', title: '७. अनंत युगाचा देव्हारा', author: 'तुकाराम' },
            { id: 'section_8_a_8', title: '८. अपने घट दियना बारु रे', author: 'कबीर' },
            { id: 'section_8_a_9', title: '९. अब की राखि लेहु भगवान', author: 'सूरदास' },
            { id: 'section_8_a_10', title: '१०. अब कैसे छूटे नाम रट लागी', author: 'रैदास' },
            { id: 'section_8_a_11', title: '११. अब तुम कब सुमिरोगे राम', author: 'कबीर' },
            { id: 'section_8_a_12', title: '१२. अब तो प्रगट भई जग जानी', author: 'सूरदास' },
            { id: 'section_8_a_13', title: '१३. अब मैं नाच्यों बहुत गुपाल', author: 'सूरदास' },
            { id: 'section_8_a_14', title: '१४. अब रहीम मुश्किल पडी', author: 'रहीम' },
            { id: 'section_8_a_15', title: '१५. अमोलिक रत्न जोडले रे तुज', author: 'ज्ञानदेव' },
            { id: 'section_8_a_16', title: '१६. अय्या, पाताळवित्तित्त (वचन)', author: 'अक्कमहादेवी' },
            { id: 'section_8_a_17', title: '१७. अरविनिंद स्तोत्र माडुवे', author: 'रामभाऊ यरगट्टीकर' },
            { id: 'section_8_a_18', title: '१८. अरितु गुरुविन पाद हुडुकि होंदु', author: 'चिदानंद' },
            { id: 'section_8_a_19', title: '१९. अरे नर आँख पर तेरे', author: 'कृष्णानंद' },
            { id: 'section_8_a_20', title: '२०. अरे मन राम नाम कह तोता', author: 'अज्ञात' },
            { id: 'section_8_a_21', title: '२१. अरे मन होशियार हो जा', author: 'ब्रजनाथ व्यास' },
            { id: 'section_8_a_22', title: '२२. अर्थियागि बन्नि अरितु नोड्डुव', author: 'महिपति' },
            { id: 'section_8_a_23', title: '२३. अलख निरंजन दत्त गुरु श्री', author: 'गोळे (मिरज)' },
            { id: 'section_8_a_24', title: '२४. अल्ला के वास्ते होगया', author: 'रामभाऊ यरगट्टीकर' },
            { id: 'section_8_a_25', title: '२५. अवधूत सो जोगी', author: 'कबीर' },
            { id: 'section_8_a_26', title: '२६. अविचल मंत्र अमर मंत्र अखै मंत्र', author: 'अज्ञात' },
            { id: 'section_8_a_27', title: '२७. अहुदहुदनाथबंधु', author: 'कृष्णराव काखंडकी' },
            { id: 'section_8_a_28', title: '२८. अळतद कूसु अळतद', author: 'चिदानंद' },
            { id: 'section_8_a_29', title: '२९. अळुतिद्या कंदा अळुतिद्या', author: 'कूडलूरेश' },
        ]
      },
      {
        id: 'section_8_aa',
        title: 'आ',
        subsections: [
            { id: 'section_8_aa_1', title: '३०. आज दिवस जाऊँ बलिहारे', author: 'रैदास' },
            { id: 'section_8_aa_2', title: '३१. आणीक दुसरे मज नाही आतां', author: 'तुकाराम' },
            { id: 'section_8_aa_3', title: '३२. आतां कशिरे विझवू', author: 'कल्याण' },
            { id: 'section_8_aa_4', title: '३३. आतां तरी जाय जाय जाय', author: 'रामदास' },
            { id: 'section_8_aa_5', title: '३४. आनंदवाद चिद्धन वस्तु', author: 'नागलिंग' },
            { id: 'section_8_aa_6', title: '३५. आम्हांसी काय बा उणें रे बापांनो', author: 'महिपती (ग्वाल्हेर)' },
            { id: 'section_8_aa_7', title: '३६. आर गोडविन्नेनु मगळे', author: 'शरीफ साहेब (शिशुनाळधीश)' },
            { id: 'section_8_aa_8', title: '३७. आरिगे काणदी मुत्तु', author: 'रेवणसिद्ध' },
            { id: 'section_8_aa_9', title: '३८. आरु अक्षर भेद हरि केळलु बंद', author: 'षडक्षरमुनि' },
            { id: 'section_8_aa_10', title: '३९. आरु ओलिदरेनु नमगिन्नारु', author: 'पुरंदरदास' },
            { id: 'section_8_aa_11', title: '४०. आरेनु माड्डुवरो माडिद', author: 'भगवंतप्प' },
            { id: 'section_8_aa_12', title: '४१. आला हो आला आला', author: 'महिपति (ग्वाल्हेर)' },
            { id: 'section_8_aa_13', title: '४२. आवकुलवादरेनु', author: 'ज्ञानबोध' },
            { id: 'section_8_aa_14', title: '४३. आव रोगवु एनगे देव धन्वंत्रि', author: 'गोपालदास' },
            { id: 'section_8_aa_15', title: '४४. आवाग शिवमंत्र नेनवागि', author: 'बेरटूरपति' },
        ]
      },
      {
        id: 'section_8_i',
        title: 'इ',
        subsections: [
            { id: 'section_8_i_1', title: '४५. इको नम्म स्वामि', author: 'महिपति' },
            { id: 'section_8_i_2', title: '४६. इतनी कृपा हो स्वामी', author: 'बहिरो' },
            { id: 'section_8_i_3', title: '४७. इदरोळारय्या  नीनु', author: 'महिपति' },
            { id: 'section_8_i_4', title: '४८. इदीग भकुतियु', author: 'पुरंदरदास' },
            { id: 'section_8_i_5', title: '४९. इदु एननुभावमंटपवो', author: 'शिवलिंगव्वा' },
            { id: 'section_8_i_6', title: '५०. इदु भाग्यविदु भाग्यविदु', author: 'पुरंदरदास' },
            { id: 'section_8_i_7', title: '५१. इदे अनुभवमंटपवु', author: 'बेरटूरपति' },
            { id: 'section_8_i_8', title: '५२. इदे बम्हज्ञान नोडिको', author: 'शरीफ साहेब' },
            { id: 'section_8_i_9', title: '५३. इदे समय हरिये', author: 'विजयदास' },
            { id: 'section_8_i_10', title: '५४. इद्दरिरली देह', author: 'गिरिमल्लेश' },
            { id: 'section_8_i_11', title: '५५. इंथदेल्लिदे ता नोडी', author: 'महिपति' },
            { id: 'section_8_i_12', title: '५६. इंदु एनगे गोविंद !', author: 'राघवेंद्रस्वामी' },
            { id: 'section_8_i_13', title: '५७. इद कोळ्ळि भवरोगकौषधवनु', author: 'पुरंदरदास' },
            { id: 'section_8_i_14', title: '५८. इन्नू दये बारदे दासन मेले', author: 'पुरंदरदास' },
            { id: 'section_8_i_15', title: '५९. इन्नेनिन्नेनु एनगिन्नु इन्नेनिन्नेनु', author: 'महिपति' },
            { id: 'section_8_i_16', title: '६०. इवन्यारु नोडु बारम्मा', author: 'गुरु शंकरार्य' },
            { id: 'section_8_i_17', title: '६१. इष्टु दिन ई वैकुंठ', author: 'कनकदास' },
            { id: 'section_8_i_18', title: '६२. इष्टे पापवनु माडिद्ध साको', author: 'पुरंदरदास' },
            { id: 'section_8_i_19', title: '६३. इस तन धन की कौन बड़ाई', author: 'कबीर' },
        ]
      },
      {
        id: 'section_8_u',
        title: 'उ',
        subsections: [
            { id: 'section_8_u_1', title: '६४. उत्तमोत्तम देव नित्य नीनिरलिक्के', author: 'महिपति' },
            { id: 'section_8_u_2', title: '६५. उद्धव कर्मगती है न्यारी', author: 'मीराबाई' },
        ]
      },
       {
        id: 'section_8_uu',
        title: 'ऊ',
        subsections: [
            { id: 'section_8_uu_1', title: '६६. ऊधो, धनि तुम्हरो बेवहार', author: 'सूरदास' },
        ]
      },
      {
        id: 'section_8_ri',
        title: 'ऋ',
        subsections: [
            { id: 'section_8_ri_1', title: '६७. ऋतु बसन्त याचक भयो', author: '' },
        ]
      },
      {
        id: 'section_8_e',
        title: 'ए',
        subsections: [
            { id: 'section_8_e_1', title: '६८. एंथ रत्नव कंडेनेन्नय', author: 'अज्ञात' },
            { id: 'section_8_e_2', title: '६९. एंथा हुच्चु हिडिदितिवग', author: 'कूडलरेश' },
            { id: 'section_8_e_3', title: '७०. एंथा गारुडिगा । सद्‌गुरु', author: 'चिदानंद' },
            { id: 'section_8_e_4', title: '७१. एंदु मैय मरेसी इदरंते', author: 'नंद्याळसंग' },
            { id: 'section_8_e_5', title: '७२. एन्न कायव दंडिगेय (वचन)', author: 'बसवेश्वर' },
            { id: 'section_8_e_6', title: '७३. एन्न बिन्त्रप केळो', author: 'गोपालदास' },
            { id: 'section_8_e_7', title: '७४. एन्नल्लि निन्न मेलण', author: 'बसवेश्वर' },
            { id: 'section_8_e_8', title: '७५. एमगे सरि इत्तंडदल्लिय', author: 'कुमार व्यास' },
            { id: 'section_8_e_9', title: '७६ एलऱ्यो एलऱ्यो केडबेडिरो ', author: 'कूडलूरेश' },
            { id: 'section_8_e_10', title: '७७. एलो दारिकारने मलगिकोंबरे', author: 'पुरंदरदास' },
            { id: 'section_8_e_11', title: '७८. एल्लिद्यो हरि हेळय्य', author: 'महिपति' },
            { id: 'section_8_e_12', title: '७९. एक प्रेम पुजारी आया है', author: 'परमात्म प्रकाश' },
            { id: 'section_8_e_13', title: '८०. एकांतीचे सुख देई मज देवा', author: 'तुकाराम' },
            { id: 'section_8_e_14', title: '८१. एतस्मात्किमिवेन्द्रजालमपरं', author: '' },
            { id: 'section_8_e_15', title: '८२. एन भरा नट्टीतप्पा एनगे मुळ्ळा', author: 'नंद्याळसंग' },
            { id: 'section_8_e_16', title: '८३. एन सवि एन सवि हरिनाम', author: 'भीमदास' },
            { id: 'section_8_e_17', title: '८४. एनिदेनिदु हरिय खेळिदु', author: 'गंगाबाई (तिकोटी)' },
            { id: 'section_8_e_18', title: '८५. एनु अन्याय तिळियदु', author: 'रामराव होर्ती' },
            { id: 'section_8_e_19', title: '८६. एनु हेळलम्मा श्रीगुरुदय', author: 'निजगुणशिवयोगी' },
            { id: 'section_8_e_20', title: '८७. एनु हेळलि एन्न अज्ञानवशदिंद', author: 'कूडलूरेश' },
            { id: 'section_8_e_21', title: '८८. एरबारद भारिय गुड्डु', author: 'मडिवाळयोगी' },

        ]
      },
      {
        id: 'section_8_ai',
        title: 'ऐ',
        subsections: [
            { id: 'section_8_ai_1', title: '८९. ऐसा देस दिवाना रे लोगो', author: 'चरनदास' },
            { id: 'section_8_ai_2', title: '९०. ऐसा सन्त सिपाही साधो', author: 'पलटू' },
            { id: 'section_8_ai_3', title: '९१. ऐसी नगरिया में किहि बिध रहना', author: 'कबीर' },
            { id: 'section_8_ai_4', title: '९२. ऐसो को उदार जग माही', author: 'तुलसीदास' },
            { id: 'section_8_ai_5', title: '९३. ऐसो है रे हरि-रस', author: 'कबीर' },
        ]
      },
      {
        id: 'section_8_o',
        title: 'ओ',
        subsections: [
            { id: 'section_8_o_1', title: '९४. ओ एन्नबारदे हरिये', author: 'कृष्णराय (काखंडकि)' },
            { id: 'section_8_o_2', title: '९५. ओदु बेड निनगे शास्त्र बेड', author: 'चिदानंद' },
        ]
      },
      {
        id: 'section_8_om',
        title: 'ॐ',
        subsections: [
            { id: 'section_8_om_1', title: '९६. ॐ नमो शिवा एनु', author: 'काडसिद्ध' },
            { id: 'section_8_om_2', title: '९७. ॐ नमः शिवायेन्निरो', author: 'पंचाक्षरी (नीरलकेरी)' },
        ]
      },
      {
        id: 'section_8_au',
        title: 'औ',
        subsections: [
            { id: 'section_8_au_1', title: '९८. औदुंबरवासि प्रभो', author: 'अज्ञात' },
            { id: 'section_8_au_2', title: '९९. और देवल जहँ धुन्धली पूजा', author: 'चरनदास' },

        ]
      },
      
      {
        id: 'section_8_an',
        title: 'अं',
        subsections: [
            { id: 'section_8_an_1', title: '१००. अंजिकिन्यातकय्य', author: 'पुरंदरदास' },
            { id: 'section_8_an_2', title: '१०१. अंतरंगद कदवु तेरेयितिंदु', author: 'विजयदास' },
            { id: 'section_8_an_3', title: '१०२. अंदवाद श्रीगंधद गिडदोळु', author: 'बंदेनवाज' },
        ]
      },



      
      {
        id: 'section_8_ka',
        title: 'क',
        subsections: [

            { id: "section_8_ka_1", title: "१०३. कडकोळ्ळद ना गुलामा", author: "कृष्णप्पा खैनूर" },
            { id: "section_8_ka_2", title: "१०४. कण्ण मुचिदरु काणबरुतिदे", author: "भीमाशंकर" },
            { id: "section_8_ka_3", title: "१०५. कण्णारे कंडेवु चिन्मयद रूप", author: "महिपति" },
            { id: "section_8_ka_4", title: "१०६. कण्णिनोळगे नोडि कैवल्यव", author: "पुरंदरदास" },
            { id: "section_8_ka_5", title: "१०७. कण्णिनोळगे नोडो हरिय", author: "पुरंदरदास" },
            { id: "section_8_ka_6", title: "१०८. कण्णिनोळु कण्णु कंडे", author: "चिदानंद" },
            { id: "section_8_ka_7", title: "१०९. कण्णिलि केळुव कांबुव", author: "पुरंदरदास" },
            { id: "section_8_ka_8", title: "११०. कत जाइए रे, घर लाग्यो रंगु", author: "रामानंद" },
            { id: "section_8_ka_9", title: "१११. कबिराचे विणतो शेले", author: "ग. दि. माडगूळकर" },
            { id: "section_8_ka_10", title: "११२. कम से कम ढाइ घंटोंतक", author: "सावनसिंग (बियास)" },
            { id: "section_8_ka_11", title: "११३. करनी बिन कथनी इसी", author: "चरनदास" },
            { id: "section_8_ka_12", title: "११४. करम गति टारै नाहि टरी", author: "कबीर" },
            { id: "section_8_ka_13", title: "११५. करी घेता न ये", author: "रामदास" },
            { id: "section_8_ka_14", title: "११६. करुणिसो गुरु एनगे", author: "महिपति" },
            { id: "section_8_ka_15", title: "११७. कलियुगीं संत झाले ते बहुत", author: "तुकाराम" },
            { id: "section_8_ka_16", title: "११८. कल्लुसक्करे कोळ्ळिरो", author: "पुरंदरदास" },
            { id: "section_8_ka_17", title: "११९. कशी मोहिनी घातली गुरुनै", author: "महीपति (ग्वाल्हेर)" },
            { id: "section_8_ka_18", title: "१२०. कहूँ रे जो कहिबे की होइ", author: "कबीर" },
            { id: "section_8_ka_19", title: "१२१. काणबारदंथा वस्तु", author: "कूडलूरेश" },
            { id: "section_8_ka_20", title: "१२२. काणरल्ल शिवन काणरल्ल", author: "सर्पभूषण (गुरुसिद्ध)" },
            { id: "section_8_ka_21", title: "१२३. काणुतिदे परबिंदु", author: "सर्पभूषण (गुरुसिद्ध)" },
            { id: "section_8_ka_22", title: "१२४. कापसाचे गोळे फिरती पोकळी", author: "ज्ञानदेव (ज्ञानेश्वर)" },
            { id: "section_8_ka_23", title: "१२५. कामामध्यें काम रे", author: "अज्ञात" },
            { id: "section_8_ka_24", title: "१२६. कायकांतारव होक्कु", author: "सर्पभूषण (गुरुसिद्ध)" },
            { id: "section_8_ka_25", title: "१२७. कायलारेनु कृष्ण", author: "पुरंदरदास" },
            { id: "section_8_ka_26", title: "१२८. कायो गुरुराया । करुणिसि", author: "विठ्ठलाचार्य" },
            { id: "section_8_ka_27", title: "१२९. काल करो सो आज कर", author: "" },
            { id: "section_8_ka_28", title: "१३०. कालकर्मव कालिले ओदिदव", author: "भवतारक" },
            { id: "section_8_ka_29", title: "१३१. काहे न रसना रामहिं गावहि", author: "तुलसीदास" },
            { id: "section_8_ka_30", title: "१३२. काहे रे बन खोजन जाई", author: "नानक" },
            { id: "section_8_ka_31", title: "१३३. किमि सहि जात", author: "तुलसीदास" },
            { id: "section_8_ka_32", title: "१३४. कीजै प्रभु अपने बिरद की लाज", author: "सूरदास" },
            { id: "section_8_ka_33", title: "१३५. कुरुबरो नावु कुरुबरो", author: "कूडप्रेश" },
            { id: "section_8_ka_34", title: "१३६. कुल कुल कुलवेन्नुतिहरु", author: "कनकदास" },
            { id: "section_8_ka_35", title: "१३७. कूसनु कंडीरा ज्ञानिगळेल्ल", author: "पुरंदरदास" },
            { id: "section_8_ka_36", title: "१३८. कृष्णमूर्ति कण्ण मुंदे निंतिरुत्तदे", author: "पुरंदरदास" },
            { id: "section_8_ka_37", title: "१३९. केंडक्के गोरलि हत्तुवदुंटे", author: "पुरंदरदास" },
            { id: "section_8_ka_38", title: "१४०. केशव कहि न जाय", author: "तुलसीदास" },
            { id: "section_8_ka_39", title: "१४१. केहि समुझावौं", author: "कबीर" },
            { id: "section_8_ka_40", title: "१४२. केळनो हरि ताळनो", author: "पुरंदरदास" },
            { id: "section_8_ka_41", title: "१४३. केळिदागले हेळबारदु", author: "अज्ञात" },
            { id: "section_8_ka_42", title: "१४४. कैसे बोटानें दाखवू तुला", author: "ज्ञानेश्वर" },
            { id: "section_8_ka_43", title: "१४५. कोई सुनता है गुरु ज्ञानी", author: "कबीर" },
            { id: "section_8_ka_44", title: "१४६. कोई स्याम मनोहर ल्योरी", author: "मीराबाई" },
            { id: "section_8_ka_45", title: "१४७. कोरी साल न छाँडै रे", author: "दादू" },
            { id: "section_8_ka_46", title: "१४८. कोलु कोलु अन्निरो", author: "अज्ञात" },
            { id: "section_8_ka_47", title: "१४९. कंडिरेनो महाकारण ब्रह्मन", author: "काडसिद्ध" },
            { id: "section_8_ka_48", title: "१५०. क्या तन माँजता रे", author: "प्रभूदास" },
            { id: "section_8_ka_49", title: "१५१. क्या बे किसी से काम", author: "महिपती (ग्वाल्हेर)" },
           
        ]
      },
      {
        id: 'section_8_kha',
        title: 'ख',
        subsections: [
            { id: 'section_8_kha_1', title: '१५२. खूण जरी तुम्हा', author: 'रामभाऊ यरगट्टीकर' },
        ]
      },
      {
        id: 'section_8_ga',
        title: 'ग',
        subsections: [
            { id: "section_8_ga_1", title: "१५३. गया और काशीमें", author: "अज्ञात" },
            { id: "section_8_ga_2", title: "१५४. गाफिल तू सोच मन में", author: "ब्रह्मानंद" },
            { id: "section_8_ga_3", title: "१५५. गुरिया ओगेदेनो", author: "नरसिंह" },
            { id: "section_8_ga_4", title: "१५६. गुरुकृपाञ्जन पायो मेरे भाई", author: "एकनाथ" },
            { id: "section_8_ga_5", title: "१५७. गुरुता तोरिद गुरुविन मरेतु", author: "गुरुलिंगजंगम" },
            { id: "section_8_ga_6", title: "१५८. गुरुदेव नानु", author: "रुद्र" },
            { id: "section_8_ga_7", title: "१५९. गुरुदेव नी माडिदु", author: "सर्पभूषण (गुरुसिद्ध)" },
            { id: "section_8_ga_8", title: "१६०. गुरुंनीं धरिलें करी", author: "महिपति (ग्वाल्हेर)" },
            { id: "section_8_ga_9", title: "१६१. गुरु ने मोहि दीन्ही", author: "कबीर" },
            { id: "section_8_ga_10", title: "१६२. गुरु बिन कौन बतावै बाट", author: "कबीर" },
            { id: "section_8_ga_11", title: "१६३. गुरुरायनंथ करुणाळू", author: "महिपति" },
            { id: "section_8_ga_12", title: "१६४. गुरुविन मरेतेल्लो खोडी", author: "उमदीकर शिष्य" },
            { id: "section_8_ga_13", title: "१६५. गुरुविन मरेतेल्लो । मनुज नी", author: "पुरंदरदास" },
            { id: "section_8_ga_14", title: "१६६. गुरुविन ह्यांग मरेयले", author: "निरुपाधिसिद्ध" },
            { id: "section_8_ga_15", title: "१६७. गुरुवे इरलारे निन्ननु", author: "लिंगप्पा सावळगी" },
            { id: "section_8_ga_16", title: "१६८. गुरुवे निम्म स्मरणेय", author: "बसव दोइडपेटी" },
            { id: "section_8_ga_17", title: "१६९. गुरुवे निम्माज्ञेयनु", author: "कूडलूरेश" },
            { id: "section_8_ga_18", title: "१७०. गोल्लरो नावु गोल्लरो", author: "बलभीम" },
            { id: "section_8_ga_19", title: "१७१. गोपालदासराय", author: "जगन्नाथदास" },
            { id: "section_8_ga_20", title: "१७२. गोपी सुनहु हरि-सन्देस", author: "सूरदास" },
        ]
      },
      {
        id: 'section_8_gha',
        title: 'घ',
        subsections: [
            { id: 'section_8_gha_1', title: '१७३. घर तजौं, बन तजौं', author: 'अज्ञात' },
            { id: 'section_8_gha_2', title: '१७४. घूँघट का पट खोल', author: 'कबीर' },
        ]
      },
      {
        id: 'section_8_ch',
        title: 'च',
        subsections: [
            { id: "section_8_ch_1", title: "१७५. चरका क्या काते दिल जान", author: "अज्ञात" },
            { id: "section_8_ch_2", title: "१७६. चिच्छक्तिर्ब्रह्मणो राम", author: "(योगवाशिष्ठ)" },
            { id: "section_8_ch_3", title: "१७७. चिंचेच्या पानावर देऊळ रचिले", author: "एकनाथ" },
            { id: "section_8_ch_4", title: "१७८. चिंतेयातको", author: "पुरंदरदास" },
            { id: "section_8_ch_5", title: "१७९. चिंत्याक माडती", author: "पुरंदरदास" },
            { id: "section_8_ch_6", title: "१८०. चिरजीवियागिरेलो", author: "विजयदास" },
            { id: "section_8_ch_7", title: "१८१. चुवत अमीरस", author: "कबीर" },
            { id: "section_8_ch_8", title: "१८२. चेतना है तो चेतले", author: "नानक" },
            { id: "section_8_ch_9", title: "१८३. चेतश्चञ्चलताम्", author: "" },
        ]
      },
      {
        id: 'section_8_cha',
        title: 'छ',
        subsections: [
            { id: 'section_8_cha_1', title: '१८४.  छाँड़ि मन ', author: 'सूरदास' },
        ]
      },
      {
        id: 'section_8_ja',
        title: 'ज',
        subsections: [
            { id: "section_8_ja_1", title: "१८५. जगव सुत्तिप्पुटु (वचन)", author: "बसवेश्वर" },
            { id: "section_8_ja_2", title: "१८६. जन्तूनां नरजन्म", author: "" },
            { id: "section_8_ja_3", title: "१८७. जन्मा आली वाया गेली", author: "तुकाराम" },
            { id: "section_8_ja_4", title: "१८८. जब तें अनहत", author: "चरनदास" },
            { id: "section_8_ja_5", title: "१८९. जब से देखी ख्वाबमें", author: "सूरदास" },
            { id: "section_8_ja_6", title: "१९०. जय पांडुरंगा", author: "पुरंदरदास" },
            { id: "section_8_ja_7", title: "१९१. जाके प्रिय न राम वैदेही", author: "तुलसीदास" },
            { id: "section_8_ja_8", title: "१९२. जाग्रदल्लि जागरनागि", author: "उमदीकर शिष्य" },
            { id: "section_8_ja_9", title: "१९३. जा दिन मन-पंछी", author: "सूरदास" },
            { id: "section_8_ja_10", title: "१९४. जिन्हके रही भावना जैसी", author: "तुलसीदास" },
            { id: "section_8_ja_11", title: "१९५. जेहि जय होइ", author: "तुलसीदास" },
            { id: "section_8_ja_12", title: "१९६. जोगी मत जा", author: "मीराबाई" },
            { id: "section_8_ja_13", title: "१९७. जो पीर मेरा", author: "मौला" },
        ]
      },
      {
        id: 'section_8_jha',
        title: 'झ',
        subsections: [
            { id: 'section_8_jha_1', title: '१९८. झरि लागै महलिया', author: 'धरमदास' },
            { id: 'section_8_jha_2', title: '१९९. झिलमिल झिलमिल', author: 'यारी' },
            { id: 'section_8_jha_3', title: '२००. झीनी झीनी बीनी चदरिया', author: 'कबीर' },
        ]
      },
      {
        id: 'section_8_ta',
        title: 'त',
        subsections: [
          { id: "section_8_ta_1", title: "२०१. तत्त हिंडोलवा", author: "गुलाल" },
          { id: "section_8_ta_2", title: "२०२. तनु निन्नदु जीवन", author: "कनकदास" },
          { id: "section_8_ta_3", title: "२०३. तनुर्वेब गरडियोळ", author: "सर्पभूषण (गुरुसिद्ध)" },
          { id: "section_8_ta_4", title: "२०४. तन्न ता तिळिद मेले", author: "महंत" },
          { id: "section_8_ta_5", title: "२०५. तरीच जन्मा यावें गे", author: "अज्ञात" },
          { id: "section_8_ta_6", title: "२०६. तल्लणव गोळ्ळदिरु एले मानवा", author: "कनकदास" },
          { id: "section_8_ta_7", title: "२०७. ता ब्यारे आगबेकण्णा", author: "तुरळि संगम" },
          { id: "section_8_ta_8", title: "२०८. तिळियबेकु निज", author: "निरुपाधि" },
          { id: "section_8_ta_9", title: "२०९. तिळियुवदे शिवशरणर महिमे", author: "शिवयोगि (अथणी)" },
          { id: "section_8_ta_10", title: "२१०. तिळिसुव मातल्ल", author: "भवतारक" },
          { id: "section_8_ta_11", title: "२११. तीर्थवनु पिडिदवरु", author: "कनकदास" },
          { id: "section_8_ta_12", title: "२१२. तुझिये निढळीं कोटि चंद्र प्रकाशे", author: "ज्ञानेश्वर" },
          { id: "section_8_ta_13", title: "२१३. तुम पलक उधारो दीनानाथ", author: "मीराबाई" },
          { id: "section_8_ta_14", title: "२१४. तेरेद बागिल सुंकविल्लद", author: "शंकरानंद (महालिंगरंग)" },
          { id: "section_8_ta_15", title: "२१५. तो भी कच्चा बे कच्चा", author: "मच्छिंद्रनाथ" },
          { id: "section_8_ta_16", title: "२१६. तो मज आठवतो", author: "केशव" },
          { id: "section_8_ta_17", title: "२१७. तोंवरी तोंवरी", author: "रामदास" },
          { id: "section_8_ta_18", title: "२१८. तौक पहिरावौ", author: "नन्दलाल" },
          { id: "section_8_ta_19", title: "२१९. तौ निबहै जन सेवक तेरा", author: "दादू" },
        ]
      },
      {
        id: 'section_8_tra',
        title: 'त्र',
        subsections: [
             { id: 'section_8_tra_1', title: '२२०. त्रिविध तापांसि', author: 'रामदास' },
        ]
      },
      {
        id: 'section_8_da',
        title: 'द',
        subsections: [
            { id: "section_8_da_1", title: "२२१. दणियदे मलगिदेनो", author: "चिदानंद" },
            { id: "section_8_da_2", title: "२२२. दरस दिवाना बावला", author: "कबीर" },
            { id: "section_8_da_3", title: "२२३. दशविध नौबत्तागुतदण्णा", author: "चिदानंद" },
            { id: "section_8_da_4", title: "२२४. दासनेंदरे पुरंदरदासनय्य", author: "व्यासराय" },
            { id: "section_8_da_5", title: "२२५. दासरिगुंटे भय शोक", author: "जगन्नाथदास" },
            { id: "section_8_da_6", title: "२२६. दिखाया सरीखा नहीं", author: "सिद्धलिंग" },
            { id: "section_8_da_7", title: "२२७. दिवाने मन", author: "कबीर" },
            { id: "section_8_da_8", title: "२२८. दीनन दुखहरन", author: "सूरदास" },
            { id: "section_8_da_9", title: "२२९. दुड्डीवरी दुड्डी", author: "एकनाथ" },
            { id: "section_8_da_10", title: "२३०. दृष्टियोळगे दृष्टि निंतितु", author: "भवतारक" },
            { id: "section_8_da_11", title: "२३१. देखिला गे माये", author: "तुकाराम" },
            { id: "section_8_da_12", title: "२३२. देखोनि त्याच्या", author: "एकनाथ" },
            { id: "section_8_da_13", title: "२३३. देवगंगेयोकुळ्ळवगे दुरि", author: "जगन्नाथदास" },
            { id: "section_8_da_14", title: "२३४. देव जवळीं अंतरी", author: "रामदास" },
            { id: "section_8_da_15", title: "२३५. देवनल्लवेनु", author: "भवतारक" },
            { id: "section_8_da_16", title: "२३६. देहु कलाली एक पियाला", author: "रैदास" },
        ]
      },
      {
        id: 'section_8_dha',
        title: 'ध',
        subsections: [
            { id: "section_8_dha_1", title: "२३७. धनव गळिसबेकेंथादु", author: "भवतारक" },
            { id: "section_8_dha_2", title: "२३८. धन्य कृतकृत्य जालो", author: "रामदास" },
            { id: "section_8_dha_3", title: "२३९. धन्य सुदिन आजि आम्ही", author: "पार्वती-रुक्मिणी" },
            { id: "section_8_dha_4", title: "२४०. धरिला पंढरीचा चोर", author: "जनाबार्ह" },
            { id: "section_8_dha_5", title: "२४१. धांव गंगे बा तू तुळशी", author: "गोदावरी" },
            { id: "section_8_dha_6", title: "२४२. धांव घाली विठू आतां", author: "चोखामेळा" },
            { id: "section_8_dha_7", title: "२४३. धोखै ही धोखै डहकायो", author: "सूरदास" },
        ]
      },
      {
        id: 'section_8_na',
        title: 'न',
        subsections: [
            { id: "section_8_na_1", title: "२४४. नको वाजवू श्रीहरि मुरली", author: "नामदेव" },
            { id: "section_8_na_2", title: "२४५. नन्निंद नाने जनिसि बंदेने", author: "कनकदास" },
            { id: "section_8_na_3", title: "२४६. नयन बसे रघुबीर", author: "तुलसीदास" },
            { id: "section_8_na_4", title: "२४७. नरहरि चञ्चल है मति मोरी", author: "रैदास" },
            { id: "section_8_na_5", title: "२४८. नवधा भगति कहउँ", author: "तुलसीदास" },
            { id: "section_8_na_6", title: "२४९. ना इन्नेनु पेळलि", author: "चिदानंद" },
            { id: "section_8_na_7", title: "२५०. नादव केळुत निद्रेय", author: "चिदानंद" },
            { id: "section_8_na_8", title: "२५१. ना निनगेनु बेडुवदिल्ल", author: "रंग विठ्ठल" },
            { id: "section_8_na_9", title: "२५२. ना निन्न ध्यानदोळिरुतिरलु", author: "पुरंदरदास" },
            { id: "section_8_na_10", title: "२५३. नाम तेंचि रूप", author: "नामदेव" },
            { id: "section_8_na_11", title: "२५४. नामदेव कीर्तन करी", author: "जनाबाई" },
            { id: "section_8_na_12", title: "२५५. नाम रूप दुई ईस उपाधी", author: "तुलसीदास" },
            { id: "section_8_na_13", title: "२५६. नाम वाचे श्रवणी कीर्ती", author: "निळोबा" },
            { id: "section_8_na_14", title: "२५७. नामामृतरसव कुडिदु", author: "भगवंतप्प" },
            { id: "section_8_na_15", title: "२५८. नारायण निन्न नाम", author: "कनकदास" },
            { id: "section_8_na_16", title: "२५९. नारायण निन्न नामद", author: "पुरंदरदास" },
            { id: "section_8_na_17", title: "२६०. नात्री तो हम भी करी", author: "" },
            { id: "section_8_na_18", title: "२६१. निज ऊहिसवारदु संपन्न", author: "निजगुणशिवयोगी" },
            { id: "section_8_na_19", title: "२६२. निज गुह्यद मातु", author: "महिपति" },
            { id: "section_8_na_20", title: "२६३. निजल्याने गाता उभा नारायण", author: "तुकाराम" },
            { id: "section_8_na_21", title: "२६४. निनगारु सरि इल्ल", author: "पुरंदरदास" },
            { id: "section_8_na_22", title: "२६५. निनगे दरूशनके", author: "विजयदास" },
            { id: "section_8_na_23", title: "२६६. निन्न निजव नीने", author: "पंचाक्षरी (नीरलकेरि)" },
            { id: "section_8_na_24", title: "२६७. निम्म नोट परम सुख", author: "बसवेश्वर" },
            { id: "section_8_na_25", title: "२६८. निरगुन ते एहि भाँति बड़", author: "" },
            { id: "section_8_na_26", title: "२६९. निर्गुण हमारे पिता लगत है", author: "" },
            { id: "section_8_na_27", title: "२७०. निर्विकल्प निराकार", author: "सोमनाथ पंचनदीकर" },
            { id: "section_8_na_28", title: "२७१. नीने एल्ल रूप ताळिरुवि", author: "चन्नमल्लिकार्जुन" },
            { id: "section_8_na_29", title: "२७२. नी याको", author: "पुरंदरदास" },
            { id: "section_8_na_30", title: "२७३. नूरु मातुगळ्याको", author: "मडिवाळयोगी" },
            { id: "section_8_na_31", title: "२७४. नेतिनेत्यादिनिगमवचनेन", author: "" },
            { id: "section_8_na_32", title: "२७५. नैनहीन को राह दिखा प्रभु", author: "अज्ञात" },
            { id: "section_8_na_33", title: "२७६. नयनेंद्रिय विषयदिंद (वचन)", author: "अखंडेश्वर" },
            { id: "section_8_na_34", title: "२७७. नोड सखी बेळगुतद", author: "पंचाक्षरी (नीरलकेरि)" },
            { id: "section_8_na_35", title: "२७८. नोडिरी ब्रह्मनाटव", author: "कूडलूरेश" },
            { id: "section_8_na_36", title: "२७९. नौकरी शरिअत से करना", author: "कबीर" },
        ]
      },
      {
        id: 'section_8_pa',
        title: 'प',
        subsections: [
            { id: 'section_8_pa_1', title: '२८०. पढ़ पढ़ कर पत्थर भए', author: '' },
            { id: 'section_8_pa_2', title: '२८१. (अ) परतर शिवलिंग', author: 'निजगुणशिवयोगि' },
            { id: 'section_8_pa_3', title: '२८१.  (ब) प्राणलिंगविदनु', author: 'निजगुणशिवयोगि' },
            { id: 'section_8_pa_4', title: '२८१.  (क) भावलिंगविदने', author: 'निजगुणशिवयोगि' },
            { id: "section_8_pa_5", title: "२८२. परमात्मनुनभव नररिंगे", author: "मनोहरपंत देशपांडे (अथणि)" },
            { id: "section_8_pa_6", title: "२८३. पवित्र तो देह वाणी पुण्यवंत", author: "तुकाराम" },
            { id: "section_8_pa_7", title: "२८४. पांडुरंग कांती दिव्य तेजे", author: "ज्ञानेश्वर" },
            { id: "section_8_pa_8", title: "२८५. पांडुरंगन नोडुणु नडि", author: "पुरंदरदास" },
            { id: "section_8_pa_9", title: "२८६. पादपूजेय माडि मुक्तादे", author: "शंकरानंद" },
            { id: "section_8_pa_10", title: "२८७. पामर जन्मविदु बलु खोट्टि", author: "अज्ञात" },
            { id: "section_8_pa_11", title: "२८८. पायाचा मी दास विठोबा", author: "बल्लव" },
            { id: "section_8_pa_12", title: "२८९. पायो जी मैने रामरतन", author: "मीराबाई" },
            { id: "section_8_pa_13", title: "२९०. पावन जस है माधो तेरा", author: "रैदास" },
            { id: "section_8_pa_14", title: "२९१. पावन पर्वत वेद पुराना", author: "तुलसीदास" },
            { id: "section_8_pa_15", title: "२९२. पाहणेची पाहसी काय", author: "ज्ञानेश्वर" },
            { id: "section_8_pa_16", title: "२९३. पूर्णप्रतापा भक्तवत्सला", author: "लक्ष्मणभटजी निंबरगी" },
            { id: "section_8_pa_17", title: "२९४. पूर्वजन्मी सुकृते थोर केली", author: "ज्ञानेश्वर" },
            { id: "section_8_pa_18", title: "२९५. पेळल्ळवे स्वानुभवद", author: "कल्मेश्वर" },
            { id: "section_8_pa_19", title: "२९६. पंचकरण सिद्धांत देख कर", author: "कबीर" },
            { id: "section_8_pa_20", title: "२९७. पंचलक्षणपूर्ण", author: "वेंकप्पा बरगी (विजापूर)" },
        ]
      },
      {
        id: 'section_8_pra',
        title: 'प्र',
        subsections: [
            { id: 'section_8_pra_1', title: '२९८. प्रभु मेरे औगुन चित न धरो', author: 'सूरदास' },
            { id: 'section_8_pra_2', title: '२९९. प्रलयपयोधिजले', author: 'जयदेव' },
            { id: 'section_8_pra_3', title: '३००. प्राप्यस्य ब्रह्मणो', author: '' },
            { id: 'section_8_pra_4', title: '३०१. प्रीति लगी तुव नाम की ', author: 'कबीर' },

        ]
      },
      {
        id: 'section_8_pha',
        title: 'फ',
        subsections: [
            { id: 'section_8_pha_1', title: '३०२. फागुन के दिन चार रे', author: 'मीराबाई' },
        ]
      },
      {
        id: 'section_8_ba',
        title: 'ब',
        subsections: [
            { id: 'section_8_ba_1', title: '३०३. बन्धनोंकी श्रृखलाको', author: 'गिरीशचंद्र शर्मा' },
            { id: 'section_8_ba_2', title: '३०४. बहुत हैरान हूँ भगवन', author: 'अज्ञात' },
            { id: 'section_8_ba_3', title: '३०५. बहुदोड्डुदी जन्म', author: 'सिद्धलिंगेश (रेवगीपूर)' },
            { id: 'section_8_ba_4', title: '३०६. बहुरि नहिं आवना या देस', author: 'कबीर' },
            { id: 'section_8_ba_5', title: '३०७. बा उभा ठेउनि कर कटी', author: 'दामाजीपंत' },
            { id: 'section_8_ba_6', title: '३०८. बाट पकड़ो सीधा', author: 'महिपति' },
            { id: 'section_8_ba_7', title: '३०९. बात करो दिन रात प्रभु कीं', author: 'कबीर' },
            { id: 'section_8_ba_8', title: '३१०. बाबा बा एन्न', author: 'नंद्याळ संग' },
            { id: 'section_8_ba_9', title: '३११. बालन बिन्नहवनु', author: 'लिंगप्प सावळगी' },
            { id: 'section_8_ba_10', title: '३१२. बाहर ढूँढ़न जा मत सजनी', author: 'ब्रह्मानंद' },
            { id: 'section_8_ba_11', title: '३१३. बाहुबळे तुवा काढिले अमृत', author: 'नामदेव' },
            { id: 'section_8_ba_12', title: '३१४. बिट्टु हिंगे इरलारे', author: 'सर्पभूषण' },
            { id: 'section_8_ba_13', title: '३१५. बिनु पग चलै', author: 'तुलसीदास' },
            { id: 'section_8_ba_14', title: '३१६. बिन्नहके बायिल्लवय्य', author: 'पुरंदरदास' },
            { id: 'section_8_ba_15', title: '३१७. बिल्वपत्रिय धरिस', author: 'उरगगिरिनिलय' },
            { id: 'section_8_ba_16', title: '३१८. बिसर गई सब', author: 'नानक' },
            { id: 'section_8_ba_17', title: '३१९. बिसलोळगे बिद्द मोसळेय', author: 'रत्नाकर' },
            { id: 'section_8_ba_18', title: '३२०. बृन्दाबन ढूँढ्यो', author: 'अज्ञात' },
            { id: 'section_8_ba_19', title: '३२१. बेट्टद मेलोंदु मनेय (वचन)', author: 'अक्कमहादेवी' },
            { id: 'section_8_ba_20', title: '३२२. बेरेयबारदे तिळिदु', author: 'सर्पभूषण' },
            { id: 'section_8_ba_21', title: '३२३. (अ) बेडिकोंबुवेनो श्री', author: 'प्रभुदेव' },
            { id: 'section_8_ba_22', title: '३२३. (ब) बेडिकोंबुवद्याको', author: 'भगवंतप्प' },
            { id: "section_8_ba_23", title: "३२४. बैलिगे बैलादितु", author: "पुरंदरदास" },
            { id: "section_8_ba_24", title: "३२५. बोधिसेन्ननु गुरुवे", author: "सर्पभूषण (गुरुसिद्ध)" },
            { id: "section_8_ba_25", title: "३२६. बोलमा बोलमा बोलमा रे", author: "मीराबाई" },
            { id: "section_8_ba_26", title: "३२७. ब्रह्म बेरे परब्रह्म बेरे", author: "भवतारक" },
            { id: "section_8_ba_27", title: "३२८. ब्रह्मानंदद सभेयोळगल्लि", author: "पुरंदरदास" },
            { id: "section_8_ba_28", title: "३२९. ब्रह्मानंदद सुखवेनु निनगे", author: "दिनकर बसव" },
            { id: "section_8_ba_29", title: "३३०. ब्राह्मणनेंदरे ब्रह्मन तिळिदव", author: "पुरंदरदास" },
            { id: "section_8_ba_30", title: "३३१. ब्राह्मण सो जो ब्रह्म पिछानै", author: "चरनदास" },
        ]
      },
      {
        id: 'section_8_bha',
        title: 'भ',
        subsections: [
            { id: "section_8_bha_1", title: "३३२. भक्त नेंदरे भक्त", author: "मनोहरपंत देशपांडे (अथणि)" },
            { id: "section_8_bha_2", title: "३३३. भक्तीनें जल पत्र", author: "अज्ञात" },
            { id: "section_8_bha_3", title: "३३४. भक्तेयानप्पेनय्य (वचन)", author: "अक्त महादेवी" },
            { id: "section_8_bha_4", title: "३३५. भज मन तुलसी राम कहो", author: "तुलसीदास" },
            { id: "section_8_bha_5", title: "३३६. भज मन राम चरन सुखदाई", author: "तुलसीदास" },
            { id: "section_8_bha_6", title: "३३७. भजो रे भैया राम", author: "कबीर" },
            { id: "section_8_bha_7", title: "३३८. भाई काहेकु लड़ते", author: "अज्ञात" },
            { id: "section_8_bha_8", title: "३३९. भूले मन समझ के लाद", author: "कबीर" }
        ]
      },
      {
        id: 'section_8_ma',
        title: 'म',
        subsections: [
             { id: "section_8_ma_1", title: "३४०. मक्कळाडिसुवाग", author: "जगन्नाथदास" },
            { id: "section_8_ma_2", title: "३४१. मगा हुट्टिदव्वा", author: "शिवलिंगव्वा (जत)" },
            { id: "section_8_ma_3", title: "३४२. मजहब नहीं सिखाता", author: "इकबाल" },
            { id: "section_8_ma_4", title: "३४३. मन मस्त हुआ तब क्यों बोले", author: "कबीर" },
            { id: "section_8_ma_5", title: "३४४. मन रे! परस हरि के चरन", author: "मीराबाई" },
            { id: "section_8_ma_6", title: "३४५. मन लागो यार फकीरी में", author: "कबीर" },
            { id: "section_8_ma_7", title: "३४६. मनसु पूजकरु", author: "अज्ञात" },
            { id: "section_8_ma_8", title: "३४७. मना भजले श्री भगवन्ता", author: "कबीर" },
            { id: "section_8_ma_9", title: "३४८. ममता तू न गई मेरे मन तें", author: "तुलसीदास" },
            { id: 'section_8_ma_10', title: '३४९. (अ) मलगि परमादरदि', author: 'जगन्नाथदास' },
            { id: 'section_8_ma_11', title: '३४९. (ब) मलगि पाडिदरे', author: 'पुरंदरदास' },
            { id: "section_8_ma_12", title: "३५०. महरम होय", author: "कबीर" },
            { id: "section_8_ma_13", title: "३५१. माई री मैंने लियो", author: "मीराबाई" },
            { id: "section_8_ma_14", title: "३५२. माझे जीवींची सांगात", author: "रामदास" },
            { id: "section_8_ma_15", title: "३५३. माझे दैवत सद्‌गुरुराज", author: "माधव" },
            { id: "section_8_ma_16", title: "३५४. माझ्या सद्‌गुरुचा अगाध", author: "मल्हारपंत जोशी" },
            { id: "section_8_ma_17", title: "३५५. मातुमातिगे शंकरा", author: "शंकरानंद" },
            { id: "section_8_ma_18", title: "३५६. माधव निन्न मूरुतियनु", author: "पुरंदरदास" },
            { id: "section_8_ma_19", title: "३५७. मानवजन्म दोड्डदु", author: "पुरंदरदास" },
            { id: "section_8_ma_20", title: "३५८. मीचि मज व्यालो", author: "तुकाराम" },
            { id: "section_8_ma_21", title: "३५९. मुत्तु", author: "पुरंदरदास" },
            { id: "section_8_ma_22", title: "३६०. मुत्तु बंददे को‌ळिरण्णा", author: "चिदानंद" },
            { id: "section_8_ma_23", title: "३६१. मुय्यक्के मुय्य तीरितु", author: "पुरंदरदास" },
            { id: "section_8_ma_24", title: "३६२. मुसाफिर सोता है", author: "कृष्णानंद" },
            { id: "section_8_ma_25", title: "३६३. मूडण देसेयोळु", author: "अज्ञात" },
            { id: "section_8_ma_26", title: "३६४. मेरेयदिरु मेरेयदिरु", author: "कनकदास" },
            { id: "section_8_ma_27", title: "३६५. मेरी सुरत गगन में", author: "ब्रह्मानंद" },
            { id: "section_8_ma_28", title: "३६६. मेरे काने गुंजेसे", author: "अज्ञात" },
            { id: "section_8_ma_29", title: "३६७. मेरो मन अनत कहाँ सुख", author: "सूरदास" },
            { id: "section_8_ma_30", title: "३६८. मैं पंथी एक अपार के", author: "दादू" },
            { id: "section_8_ma_31", title: "३६९. मैं मझधारा का माँझी हूँ", author: "अज्ञात" },
            { id: "section_8_ma_32", title: "३७०. मोह्यौ मृग देखि बन अन्धा", author: "दादू" }
        ]
      },
      {
        id: 'section_8_ya',
        title: 'य',
        subsections: [
            { id: "section_8_ya_1", title: "३७१. याके दय माडवल्लि", author: "पुरंदरदास" },
            { id: "section_8_ya_2", title: "३७२. याकेन्न ई राज्य", author: "पुरंदरदास" },
            { id: "section_8_ya_3", title: "३७३. याचेऽहं (करुणासिन्धो)", author: "मध्वाचार्य" },
            { id: "section_8_ya_4", title: "३७४. यातरिंदलि माडलि", author: "कूडलूरेश" },
            { id: "section_8_ya_5", title: "३७५. यादव नी बा", author: "पुरंदरदास" },
            { id: "section_8_ya_6", title: "३७६. या परी त्रिवेणी", author: "एकनाथ" },
            { id: "section_8_ya_7", title: "३७७. यारिगे यारिल्ल", author: "पुरंदरदास" },
            { id: "section_8_ya_8", title: "३७८. यारु कै बिट्टरू", author: "पुरंदरदास" },
            { id: "section_8_ya_9", title: "३७९. यावत् क्षणम्", author: "" },
            { id: "section_8_ya_10", title: "३८०. याव देशद हूविद्याव", author: "शिवलिंगव्वा" },
            { id: "section_8_ya_11", title: "३८१. या विधि मन को लगावै", author: "कबीर" },
            { id: "section_8_ya_12", title: "३८२. योगिगळ लीले पथविदु", author: "पर्वतमूर्ति" },
            { id: "section_8_ya_13", title: "३८३. योगि बंदनो शिवयोगि बंदनों", author: "नागलिंग" },
            { id: "section_8_ya_14", title: "३८४. योगिय मार्गविदम्मा", author: "भवतारक" }
        ]
      },
      {
        id: 'section_8_ra',
        title: 'र',
        subsections: [
            { id: "section_8_ra_1", title: "३८५. रघुवर तुमको मेरी लाज", author: "तुलसीदास" },
            { id: "section_8_ra_2", title: "३८६. रत्न बंददे नोडिरो", author: "शंकरानंद" },
            { id: "section_8_ra_3", title: "३८७. रमैया कि दुलहिनि", author: "कबीर" },
            { id: "section_8_ra_4", title: "३८८. रस गगन गुफा में", author: "कबीर" },
            { id: "section_8_ra_5", title: "३८९. रहना नहिं देस बिराना है", author: "कबीर" },
            { id: "section_8_ra_6", title: "३९०. राम कथा रस पी पी", author: "मध्वमुनीश्वर" },
            { id: "section_8_ra_7", title: "३९१. रामजी के नाम जिन्हे", author: "कबीर" },
            { id: "section_8_ra_8", title: "३९२. राम नाम सब कोइ कहे", author: "" },
            { id: "section_8_ra_9", title: "३९३. रामरस मीठारे, कोइ, पीवै", author: "दादू" },
            { id: "section_8_ra_10", title: "३९४. रामराज बैठे", author: "तुलसीदास" },
            { id: "section_8_ra_11", title: "३९५. राम राम राम । अवघेचि", author: "तुकाराम" },
            { id: "section_8_ra_12", title: "३९६. राम राम राम सीताराम", author: "पुरंदरदास" },
            { id: "section_8_ra_13", title: "३९७. रे दिल गाफिल", author: "कबीर" },
            { id: "section_8_ra_14", title: "३९८. रे मन जनम अकारथ जात", author: "सूरदास" },
            { id: "section_8_ra_15", title: "३९९. रे मन राम सों करि हेत", author: "सूरदास" },
            { id: "section_8_ra_16", title: "४००. रंग कोळलनूदलागि", author: "प्रसन्नवेंकट" },
            { id: "section_8_ra_17", title: "४०१. रंग पाहतां रंगुनि जा", author: "महिपती (ग्वाल्हेर)" },
        ]
      },
      {
        id: 'section_8_la',
        title: 'ल',
        subsections: [
            { id: 'section_8_la_1', title: '४०२. लिंगपूजे आगतण्णा', author: 'गंगाधर' },
            { id: 'section_8_la_2', title: '४०३. लिंगपूजेय माडिरो', author: 'सर्पभूषण (गुरुसिद्ध)' },
        ]
      },
      {
        id: 'section_8_va',
        title: 'व',
        subsections: [
            { id: "section_8_va_1", title: "४०४. वंदऊँ श्री हरि", author: "सूरदास" },
            { id: "section_8_va_2", title: "४०५. वस्तु अल्लिल्ल", author: "माणिकप्रभ्" },
            { id: "section_8_va_3", title: "४०६. वस्तु कंडेनो औंदु", author: "महिपति" },
            { id: "section_8_va_4", title: "४०७. वाचें बोला राम", author: "माधवात्मजा" },
            { id: "section_8_va_5", title: "४०८. विठ्ठल विठ्ठल गजरी", author: "चोखामेळा" },
            { id: "section_8_va_6", title: "४०९. विद्या मद औ गुषहुँ", author: "" },
            { id: "section_8_va_7", title: "४१०. विबुद्धतत्त्वस्यापि", author: "" },
            { id: "section_8_va_8", title: "४११. वैद्य भेटला सुखदाता", author: "रामदास" },
            { id: "section_8_va_9", title: "४१२. वैष्णव जन तो", author: "नरसि मेहता" },
            { id: "section_8_va_10", title: "४१३. वोई सतगुरु संत", author: "कबीर" },
            { id: "section_8_va_11", title: "४१४. वंदू श्री गुरुला", author: "सोमनाथ पंचनदीकर" },
        ]
      },
      {
        id: 'section_8_sha',
        title: 'श',
        subsections: [
          { id: "section_8_sha_1", title: "४१५. शंकर रामरूप", author: "तुलसिदास" },
          { id: "section_8_sha_2", title: "४१६. शब्दांची पै रत्ने", author: "तुकाराम" },
          { id: "section_8_sha_3", title: "४१७. शरण आतम की", author: "कृष्णानंद" },
          { id: "section_8_sha_4", title: "४१८. शरण तुम्हां हा", author: "हरि गोपाळ लिमये" },
          { id: "section_8_sha_5", title: "४१९. शरीरवेंबुव होलव", author: "सर्पभूषण (गुरुसिद्ध)" },
          { id: "section_8_sha_6", title: "४२०. शिंक जांभई", author: "रामी रामदास" },
          { id: "section_8_sha_7", title: "४२१. शिव शिव एनबारदे", author: "निजगुणशिवयोगि" },
          { id: "section_8_sha_8", title: "४२२. शिव सांब सांब", author: "अज्ञात" },
          { id: "section_8_sha_9", title: "४२३. शून्य शिखर में", author: "गोरखनाथ" },
        ]
      },
      {
        id: 'section_8_shra',
        title: 'श्र',
        subsections: [
            { id: 'section_8_shra_1', title: '४२४. श्रवणीं पेरिलें नयनीं उगवलें', author: 'शिवदिन केसरी' },
            { id: "section_8_shra_2", title: "४२५. श्रीगिरिय सुक्षेत्रकिंदू", author: "शांतमल्ल" },
            { id: "section_8_shra_3", title: "४२६. श्रीगुरुवे निम्म", author: "अज्ञात" },
            { id: "section_8_shra_4", title: "४२७. श्रीगुरु सारिखा", author: "ज्ञानदेव" },
            { id: "section_8_shra_5", title: "४२८. श्रीमन्मध्वमते हरि", author: "" },
            { id: "section_8_shra_6", title: "४२९. श्री रामनाम नुडियबारदे", author: "कृष्णहरि" },
            { id: "section_8_shra_7", title: "४३०. श्रीरामेवीण जे अन्न", author: "एकनाथ" },
            { id: "section_8_shra_8", title: "४३१. श्रेय धेनु बंतु मनेगे", author: "महिपति" },
        ]
      },
 
      {
        id: 'section_8_sa',
        title: 'स',
        subsections: [
          { id: "section_8_sa_1", title: "४३२. सगुण चरित्रे परम पवित्रे", author: "एकनाथ" },
          { id: "section_8_sa_2", title: "४३३. सगुण रूप नयनीं", author: "माणिकप्रभु" },
          { id: "section_8_sa_3", title: "४३४. सञ्चिन्तयेद्भगवतः", author: "" },
          { id: "section_8_sa_4", title: "४३५. सत है, दिन रात है", author: "अज्ञात" },
          { id: "section_8_sa_5", title: "४३६. सत्तर बरस तक घर बनाया", author: "ब्रजनाथ व्यास" },
          { id: "section_8_sa_6", title: "४३७. सदा नगारा कूच का", author: "" },
          { id: "section_8_sa_7", title: "४३८. सदा माझे डोळां", author: "तुकाराम" },
          { id: "section_8_sa_8", title: "४३९. सद्गुरु एल्लि हान", author: "त्रिमल्लेश" },
          { id: "section_8_sa_9", title: "४४०. सद्गुरु चरण वंदुनी शिरी", author: "गंगाबाई (तिकोटी)" },
          { id: "section_8_sa_10", title: "४४१. सद्गुरु निम्म मायके", author: "प्रभुदेव (हेम्मडगि)" },
          { id: "section_8_sa_11", title: "४४२. सद्‌गुरुविगे नानेनु माडि", author: "अज्ञात" },
          { id: "section_8_sa_12", title: "४४३. सद्‌गुरुविन चिंतियल्लि", author: "चिदानंद" },
          { id: "section_8_sa_13", title: "४४४. सद्‌गुरु साकिद मद्दाने", author: "कल्मेश्वर" },
          { id: "section_8_sa_14", title: "४४५. सन्त सन्त सब एक हैं", author: "" },
          { id: "section_8_sa_15", title: "४४६. साई अलख पलखमें झलके", author: "महिपति (ग्वाल्हेर)" },
          { id: "section_8_sa_16", title: "४४७. सात्विक श्रद्धा धेनु सुहाई", author: "तुलसीदास" },
          { id: "section_8_sa_17", title: "४४८. साधु कि संगत पाई रे", author: "मीराबाई" },
          { id: "section_8_sa_18", title: "४४९. साधू ऐसा चाहिऐ", author: "" },
          { id: "section_8_sa_19", title: "४५०. साधो सहज समाधि भली", author: "कबीर" },
          { id: "section_8_sa_20", title: "४५१. साधो सो सदगुरु मोहिं भावै", author: "कबीर" },
          { id: "section_8_sa_21", title: "४५२. सारिगे होगुणु बन्निरि", author: "चिक्कय्य" },
          { id: "section_8_sa_22", title: "४५३. सारि चल्लिदे मुकुति", author: "गुहेश्वर" },
          { id: "section_8_sa_23", title: "४५४. सावधनागि माडेलो", author: "भवतारक" },
          { id: "section_8_sa_24", title: "४५५. सुखविल्ल आत्मके", author: "कृष्णराय काखंडकि" },
          { id: "section_8_sa_25", title: "४५६. सुनु गिरिजा हरिचरित", author: "तुलसीदास" },
          { id: "section_8_sa_26", title: "४५७. सुनु मुनि तोहिं कहऊँ", author: "तुलसीदास" },
          { id: "section_8_sa_27", title: "४५८. सुना रे मैंने निर्बल के बल राम", author: "सूरदास" },
          { id: "section_8_sa_28", title: "४५९. सुन्न सहज मन सुमिरते", author: "" },
          { id: "section_8_sa_29", title: "४६०. सुमिरन कर ले मेरे मना", author: "नानक" },
          { id: "section_8_sa_30", title: "४६१. सुम्मनिरु नालिगे", author: "निरुपाधिसिद्ध" },
          { id: "section_8_sa_31", title: "४६२. सुरतिय नरतिय नागतिय", author: "" },
          { id: "section_8_sa_32", title: "४६३. सै शबास गबरु", author: "चिदानंद" },
          { id: "section_8_sa_33", title: "४६४. सै सद्‌गुरुविन दये", author: "महालिंगपूरेश (मंगळूर)" },
          { id: "section_8_sa_34", title: "४६५. सै सै सद्‌गुरुविन दयदिंदल्ल", author: "भीमाशंकर" },
          { id: "section_8_sa_35", title: "४६६. सै सै सै कुंतिदेने", author: "शिवालिंगव्वा (जत)" },
          { id: "section_8_sa_36", title: "४६७. सोइ सच्चिदानन्दघन रामा", author: "तुलसीदास" },
          { id: "section_8_sa_37", title: "४६८. सो काफिर जो बोलै", author: "दादू" },
          { id: "section_8_sa_38", title: "४६९. सोच समझ नादान पियारे", author: "कबीर" },
          { id: "section_8_sa_39", title: "४७०. संतचरणरज लागता सहज", author: "नामदेव" },
          { id: "section_8_sa_40", title: "४७१. स्थिर मुक्तिसंपदके", author: "शंकरानंद" },
          { id: "section_8_sa_41", title: "४७२. स्मरणेयोंदे सालदे", author: "पुरंदरदास" },
        ]
      },
      {
        id: 'section_8_ha',
        title: 'ह',
        subsections: [
           { id: "section_8_ha_1", title: "४७३. हम ऐसा देखा सतगुरु", author: "कबीर" },
          { id: "section_8_ha_2", title: "४७४. हमन है इश्क मस्ताना", author: "कबीर" },
          { id: "section_8_ha_3", title: "४७५. हरनीव कालक्के (वचन)", author: "बसवेश्वर" },
          { id: "section_8_ha_4", title: "४७६. हरिदासर संग दोरकितु", author: "पुरंदरदास" },
          { id: "section_8_ha_5", title: "४७७. हरिनारायण गुरु नारायण", author: "पुरंदरदास" },
          { id: "section_8_ha_6", title: "४७८. हरिनो मारग छे शूरानो", author: "प्रीतम" },
          { id: "section_8_ha_7", title: "४७९. हरियेंदु मनदोळु मरेदोम्मे", author: "पुरंदरदास" },
          { id: "section_8_ha_8", title: "४८०. हरि से कोई नहिं बडा", author: "कबीर" },
          { id: "section_8_ha_9", title: "४८१. हरिस्मरण विस्मरण", author: "सोहिरा" },
          { id: "section_8_ha_10", title: "४८२. हादिय कूडि होगु", author: "अज्ञात" },
          { id: "section_8_ha_11", title: "४८३. हाविन हेडेय कोंडु केन्नेय", author: "बसवेश्वर" },
          { id: "section_8_ha_12", title: "४८४. हावु कचितम्मा", author: "बलभीम" },
          { id: "section_8_ha_13", title: "४८५. हावु तुळिदेने मानिनि", author: "शरीफसाहेब" },
          { id: "section_8_ha_14", title: "४८६. हिग्गुवि एतको ई", author: "पुरंदरदास" },
          { id: "section_8_ha_15", title: "४८७. हिडि हिडि भावदलि", author: "महिपति" },
          { id: "section_8_ha_16", title: "४८८. हिंदिल्ल स्वामि मुंदिल्ल", author: "पुरंदरदास" },
          { id: "section_8_ha_17", title: "४८९. हुच्चु हिडियितु", author: "पुरंदरदास" },
          { id: "section_8_ha_18", title: "४९०. हुट्टिसुवात ब्रह्मनेंबरु", author: "बसवेश्वर" },
          { id: "section_8_ha_19", title: "४९१. हुरमुजी रंगाची उंच मूर्ती", author: "तुकाराम" },
          { id: "section_8_ha_20", title: "४९२. हुसेन साहेबर बदियलि", author: "सिद्धेश्वर (कलबुरगि)" },
          { id: "section_8_ha_21", title: "४९३. हेगिहरू चंद ज्ञानियु", author: "शंकरानंद" },
          { id: "section_8_ha_22", title: "४९४. हेगे तीरीतु निम्मुपकार", author: "मडिवाळयोगि (कडकोळ)" },
          { id: "section_8_ha_23", title: "४९५. है कोइ सन्त सहज सुख", author: "कबीर" },
          { id: "section_8_ha_24", title: "४९६. होळेव केंजडेगळ (वचन)", author: "अक्कमहादेवि" },
          { id: "section_8_ha_25", title: "४९७. हो तो कोई पिये", author: "कबीर" },
          { id: "section_8_ha_26", title: "४९८. हौदप्पा हौदप्पा", author: "निरुपाधिसिद्ध" },
          { id: "section_8_ha_27", title: "४९९. ह्यागे इरबेकु संसारदल्लि", author: "पुरंदरदास" },
          { id: "section_8_ha_28", title: "५००. ह्यागे मरेयली", author: "चिदानंद" },
        ]
      },
      {
        id: 'section_8_ksha',
        title: 'क्ष',
        subsections: [
            { id: 'section_8_ksha_1', title: '५०१. क्षणद संसारकागि', author: 'करिबसव (माशाळ)' },
        ]
      }
    ]
  },
  {
    id: 'section_9',
    title: '९. भुपाळ्या',
    subsections: [
      { id: 'section_9_sub_1', title: '१. उठा जी मायबाप (जागल्या)', author: 'एकनाथ' },
      { id: 'section_9_sub_2', title: '२. एळय्या आत्मारामा', author: 'महिपतिसुत' },
      { id: 'section_9_sub_3', title: '३. एकु सद्‌गुरुनाथ', author: 'अज्ञात' },
      { id: 'section_9_sub_4', title: '४. जागिए रघुनाथ कुँवर', author: 'तुलसीदास' },
    ]
  },
  {
    id: 'section_10',
    title: '१०. आरत्या',
    subsections: [
        { id: 'section_10_sub_1', title: '१. आरति बेळगुवेनु', author: 'अज्ञात' },
        { id: 'section_10_sub_2', title: '२. आरती उमदीशा', author: 'अज्ञात' },
        { id: 'section_10_sub_3', title: '३. आरती कहाँ लौ जोवै', author: 'रैदास' },
        { id: 'section_10_sub_4', title: '४. ऐसी आरति त्रिभुवन तारै', author: 'कबीर' },
        { id: 'section_10_sub_5', title: '५. कर्पूरारतियन्नु बेळगुवेनु', author: 'मनोहरपंत देशपांडे (अथणी)' },
        { id: 'section_10_sub_6', title: '६. काकडारती उजळू', author: 'एकनाथ' },
        { id: 'section_10_sub_7', title: '७. ओवाळू आरति माझ्या पंढरिनाथा', author: 'तुकाराम' },
        { id: 'section_10_sub_8', title: '८. जय जय जय गुरुलिंगा', author: 'अनामिक' },
        { id: 'section_10_sub_9', title: '९. जय जय मल्लेशा', author: 'अज्ञात' },
        { id: 'section_10_sub_10', title: '१०. जय जय सोपानदेवा', author: 'गोविंदबंधू' },
        { id: 'section_10_sub_11', title: '११. जय देव जय श्री उमदीशा', author: 'जोशी (तिकोटी)' },
        { id: 'section_10_sub_12', title: '१२. जय देव जय सद्‌गुरु रामा', author: 'भाऊराव आपटे (जमखंडी)' },
        { id: 'section_10_sub_13', title: '१३. जय जय श्री गुरुदेवा', author: 'मनोहरपंत देशपांडे (अथणी)' },
        { id: 'section_10_sub_14', title: '१४. जय देव जय सदानंदा', author: 'तिरुमल' },
    ]
  },
  {
    id: 'section_11',
    title: '११. प्रार्थना',
    subsections: [
      { id: 'section_11_sub_1', title: '१. देव हिरि गुरुराय', author: 'मनोहरपंत देशपांडे (अथणी)' },
      { id: 'section_11_sub_2', title: '२. पांडुरंगगे मंगळं', author: 'अनामिक' },
      { id: 'section_11_sub_3', title: '३. मंगलवागिहुदे', author: 'शंकरानंद' },
      { id: 'section_11_sub_4', title: '४. सदा बेळगुतद । ज्योति', author: 'निरुपाधिसिद्ध' },
      { id: 'section_11_sub_5', title: '५. स्वानंद सागर', author: 'मनोहरपंत देशपांडे (अथणी)' },
      { id: 'section_11_sub_6', title: '६. वरद हस्त ठेवा', author: 'भाऊराव आपटे (जमखंडी)' },
    ]
  },
  {
    id: 'section_12',
    title: '१२. स्तवने',
    subsections: [
      { id: 'section_12_sub_1', title: '१. अहो बत महद्भाग्यम्', author: 'भाउराव आपटे (जमखंडी)' },
      { id: 'section_12_sub_2', title: '२. यो रानडे वंशललामभूतः', author: 'लोकनायक, मा. श्री. अणे' },
    ]
  },
  {
    id: 'section_13',
    title: '१३. भारुडे',
    subsections: [
      { id: 'section_13_sub_1', title: '१. अजब हैं चित्रकूट', author: 'एकनाथ' },
      { id: 'section_13_sub_2', title: '२. आदि पुरुष निर्गुण', author: 'एकनाथ' },
      { id: 'section_13_sub_3', title: '३. सर्प चावला मज सर्प चावला', author: 'एकनाथ' },
    ]
  },
];
