export const devotee = [
  {
    id: '1',
    text: "During youth when one's senses are hale and sound, one should not go mad after women and wealth, and waste one's life merely in the enjoyment of sensuous pleasures. It is as good as fasting if one fails to taste the ambrosia of God's name which is the main purpose of human life. ",
    reference: "P.G.K.L. page no.51. ",
    category: 'Devotee',
  },
  {
    id: '2',
    text: "Long before the messengers of death make their appearance, one should be prepared spiritually to withstand the attack, and make up one's mind to enter on the spiritual path. ",
    reference: "P.G.K.L. page no.51. ",
    category: 'Devotee',
  },
  {
    id: '3',
    text: "The true disciple is he, who has suffered great pains, physical, mental and moral; who by the power of the pain has set his heart upon the Eternal in an utter disgust of the evanescent world;......for whom considerations of wealth and prosperity are of no significance. ",
    reference: "M.M.chapter XIX-40.page no. 396/517-518 ",
    category: 'Devotee',
  },
  {
    id: '4',
    text: "The first step in the advancement of spiritual life consists in rising from the life of sense to a belief in God and in those who are beloved of God. ",
    reference: "M.M.chapter III-74.page no.112/147. ",
    category: 'Devotee',
  },
  {
    id: '5',
    text: "Spiritual life cannot be nurtured without the company of the spiritual teacher, and the saints. The spiritual teacher and the saints perform the functions respectively of the mother and the nurse, or to vary the metaphor, of the sower and the gardener. ",
    reference: "P.G.H.L.page no.196/232. ",
    category: 'Devotee',
  },
  {
    id: '6',
    text: "There is no use going to places of pilgrimage. If the mind becomes pure, God lives in our very house, and can be seen by the devotee wherever he may be. ",
    reference: "M.M.chapter XI-2.page по.219/286. ",
    category: 'Devotee',
  },
  {
    id: '7',
    text: "When the equipment in moral virtues is being perfected, the next step in the path of Self-realisation is initiation by a worthy Spiritual Teacher...unless one be initiated by a Guru in the path of Self-realisation, one cannot attain the goal of mystic life. ",
    reference: "C.S.U.P. page no.242/329-330 ",
    category: 'Devotee',
  },
  {
    id: '8',
    text: "Why should we bother about Dvaita, Advaita, Vishishtadvaita and Shakti - vishishtadvaita and so on, Reality is beyond all these theories. A spiritual man has got nothing to do with these intellectual controversies. ",
    reference: "P.G.K.L. page no.117. ",
    category: 'Devotee',
  },
  {
    id: '9',
    text: "To awaken and intensify our love for spiritual life, we should try to have सत्संग (the holy company of saints and seekers). There is no other means so simple and effective than that. It would ensure our steady progress on the spiritual path. ",
    reference: "Glimpses 150-151. ",
    category: 'Devotee',
  },
  {
    id: '10',
    text: "In spiritual Sadhna meditative reading proves to be very valuable and effective. While reading we should also try to remember the name of Lord, that would certainly enhance the utility of reading. Also these factors would create a devotional atmosphere round about us which in turn would ultimately awaken and intensify our love for spiritual life. ",
    reference: "Glimpses 151-152 ",
    category: 'Devotee',
  },
  {
    id: '11',
    text: "God shows Himself to a devotee, only if this latter possesses good emotions and desires ",
    reference: "M.M.chapter V-2. .page no.167/221. ",
    category: 'Devotee',
  },
  {
    id: '12',
    text: "In order that a man's mind may be set on God, it is necessary that he should give himself to the reading, or hearing, or meditating of spiritual literature. ",
    reference: "M.M. chapter xix- 46.page no.401/522 ",
    category: 'Devotee',
  },
  {
    id: '13',
    text: "I and thou, thine and mine have rent a wedge in human existence. It is only when this duality ceases that one could cross the sea of life by the Grace of God. ",
    reference: "P.G.H.L.page no.122/156. ",
    category: 'Devotee',
  },
  {
    id: '14',
    text: "You ought to associate yourself with the good in order that you might be able to meditate on God intensely inside your heart. That is the highest thing a man is capable of, and that cannot be accomplished without the company of the good. ",
    reference: "P.G.K.L.page no. 44-45. ",
    category: 'Devotee',
  },
  {
    id: '15',
    text: "To meditate on God conceiving his Form in our mind is Sakama (with expectation of reward) and to meditate on God without conceiving His Form is Nishkama. God comes with greater love, to the man who meditates on His Name without thinking about His Form ",
    reference: "S.A.G.I.S.page no.147. ",
    category: 'Devotee',
  },
  {
    id: '16',
    text: "He who has a desire to see God should move in the company of the good, for without the company of the good, God cannot be attained. ",
    reference: "M.M.chapter XIX-30.page no.391/509. ",
    category: 'Devotee',
  },
  {
    id: '17',
    text: "Without rendering the highest reverential service to our Teacher (गुरुपादपंकजसेवा), the double lock of God-love and God-vision would not open out to us. ",
    reference: "P.G.H.L.page no.96/130. ",
    category: 'Devotee',
  },
  {
    id: '18',
    text: "We must have control over our breaths, we must meditate upon God, we must belong to the spiritual tradition and we must have the grace of Antaryamin. It is only then that we can realise God. ",
    reference: "P.G.K.L. page no.231. ",
    category: 'Devotee',
  },
  {
    id: '19',
    text: "The spiritual aspirant must always live in the company of the Saints, for other company may take away his mind from God. If one goes to see anybody at all, he should go to see a Saint. If one lives in the company of anybody, it should be in the company of the Saints. ",
    reference: "M.M.chapter XVI-51.page no.317/413. ",
    category: 'Devotee',
  },
  {
    id: '20',
    text: "An aspirant should walk in a balanced manner on the rope of the meditational process, though the weight he carries may be very heavy indeed. ",
    reference: "P.G.H.L.page no.158/193. ",
    category: 'Devotee',
  },
  {
    id: '21',
    text: "There is one way to reach God, namely, that we should go and take resort with the saints; for when we have worshipped the saints, we shall certainly see God. ",
    reference: "M.M.chapter VIII-4.page no.198/259-260. ",
    category: 'Devotee',
  },
  {
    id: '22',
    text: "The aspirant must have Bhava and Bhakti. It is only when you have definite devotion towards God, that God may listen to you. Otherwise, you may call upon him orally or 'strenuously with a bugle', and yet he may not appear before you at all. What is wanted is a devout heart for God, and not a mere oral or mechanical or verbal calling upon him. ",
    reference: "P.G.K.L.page no.65. ",
    category: 'Devotee',
  },
  {
    id: '23',
    text: "For the realisation of the Self, one should lead a life of introversion, with an utter disgust for the world and catharsis from sins, a spirit of humbleness, and a life of tranquility, truth, penance, insight, strength, and right pursuit. Unless these conditions are fulfilled, the aspirant after spiritual life may never hope to realise the Self. ",
    reference: "C.S.U.P.page no.221/329. ",
    category: 'Devotee',
  },
  {
    id: '24',
    text: "Whenever we find ourselves in a critical situation, we should lift our minds towards God, throw ourselves upon His mercy, and pray to Him to protect us from opposing evils. ",
    reference: "P.G.H.L.page no. 126/159-160. ",
    category: 'Devotee',
  },
  {
    id: '25',
    text: "We cannot find reality in the Mantras. They are merely rafts which are likely to sink in the ocean of life. Therefore, we must hold on to the steers-man, namely, God, who will take us to the other shore. ",
    reference: "B.G.P.G.R. page no.16-17. ",
    category: 'Devotee',
  },
  {
    id: '26',
    text: "When we shut all the sense organs to outer perceptions, then probably by proper meditation on God, and by His Grace, internal senses open, and we are able to perceive, hear and speak things which it would be ordinarily impossible for human beings to do. ",
    reference: "P.G.H..L.page no. 200/236 ",
    category: 'Devotee',
  },
  {
    id: '27',
    text: "We should lead a life of utter ignorance about all things except God. The knowledge of God is devotion, and the knowledge of God is realisation ",
    reference: "M.M.chapter V-3.page no.167/222. ",
    category: 'Devotee',
  },
  {
    id: '28',
    text: "The body should be devoted to the service of the parents, who are holier than any other holy objects. The Guru must particularly be worshipped, who so compassionately bestowed upon us Knowledge, and showed us the way out of the wilderness of Samsara. ",
    reference: "M.M.chapter III-52.page no.95/124-125. ",
    category: 'Devotee',
  },
  {
    id: '29',
    text: "Unless we repent, God's name shall not come to our lips. Repentance is the cause of ecstasy. If one sincerely repents, God is not far from him. ",
    reference: "M.M.chapter XI-4.page no.220/287. ",
    category: 'Devotee',
  },
  {
    id: '30',
    text: "That God may remain in a friendly way with us depends upon our own way of behaving with Him; for, the echoes of our words come in the very manner in which we utter them. If we solely devote ourselves to God, God becomes solely devoted to US. ",
    reference: "M.M.chapter XIX-52.page no.405/528-529 ",
    category: 'Devotee',
  },
  {
    id: '31',
    text: "God appears to those who surrender themselves to Him. Those who are having spiritual intuition and those who are poor in spirit have the vision of God. ",
    reference: "P.G.K.L.page.no.165. ",
    category: 'Devotee',
  },
  {
    id: '32',
    text: "We must utilise our hands, eyes, feet and all other organs of sense, in a proper manner, in the service of God, so that they might be receptacles of the vision, audition, and other experiences of God. ",
    reference: "P.G.K.L. page no. 51. ",
    category: 'Devotee',
  },
  {
    id: '33',
    text: "God is not very distant from those who have conquered their hearts, and have stilled their passions. When the dross material in base gold has been driven off, what remains is pure gold itself; similarly, when desire disappears, the Individual Soul becomes Brahman.. ",
    reference: "M.M.chapter III-50.page no.93/122. ",
    category: 'Devotee',
  },
  {
    id: '34',
    text: "An Aspirant is indeed he who has gone in all submissiveness to his Teacher and has been instructed by him on the path to God. When his Spiritual Teacher opens out to him the pathway to Atman, the shackles of his worldly existence are destroyed; and yet he performs Sadhana in order to be convinced of his liberation. ",
    reference: "M.M.chapter XIX. 51.page no.404/527. ",
    category: 'Devotee',
  },
  {
    id: '35',
    text: "What the eyes of ordinary people cannot visualise, what their mind cannot imagine, the Aspirant tries to realise in his own experience. What cannot be expressed by word of mouth, what would ordinarily dazzle the eye, the Aspirant tries to realise on his own account.... Where the mind comes to a standstill, where logic is of no avail, that the Aspirant tries to apprehend by the power of his own spiritual experience. ",
    reference: "M.M.chapter XIX-51.page no.404-405/527-528. ",
    category: 'Devotee',
  },
  {
    id: '36',
    text: "A devotee must have a perfectly devout heart towards God. Without devotion we can achieve nothing. There is no use in calling mechanically upon God, 'unknowingly'; there is no use in calling upon God without Bhava and Bhakti. ",
    reference: "P.G.K.L. page no.65. ",
    category: 'Devotee',
  },
  {
    id: '37',
    text: "The true disciple is he, who devotes himself to the service of humanity; who is jealous of none; who has great courage and moral determination; who does not spare himself any pains in the pursuit of the spiritual life; who knows the ways and means of the development of Paramartha; ",
    reference: "M.M.chapter XIX-40.page no.397/518. ",
    category: 'Devotee',
  },
  {
    id: '38',
    text: "It is not simply by performing our devotional acts that we may be able to achieve our highest goal. God must be moved and it is only when He is moved that He will move the world by His Grace. ",
    reference: "B.G.P.G.R.page no.255/226. ",
    category: 'Devotee',
  },
  {
    id: '39',
    text: "Spiritual life cannot be nurtured without the company of the spiritual teacher, and the saints. It is only in the company of the good that our virtuous life flowers, and when we come across those who have reached the highest state of realisation, it fructifies. ",
    reference: "P.G.H.L.page no.196/232. ",
    category: 'Devotee',
  },
  {
    id: '40',
    text: "In order to secure the friendship of God, we should not mind even if we were to lose our nearest relatives. We should ultimately sacrifice everything to God, including even our own life. It matters not if we lose all in order to gain the friendship of God. ",
    reference: "M.M.chapter XIX-52.page no.405/528. ",
    category: 'Devotee',
  },
  {
    id: '41',
    text: "You should always be very careful. When you will be caught up in the grip of death, your mind will suffer from qualms of conscience and cry remorsefully. So before you get those pangs you must see that God becomes your friend. So approach your spiritual teacher, and begin your spiritual life in right earnest; do not mearly make a show of it. ",
    reference: "P.G.K.L. page no.53. ",
    category: 'Devotee',
  },
  {
    id: '42',
    text: "When the light and the sound experiences have been attained, God might take it into his head to make an appearance before you. But lest he might appear and run away, 'we should look at him gently, continuously. Do not allow him to run away. ",
    reference: "P.G.K.L. page no.200. ",
    category: 'Devotee',
  },
  {
    id: '43',
    text: "Mystical phenomena are a necessary accompaniment of mystical life. But what constitutes the essence of mystic realisation is not these mystical phenomena themselves, but an unfaltering, unbending, unending love of God. ",
    reference: "M.M.preface 12 page no.21/xxviii ",
    category: 'Devotee',
  },
  {
    id: '44',
    text: "Unless we realise our absolute impotence before the majestic power of God, it may not be possible for God's Grace to descend upon us. ",
    reference: "P.G.H.L.page no.181-182/217. ",
    category: 'Devotee',
  },
  {
    id: '45',
    //fixit
    text: "This constitutes them in your heart. the sign-post on your way towards ",
    reference: "P.G.K.I. page no.58. ",
    category: 'Devotee',
  },
  {
    id: '46',
    text: "There is only one favour that we should ask of God: that we should always think of Him in our heart; that we should always utter His name by our mouth; that we should always see Him with our eyes; that our hands should worship only Him; that our head be placed always at His feet; that our ears should only hear of God's exploits; that He should show Himself always to our right and to our left, before and after, and at the end of our life. We should ask God of no other favour except this. ",
    reference: "M.M.chapter VIII-5.page no.200/262. ",
    category: 'Devotee',
  },
  {
    id: '47',
    text: "Your spiritual teacher might be staying millions of miles away, and yet you can send your Self as a messenger on the तुरङ्गम of Shabda, or on Shabda as experienced in the तुरीय state; and as the speed of the Anahata Shabda or spirit would far exceed that of any entity known to science such as light or electricity, contact would be established between yourself and the Guru, and for the matter of that, between yourself and God, within the twinkling of an eye-lash. ",
    reference: "P.G.H.L.page no.362/399-400. ",
    category: 'Devotee',
  },
  {
    id: '48',
    text: "What is the use of coming to this terrestrial existence if after putting faith in the spiritual teacher we do not become even like unto him who imparted to us spiritual wisdom? ",
    reference: "P.G.K.L. page no.67. ",
    category: 'Devotee',
  },
   {
    id: '49',
    text: "r highest ideal is to approach, in meritorious deeds and in spiritual realisation, spiritual teacher because we regard that our spiritual teacher is identical with God.",
    reference: "P.G.K.L. page no.67.",
    category: 'Devotee',
  },
  {
    id: '50',
    text: "During this short sojourn if we do not make ourselves worthy of our spiritual teacher and God, it is no use to be born in this world at all.",
    reference: "P.G.K.L. page no.67.",
    category: 'Devotee',
  },
  {
    id: '51',
    text: "We must throw ourselves upon the mercy of God and be reconciled with whatever happens.",
    reference: "P.G.K.L. page no.86.",
    category: 'Devotee',
  },
  {
    id: '52',
    text: "Great power comes out of a disinterested love for God which slights the realisation of any fruits. What the devotee has in mind, God brings to fruition of His own accord. There is no necessity for the devotee to take any thought about the matter. When the devotee's disinterested love is coupled with the great power of God, Death itself cannot stand the onslaught of the combination.",
    reference: "M.M.chapter XIX-45.page no.401/522.",
    category: 'Devotee',
  },
  {
    id: '53',
    text: "The Methodology of Meditation by means of which God may be attained - The first of these is evidently the Name of God, by the help of which the Teacher directs his disciple to meditate on God. Secondly, we are told that this meditation must be of a fully concentrated type. And thirdly, this meditation must be immediate, must be practised here and now and must not suffer any loss of time. When all these criteria are fulfilled, the disciple may regard himself definitely as on the way to God.",
    reference: "S.A.G.I.S.-page no.167.",
    category: 'Devotee',
  },
  {
    id: '54',
    text: "The human body is the field. It should be tilled with the help of the oxen of tranquility and self-control. The weeds of egoism should be removed; the manure of equanimity should be evenly spread over the field and the field completely levelled. Then the seeds of the instructions of the spiritual teacher should be sown. The rain of meritorious actions should water the field, and the superfluous growth of vicious deeds should be weeded out. This will enable one to rear the rich crop of eternal liberation and push away the famine of worldly existence out of borders.",
    reference: "P.G.K.L. page no.49-50.",
    category: 'Devotee',
  },
  {
    id: '55',
    text: "Devotee by his power can even rule over God. Before the power of his devotion, no other power avails. Who can rule God except His devotee? Wherever the Devotee sits, all things come of their own accord, and nobody ever dares to do him wrong.",
    reference: "M.M.chapter XVI-76.page no.342/447.",
    category: 'Devotee',
  },
  {
    id: '56',
    text: "Mind can be conquered only by mind. But even that is possible only when the grace of the Guru is secured. This unconquerable mind is, as it were, a maid-servant of the Guru, and is at his beck and call. If, therefore, it is handed over to the control of the Guru, it shall give the aspirant the contentment and bliss which it alone can give.",
    reference: "M.M.chapter XII-30.page no.243/317.",
    category: 'Devotee',
  },
  {
    id: '57',
    text: "The first thing, an aspirant must be free from, is attachment to wealth and woman. Let alone divine life even the ordinary and worldly life would become unhappy. if a man has a strong attachment to these. He is the seat of doubt, whose mind is maddened by attachment to wealth and woman. He becomes a stranger to worldly happiness; what then of divine life! He who loves money and is conquered by woman is shunned by God, who lives in the temple of the body.",
    reference: "M.M.chapter XII-25. Page no.241/315",
    category: 'Devotee',
  },
  {
    id: '58',
    text: "The vision of God is not a matter of child play; it requires long and patient toil, almost to the point of exhaustion or even disbelief.",
    reference: "P.G.H.L. page no.95/129",
    category: 'Devotee',
  },
  {
    id: '59',
    text: "If thou regardest thyself as an agent, thou shalt land thyself into many difficulties; on the other hand, if thou believest that God is the real agent, then shalt thou attain to fame, and to greatness, and to power.",
    reference: "M.M.chapter XIX-5.page no.376/489.",
    category: 'Devotee',
  },
  {
    id: '60',
    text: "The study of philosophy for oneself and for others (आतमविद्या) becomes a cardinal requisite for the determination of the nature of God, and consequently for our attachment to Him.",
    reference: "P.G.H.L.page no.96/130.",
    category: 'Devotee',
  },
  {
    id: '61',
    text: "One must throw aside all his greatness; one must forget all his learning; one must become smaller than the smallest thing in the world; only then could he hope to come in God's presence.... One must leave away all the pride of body, and wealth, and virtue, and then seek God.",
    reference: "M.M.chapter III-24.page no.65/84",
    category: 'Devotee',
  },
  {
    id: '62',
    text: "There are only two ways for the attainment of spiritual life: one is that we should not get ourselves contaminated with others' wealth; the other is that we should not contaminate ourselves with others' women. Seeking of wealth means losing of Paramartha.",
    reference: "M.M.chapter XI-4.page no.221/288",
    category: 'Devotee',
  },
  {
    id: '63',
    text: "Principally, we should observe one rule in life: we should never follow what our mind dictates to us. What the mind regards as happiness comes ultimately to be experienced as unhappiness We should thus always keep our mind imprisoned at God's feet.",
    reference: "м.M.chapter XI-4.page no.222/289",
    category: 'Devotee',
  },
  {
    id: '64',
    text: "Our earnest passion for spiritual welfare should gush up like a fountain towards God. Such a warm zeal can be developed through discrimination and holy company. Intellectual study of the literature of saints will be of some use to facilitate discrimination. But along with it meditation should be necessarily performed. Otherwise we won't be able to understand clearly the real significance of such literature.... This discrimination should be accompanied by the company of saints for developing its efficacy. These two would greatly help to intensify devotion and zeal of the seeker.",
    reference: "Glimpses 150-151.",
    category: 'Devotee',
  },
  {
    id: '65',
    text: "We should go to solitude and fix our mind on God, should not allow our mind to wander, should avoid all frivolity.... should set our heart on reality, and pierce it as an arrow pierces the mark. We should bid good-bye to idleness and to sleep, and live in the constant wakefulness of God.",
    reference: "M.M.chapter XVI-49. page no.314/409",
    category: 'Devotee',
  },
  {
    id: '66',
    text: "When Sattvic qualities predominate the disciple is indifferent to everything for the sake of God. He has left off all happiness for the sake of God. His mind may move in the direction of sense, but he has forever within him the ballast of Spirit.",
    reference: "M.M.chapter XIX-42.page no.398/519.",
    category: 'Devotee',
  },
  {
    id: '67',
    text: "We must control our senses, and use them not for worldly pleasure, but in the service of God, so that we may taste by the grace of God the ambrosial juice from the name of God. No relatives and nothing in the world will protect us from the servants of the god of death, when they come to take us away from this world. We should therefore have a firm hold on spiritual life before the attack comes.",
    reference: "P.G.K.L. page no. 48-49.",
    category: 'Devotee',
  },
  {
    id: '68',
    text: "The spiritual aspirant gains the ripe fruit of self-realisation only when he implicitly acts according to the orders of his spiritual teacher.",
    reference: "M.M.chapter IV-19.page no. 162/215.",
    category: 'Devotee',
  },
  {
    id: '69',
    text: "'Whatever you desire, Oh God, is welcome to me.' If we just submit to God in this way, He would be gracious to lead us towards Himself.",
    reference: "P.G.K.L. page no.43.",
    category: 'Devotee',
  },
  {
    id: '70',
    text: "secondary Bhakti concerns itself with Ritualism, with Kirtana, with Dhyana Puja, and even with Namasmarana. Primary Bhakti, on the other hand, mea up-springing of the pure fount of love in man towards God. When we once ta this, nothing else matters; but if we have only secondary devotion, we can supposed to have known the nature of Supreme Devotion.",
    reference: "M.M.chapter 1-8.page no.L",
    category: 'Devotee',
  },
  {
    id: '71',
    text: "An ideal disciple is one who is like faith incarnate and who is a flute in the han of his master.",
    reference: "क.प.सो. पा.क्र.१०४",
    category: 'Devotee',
  },
  {
    id: '72',
    text: "Only he can hope to know God, who turns his back from the requirements of sense;",
    reference: "M.M.chapter III-24.page no.66/84.",
    category: 'Devotee',
  },
  {
    id: '73',
    text: "Those who devote all the operations of the mind and senses to God and meditate without distinction of day and night, such devotees God prizes more than anything else.",
    reference: "M.M.chapter III-28.page no.69/89.",
    category: 'Devotee',
  },
  {
    id: '74',
    text: "If inside the mind is purified by the words of the Guru, that purity is sure to reveal itself through external activities. Mere bodily purity, without the purity of the heart, is absolutely useless.....What is absolutely necessary, therefore, is an internal purity of the heart coupled with the external purity of good actions.",
    reference: "M.M.chapter XII-32.page no.239/312",
    category: 'Devotee',
  },
  {
    id: '75',
    text: "Unless the mind is cleared of the weeds of ideas, the Name of God would not take root in it. The driving of ideas should properly be accomplished in the psycho- ethical manner. If this is not possible, then the disciple might invert and revert his breath, and concentrate on it, or else make his mind travel between the मूलाधार and सहस्रार. Thus, when the mind is caught up either in the name of God, or in the breath, or in the passage from मूलाधार to सहस्रार, other ideas will cease, and the idea of God will be regnant in the mind of the aspirant, who will thus be enabled to reach the 'Unmani' state. The eye-lashes will now cease to function, and the unmoving eyes will remain focussed on an unmoving spiritual form of God.",
    reference: "P.G.H.L.page no.214/251.",
    category: 'Devotee',
  },
  {
    id: '76',
    text: "Unless our consciousness is directed upwards, unless it bathes in the lake of the lateral ventricle, unless it enters the territory called Ajara and unless it is able see that inexpressible form of God, we shall not be entitled to have satisfied ourselves with saying that we have entered the path of God.",
    reference: "P.G.H.L.page no.155/190.",
    category: 'Devotee',
  },
  {
    id: '77',
    text: "The true method of worship by which God can be propitiated is to bathe him with honour, to anoint him with love, to place flowers of sweet and humble words on his forehead, and to make him a continuous oblation of one's self.",
    reference: "P.G.H.L.page no.210/247.",
    category: 'Devotee',
  },
  {
    id: '78',
    text: "Thus God should be the sole object of the aspirant's meditation, even in dream and in sleep. His mind should know no other object of contemplation. The natural bent of the senses should be in the direction of God, and the eyes should ever see His vision.",
    reference: "M.M.chapter XVI-51.page no.317/414.",
    category: 'Devotee',
  },
  {
    id: '79',
    text: "Our devotion to God should never change the aspect it bore at the beginning of the search; on the other hand, it should deepen in intensity as it proceeds.",
    reference: "P.G.H.L.page по.180/215.",
    category: 'Devotee',
  },
  {
    id: '80',
    text: "One should not fill his vision with the evanescence of the world. He should consider that the mortal body is destined to perish, and that Death is eating it up every moment. He should seek company of the Saints, and make haste for the spiritual life. He should not allow his eyes to be blinded by the smoke of worldly existence.",
    reference: "M.M.chapter XVI-50.page no. 315/410.",
    category: 'Devotee',
  },
  {
    id: '81',
    text: "The very moment that the disciple comes under the grace of his Spiritual Teacher, he finds the door of liberation open to him.",
    reference: "P.G.H.L.page no.336/373.",
    category: 'Devotee',
  },
  {
    id: '82',
    text: "He who knows no hatred of any being; ..who neither upholds the good nor discards the evil;...... Who has friendship with the whole world and is as it were the fount of pity; who knows no egoism; who has no sense of mine-ness; to whom happiness is as good as sorrow; who in point of sufferance is equal to the earth; who has given contentment a constant abode in his heart; in whose mind the individual Self and the universal Self both live together in close unison; who having achieved the highest stage of Yoga, delivers over his mind and intellect to God; he alone is the true devotee.",
    reference: "M.M.chapter 111-99.page no.130/171.",
    category: 'Devotee',
  },
  {
    id: '83',
    text: "The infinite must be invoked with a devotional heart but it is very difficult to entertain such intense devotion, such a passionate longing for the Lord. It is only the company of Saints that can induce it.",
    reference: "Glimpses 149",
    category: 'Devotee',
  },
  {
    id: '84',
    text: "Vision of God remains steady before the mystic when he is in the company of the saints. When alone to himself, his mind may not be equipoised; but when he is in the company of the saints, it remains absolutely steady, untouching, unmoving and equanimous which may well be regarded as the height of spiritual experience.",
    reference: "P.G.K.L.page no.275.",
    category: 'Devotee',
  },
  {
    id: '85',
    text: "The true disciple is he, who has his heart purified by repentance; whose mind has been made tranquil by the words of his master; finally, whose pure devotion knows no back-turning, even though the heavens might fall upon him.",
    reference: "M.M.chapter XIX-40.page no.397/517-518.",
    category: 'Devotee',
  },
  {
    id: '86',
    text: "Unless we annihilate ourselves completely, we have no hope of reaching God. So preparedness for self-annihilation is a necessary condition of spiritual success.",
    reference: "P.G.H.L.page no.295-296/331-332.",
    category: 'Devotee',
  },
  {
    id: '87',
    text: "When Sattvika qualities predominate in a man, he loves the narration of God's works. He transforms his original qualities for the service of God...... He loves the Saints more than himself, and is not ashamed of doing small things for the sake of God. He leaves aside everything else, and engages himself in devotion to God. ......He becomes weary of all, and loves only the spiritual life;",
    reference: "M.M.chapter XIX-42.page no.398/519.",
    category: 'Devotee',
  },
  {
    id: '88',
    text: "The true disciple is he, whose heart is not set upon power; who has a firm belief in the words of his master; who has merged himself in the personality of his master; who is pure and spotless; who is of an ascetic temper, and observes the mean in all matters.",
    reference: "M.M.chapter XIX-40.page no.397/517-518.",
    category: 'Devotee',
  },
  {
    id: '89',
    text: "The Aspirant indeed is he who revives the lost tradition of Atmajnana. He has once for all bade good-bye to evil actions, and has been multiplying virtuous actions in order that he might ultimately get lodgment in the Form of God..... With a firm determination, he tries to merge himself in the Atman.",
    reference: "M.M.chapter XIX-51.page no.404/527.",
    category: 'Devotee',
  },
  {
    id: '90',
    text: "Only through one-pointed devotion to God that one may be able to know Him, see Him and enter into Him.",
    reference: "B.G.P.G.R.page no.255/226.",
    category: 'Devotee',
  },
  {
    id: '91',
    text: "The aspirant should rather lose his life than lose the jewel of Atman which is the telos of his life, and on which therefore the active seeker must intensely concentrate in the midst of all his actions.",
    reference: "P.G.H.L.page no.158-159/193.",
    category: 'Devotee',
  },
  {
    id: '92',
    text: "The true disciple is he, who is distinguished by a capacity for effort; who is endowed with great insight, as he has been able to visualise the invisible Atman;",
    reference: "M.M.chapter XIX-40.page no.397/517-518.",
    category: 'Devotee',
  },
  {
    id: '93',
    text: "It is only those who are full of devotion to God, for whom the Guru acts as a steersman, and who take recourse to the raft of Self-realization, for such we may say the flood of Maya ceases to exist even before they have tried to cross it.",
    reference: "M.M.chapter III-19.page no.62/79.",
    category: 'Devotee',
  },
  {
    id: '94',
    text: "The spiritual aspirant must be full of concentration. Concentration should be so intense that as soon as you begin to concentrate, the form of God should appear before you.",
    reference: "P.G.H.L.page no.158/192.",
    category: 'Devotee',
  },
  {
    id: '95',
    text: "It is only when senses are brought under control, that the mind is able to find itself. It recoils upon itself, and feels its identity with the Self. When this experience is obtained, one reaches the empire of happiness, and then loses oneself by merging in the Self.",
    reference: "M.M.chapter III-88.page no.122/161.",
    category: 'Devotee',
  },
  {
    id: '96',
    text: "An aspirant seeks the company of the Saints in order that his doubts may be dispelled, and he tries to bring his spiritual experience on a par with the teachings of the Sastras, as well as with the teachings of his Spiritual Teacher...... He throws off his bodily egoism and centres his heart upon Atman.",
    reference: "M.M.chapter XIX-51.page no.404/527.",
    category: 'Devotee',
  },
  {
    id: '97',
    text: "We should behave exactly as God wishes us to behave. We should give up our happiness in order to attain the friendship of God, and must not mind sacrificing ourselves for His sake. We should forget the pain of worldly life, and should always engage ourselves in meditation on God.",
    reference: "M.M.chapter XIX-52.page no.405/528.",
    category: 'Devotee',
  },
  {
    id: '98',
    text: "In order that God-devotion might develop in us, we must sing his praise, think of his qualities, narrate his exploits and contemplate on the spiritual words which he might have left for us.",
    reference: "P.G.H.L.-page no.85/119-120.",
    category: 'Devotee',
  },
  {
    id: '99',
    text: "God can bring any fruits to us whatsoever; but a desire for fruits stands between ourselves and God. Hence the necessity of a disinterested love of God.",
    reference: "M.M.chapter XIX-45.page no.401/522.",
    category: 'Devotee',
  },
  {
    id: '100',
    text: "The devotee, must have God-devotion. He should resolve that there is no object of love greater than God. He should devote his body and speech and mind solely to God's contemplation. He who becomes one with God, and yet maintains devotion towards God, may be said to be Knowledge incarnate.",
    reference: "M.M.chapter III-44.page no.81-82/106.",
    category: 'Devotee',
  },
  {
    id: '101',
    text: "The Aspirant must offer himself as a sacrifice before the altar of God by waving the Arati of his life in the midst of lights and sounds and perfumes.",
    reference: "P.G.H.L.page no.159/194.",
    category: 'Devotee',
  },
  {
    id: '102',
    text: "It is the business of the disciple to hum round the lotus feet of his master and suck as much honey as he can.",
    reference: "P.G.K.L. page no.106-107.",
    category: 'Devotee',
  },
  {
    id: '103',
    text: "The Methodology of Meditation by means of which one could attain to Reality. Silence should be observed. A certain poise of meditation should be made steady. The mind should feel happy in the illumination of knowledge, and finally One should enjoy the ambrosia of self realisation. When we have done that, and succeeded in doing it for a long time, then it is possible that we might get an insight into the nature of God-head.",
    reference: "P.G.K.L. page no. 106-107",
    category: 'Devotee',
  },
  {
    id: '104',
    text: "The first requisite for the spiritual aspirant is shutting himself to the outside world and turning his vision inward.",
    reference: "P.G.K.L.page no.298",
    category: 'Devotee',
  },
  {
    id: '105',
    text: "The second requisite for the spiritual aspirant is to follow the golden mean. The bliss of Brahman can be had when we are able to travel by the middle path leaving aside the two extremes. Evidently travelling by the middle path would mean that the aspirant must avoid the extremes of self-indulgence and self-torture.",
    reference: "P.G.K.L.page no.298",
    category: 'Devotee',
  },
  {
    id: '106',
    text: "The third requisite for being a recipient of divine bliss is that one has to wash away the dirt of one's mind. Till then the form of God cannot be mirrored in the mind... Washing away of the dirt of the mind and the mirroring of God's form are reciprocally connected. Unless the filth of the mind is washed away, God cannot be reflected in the mind, and unless one sees God in it, its filth cannot be fully washed away.",
    reference: "P.G.K.L.page no.299",
    category: 'Devotee',
  },
  {
    id: '107',
    text: "We can not hope to reach God unless we have completely controlled our senses. The senses must not compel us to follow the innumerable objects of desire, if we want to achieve the supreme object of desire, namely, God.",
    reference: "B.G.P.G.R.page no.214/189.",
    category: 'Devotee',
  },
  {
    id: '108',
    text: "God-realisation also implies a complete sacrifice of all our possessions for the sake of God. This is really what is meant by Yajna. The sacrifice of all objects to God brings in its train the sacrifice involved in our dispassionately doing good to all fellow-beings.",
    reference: "B.G.P.G.R.page no.214/189.",
    category: 'Devotee',
  },
  {
    id: '109',
    text: "Observation of the mean is a necessary condition of spiritual life. We must eat food, but take it only in a measured quantity. We must do actions, but in a measured manner. We must speak measured words. We must measure our steps. We may also by measure go to sleep. If we are to keep awake, that also we must do by measure. In this way, when equanimity is produced in the body, great happiness will arise.",
    reference: "M.M.chapter III-50.page no.94/122",
    category: 'Devotee',
  },
  {
    id: '110',
    text: "If we want to cross the terrific stream of Mayanadi, we must have a steersman in the shape of a spiritual teacher. We must have a rudder in the shape of devotion.",
    reference: "B.G.P.G.R. page no.62/56.",
    category: 'Devotee',
  },
  {
    id: '111',
    text: "It is only when these three things meet, namely, the spiritual teacher, devotion and mystical experience, that we have the possibility of crossing that great flood of illusion.",
    reference: "B.G.P.G.R. page no.62/56.",
    category: 'Devotee',
  },
  {
    id: '112',
    text: "The devotee himself must become lean in the service of his teacher, and feed on the love of his Guru. He must become the sole receptacle of the instructions of his Guru; he should feel himself of a high lineage on account of his Guru, and must find his nobility in the good actions of his brother-pupils; his sole absorbing topic should be the constant service of his Guru; the line which his Guru lays down for carrying on his spiritual work, he should regard as binding upon him like rules of Castes and Ashramas... The Guru must be his place of pilgrimage; the Guru his deity, the Guru his mother and father; ....",
    reference: "M.M.chapter III-36.page no.76/99.",
    category: 'Devotee',
  },
  {
    id: '113',
    text: "Ideal Disciple - The disciple is described as born upon earth like Faith incarnate and as resplendent Penance; The disciple is absolutely oblivious and unmindful of his own greatness. It is the duty of such an ideal disciple to sing the glory of his master. He has no other vocation. He might be great in a way; but then he must be wholly forgetful of it. He must become a flute in the hands of his master, and act reflexly or automatically and do whatever the teacher directs him to do. He milks the Kamadhenu, the wish-fulfilling cow, and distributes the milk to the society and",
    reference: "",
    category: 'Devotee',
  },
  {
    id: '114',
    text: "Granted that all the preparation is made for the realisation of God, that one meets the Guru, that the Guru imparts to him the knowledge of the true path; granted that the seed that is sown is the best of its kind, yet it is only in course of time that a rich harvest can be reaped.",
    reference: "B.G.P.G.R.page no.72/65.",
    category: 'Devotee',
  },
  {
    id: '115',
    text: "It is not a two years', three years' or a five years' plan that would be enough to enable him to reach the God-hood. In fact, time has got nothing to do with it. What is wanted is the inner quality of the heart which may enable man to conquer time. In order however, that, that quality might be attained, अभ्यास may be necessary but it is not all. If you have reached a particular stage of भाव, then neither much time nor much practice would be needed.",
    reference: "B.G.P.G.R.page no.238/211-212.",
    category: 'Devotee',
  },
  {
    id: '116',
    text: "Suppose a man has spent about fifty years of his life in the spiritual pursuit; of course, it may be granted that he may be on a comparatively higher level than what he occupied a few years ago; but he can never be said, only on that account, to have reached the Absolute End.",
    reference: "B.G.P.G.R.page no.238/212.",
    category: 'Devotee',
  },
  {
    id: '117',
    text: "In order to attain spiritual heights, however, a great travail has to be experienced. This we might call the travail of unison. The dangers we have to meet, the temptations we have to face, the calamities we have to suffer, all these constitute the travail, through which we must pass before we attain to the crown of spiritual experience.",
    reference: "P.G.H.L. page no.367/405.",
    category: 'Devotee',
  },
  {
    id: '118',
    text: "The only Asana that a Sadhaka should perform is one in which he can sit or lie down for a long time and at the same time fill himself with joy in such a way that he may not be required to move from his seat: स्थिरसुखमासनम्.",
    reference: "B.G.P.G.R.page no.249/221",
    category: 'Devotee',
  },
  {
    id: '119',
    text: "Kama is the chiefest enemy which must be first conquered. What in modern psycho-analysis is regarded as a powerful element in human nature must be conquered, if moral and spiritual progress is to be made. Even to talk about lust, would itself be an act of lust.",
    reference: "B.G.P.G.R.page no.252/224.",
    category: 'Devotee',
  },
  {
    id: '120',
    text: "As a mirror may be covered by dust, as fire may be covered by smoke or as a fœtus might be covered by amniotic membrane, even so our spiritual life may be covered by lust. We have to drive it away; then alone would the Atman be born.",
    reference: "B.G.P.G.R.page по.252/224.",
    category: 'Devotee',
  },
  {
    id: '121',
    text: "Let our mind be composed; let fear be away from our mind; let there be no regnant emotion in our system. Then alone would we be able to concentrate on God.",
    reference: "B.G.P.G.R.page no.253/224.",
    category: 'Devotee',
  },
  {
    id: '122',
    text: "In order to reach the pinnacle of spiritual life, the sub-conscious flavour or Rasa which lies latent in our mind must first be destroyed, and this cannot be done without a previous vision of God.",
    reference: "B.G.P.G.R.page no.253/225.",
    category: 'Devotee',
  },
  {
    id: '123',
    text: "What is the use of merely looking at the tip of the nose or even controlling breath or trying to purge the mind of all sensual and sexual ideas? Unless we feel an earnest devotion to God, i.e. Bhava or Bhakti, nothing would be of any avail whatsoever.",
    reference: "B.G.P.G.R.page no.254/225.",
    category: 'Devotee',
  },
  {
    id: '124',
    text: "In the first place, that we should be inspired with one-pointed devotion towards God. We should have no other object of attachment. Then secondly, we must practise meditation without sacrificing a single moment and finally this must be continued from day to day, month to month and year to year to the very end of our life.",
    reference: "B.G.P.G.R.page no.254/225.",
    category: 'Devotee',
  },
  {
    id: '125',
    text: "We must not, however, fail to note that Bhava or Bhakti, an unexplained and inexplicable love of God, is a fundamental requirement; meditation from hour to hour and day to day and even concentration on the name of God are of secondary importance.",
    reference: "B.G.P.G.R. page no.254/226.",
    category: 'Devotee',
  },
  {
    id: '126',
    text: "Unless there is the element of surrender in our devotion and unless we resign ourselves completely to the Power and Will of God, no great achievement in spiritual life is possible.",
    reference: "B.G.P.G.R. page no.254-55/226.",
    category: 'Devotee',
  },
  {
    id: '127',
    text: "Our sight must be directed to the spiritual object of perception, but not to the physiological tip of the nose, either up or down. That is intended only to fasten the mind and to make it a little composed, and to draw it away from the objects of sense-perception.",
    reference: "B.G.P.G.R.page no.251/223.",
    category: 'Devotee',
  },
  {
    id: '128',
    text: "Whatever a devotee mystically experiences is always an index of his own spiritual achievement.",
    reference: "B.G.P.G.R.page no.70/63.",
    category: 'Devotee',
  },
  {
    id: '129',
    text: "Resignation or submission to the will of God would be a more potent instrument of achieving the end than either belief in an unseen power or a philosophic reconciliation with a world order.",
    reference: "P.G.H.L. page no.40-41/75.",
    category: 'Devotee',
  },
  {
    id: '130',
    text: "Bhakti should make the throat choked with love, should make the hair stand on end, and should compel divine tears from meditating eyes. When, therefore, complete happiness and peace are enjoyed, when 'Anubhava' is attained, when all the psycho- physical effects are experienced, then alone is true Bhakti generated. They are the criteria of Bhakti.",
    reference: "M.M. 1-9 page no. 14/19.",
    category: 'Devotee',
  },
  {
    id: '131',
    text: "Uttering the name of God, feeling His presence near himself, experiencing His immanence in the mind, or realising his identity with God, the seeker goes on to the last Mukti, namely, शरणगमनमुक्ति.",
    reference: "P.G.H.L. page . 132/166.",
    category: 'Devotee',
  },
  {
    id: '132',
    text: "We are full of joy when we are in the contemplation and realisation of God. That state of beatification is itself our liberation. Liberation is not to be found after death. But to know God, to do His work, to enjoy His presence and to devote oneself to His service are exactly what a Jivan-mukta ought to do.",
    reference: "B.G.P.G.R. page no. 190/169.",
    category: 'Devotee',
  },
  {
    id: '133',
    text: "The crowning piece of the performance, however, is the passionate longing of the aspirant for the realisation of God. It is this inner urge, this one-pointed and search, this life of consecration to the ideal, which crowns the efforts of man for the attainment of God.",
    reference: "P.G.H.L. page no.363/400",
    category: 'Devotee',
  },
  {
    id: '134',
    text: "The moral requirements of a man who wishes to be a Bhakta: He should, in the first place, leave all enjoyments, leave all contact with objects of sense, incessantly meditate on God without wasting a single minute, and always hear of God's qualities.",
    reference: "M.M.chapter 1-9.page no.12/18.",
    category: 'Devotee',
  },
  {
    id: '135',
    text: "The Bhakta should give himself up to the study of the Bhaktishastras, and should not waste words in vain. He should pray for the grace of the Saints and the grace of God;",
    reference: "M.M.chapter I-9.page no.12/18.",
    category: 'Devotee',
  },
  {
    id: '136',
    text: "The Bhakta should spend his life in serving the good. He should live in solitude, should not care for livelihood, should not hear of women, should not think about wealth, should not associate with thieves.",
    reference: "M.M.chapter 1-9.page no.12/18.",
    category: 'Devotee',
  },
  {
    id: '137',
    text: "The Bhakta should cultivate the virtues of non-injury, truth, purity, compassion, and belief in God. He should deliberately set himself to transform his natural emotions, and make them divine. Passion and anger and egoism, he should transform and utilize for the service of God. In fact, a divine transformation of all the natural emotions must take place in him.",
    reference: "M.M.chapter 1-9.page no.12.18.",
    category: 'Devotee',
  },
  {
    id: '138',
    text: "An aspirant must cultivate the virtue of bearing with the defects of others. ...To attend to the faults or defects in others is the worst of all faults in men. Virtue consists in not observing either the vice or virtue in others. If Brahman truly transcends the duality of vice and virtue, he who is prone to notice the faults or merits in others can be safely declared not to have attained to a true realisation of Brahman. Divine experience will forsake a man who attends to the vices or virtues in others.",
    reference: "M.M.chapter XII-23.page no.240/313-314.",
    category: 'Devotee',
  },
  {
    id: '139',
    text: "The Bhakta should not give himself up to argumentation; for there is no end to argumentation. It is manifold, and cannot be bridled. The devotee should be careless of the censure of others, and should have no anxiety whatsoever while he meditates.",
    reference: "M.M.chapter 1-9.page no.12/18-19.",
    category: 'Devotee',
  },
  {
    id: '140',
    text: "For the attainment of the non-perception of the duality of virtue and vice in others, man must cultivate another but closely allied virtue of enduring abuse from others. Why should a man ever think of retaliation or revenge, when a man who slanders is but his own reflex?",
    reference: "M.M.chapter XII-24.page no.240/314",
    category: 'Devotee',
  },
  {
    id: '141',
    text: "The human mind is proverbially fickle, and so long as it is not completely lost in God's meditation, who knows what it may not love! ... lust may rise even in old age. An aspirant must, therefore, keep himself aloof from the influence of woman.",
    reference: "M.M. chapter XII-27.page no.242/316",
    category: 'Devotee',
  },
  {
    id: '142',
    text: "The first step towards purification, the sine qua non of spiritual life, is a searching self-examination culminating in repentance. For that alone has the power to wash off all dirt generated in the human mind by the evil contact with sense-objects.",
    reference: "M.M.chapter VII-29.page no.242/316",
    category: 'Devotee',
  },
  {
    id: '143',
    text: "To pin our faith upon stone images is a vain pursuit. A stone god and an illusory devotee can never satisfy each other.",
    reference: "M.M.chapter VIII-3.page no.196/257.",
    category: 'Devotee',
  },
  {
    id: '144',
    text: "We should steadily perform our Sadhana and get spiritual experiences ourselves. We should accept that form of God to be real of which we have got an actual vision.",
    reference: "Glimpses 141",
    category: 'Devotee',
  },
  {
    id: '145',
    text: "We should enkindle the divine lamp within us. Then His light would automatically radiate in all directions. If the flower blooms, its fragrance would spread far and wide of its own accord. God is blissful. Spiritual life begins with the experience of at least an iota of that bliss.",
    reference: "Glimpses 141",
    category: 'Devotee',
  },
  {
    id: '146',
    text: "Spiritual life must be sought for and cultivated as an end in itself and never as a means to achieve other ends. Then alone we would attain our cherished goal, viz. God-realisation; otherwise not.",
    reference: "Glimpses 145",
    category: 'Devotee',
  },
  {
    id: '147',
    text: "The power, once communicated to you by the spiritual teacher, will lead you on to infinite progress. It does not require any further help of any kind. The progress will not be merely arithmetical; but super-mathematical.",
    reference: "Glimpses 140",
    category: 'Devotee',
  },
  {
    id: '148',
    text: "We should not allow our initial devotion to falter or change in the slightest degree.'... [cite: 54, 55] Our devotion should increase day after day...... Our devotion must grow.",
    reference: "P.G.K.L. page no.58.",
    category: 'Devotee',
  },
  {
    id: '149',
    text: "One does not know when the body may fall. One does not know what calamities may befall us. Hence, we should always be on the alert, should do all that we can for spiritual life, and fill the world with the holy name of God.",
    reference: "M.M.chapter xix-75.Page no.419/547",
    category: 'Devotee',
  },
  {
    id: '150',
    text: "Godliness will come to you, even if you make up your mind to start your spiritual life just now. It is never too late to begin doing the right thing, begin your spiritual career at once.",
    reference: "P.G.K.L.page no.52",
    category: 'Devotee',
  },
  {
    id: '151',
    text: "One must throw aside all his greatness; one must forget all his learning; one must become smaller than the smallest thing in the world; only then could he hope to come in God's presence.... One must leave away all the pride of body, and wealth, and virtue, and then seek God.",
    reference: "M.M.chapter III-24.page no.65/84",
    category: 'Devotee',
  },
  {
    id: '152',
    text: "The only source of happiness in this life is betaking oneself to the Spiritual Teacher. We should hand him over all our wealth and body and mind, and take from him in exchange the form of God. This will not come to our vision without the grace of the Spiritual Teacher. It is already inside us; but we do not know that this is so.",
    reference: "M.M.chapter VIII-11.page no.205/269.",
    category: 'Devotee',
  },
  {
    id: '153',
    text: "As the trees in a forest become fragrant by a sandal tree, which is in the midst of them, similarly, people begin to love God when there is a devotee in the midst of them.",
    reference: "M.M.chapter V-13.page no.176/234.",
    category: 'Devotee',
  },
  {
    id: '154',
    text: "Our daily meditation should be coupled with the holy company of saints. Then alone will it bear proper fruit. It is in the company of saints that we would realise the real value of meditation. If we try to live in their company for a good many days and observe their behaviour minutely we would understand how they have realised their identity with God.",
    reference: "Glimpses 116",
    category: 'Devotee',
  },
  {
    id: '155',
    text: "The spiritual pathway is not straight. It is zig-zag; it is spiral. Hence our progress along the path is bound to be spiral. When we are proceeding along the winding path we have, at times, the unique pleasure of having a glimpse of the beautiful scenery ahead. Just then, our path takes a turn and the scene goes out of sight which gives us a good deal of pain. Still, it does leave a faint memory of it which enables us to maintain our effort to reach the top, to have the vision of the scene once again. In this way, such occasional glimpses inspire and goad us onwards till we attain our highest goal.",
    reference: "Glimpses 119-120",
    category: 'Devotee',
  },
  {
    id: '156',
    text: "Our psychology must not move outside spiritual life. Spirituality should permeate our whole life.",
    reference: "Glimpses 119",
    category: 'Devotee',
  },
  {
    id: '157',
    text: "For a devotee, his spiritual progress alone is of the highest value. Nothing else counts for him as much, not even the freedom of his country. For spiritual progress, peace or status quo is chiefly needed and not revolutionary conditions. There is sometimes a sudden and great progress in distracted conditions, no doubt. But that is temporary, not permanent. Permanent progress is possible during peace only. The experiences received during distracted conditions do not re-appear for years thereafter.",
    reference: "Glimpses 120",
    category: 'Devotee',
  },
  {
    id: '158',
    text: "The two factors involved in the attempt towards the realisation of divine experience - The first is the extraordinary courage which will not be daunted to make a holocaust of everything, and the second is the forgetfulness of everything except God.",
    reference: "M.M.chapter XII-47.page no.252/329.",
    category: 'Devotee',
  },
  {
    id: '159',
    text: "The Yoga of Namasmarana is the only path that can enable the Sadhaka to attain God-head. This path alone can take a Sadhaka into the inner sanctuary and grant him the vision and bliss of divinity. '... there is no other path for going there. All the saints of the world, have followed the same Pathway and have bequeathed its knowledge to posterity.",
    reference: "Glimpses page no. 147/164.",
    category: 'Devotee',
  },
  {
    id: '160',
    text: "Until a man is able to see his own Form by the Grace of his spiritual teacher, he may not be regarded as having attained to the highest mystical experience.",
    reference: "P.G.H.L.page no.170/205.",
    category: 'Devotee',
  },
  {
    id: '161',
    text: "An aspirant leaves away all passion and anger, all vanity and jealousy, all shame and pride of family. He has dispelled all doubts,...cut off the shackles of death, and has once for all destroyed the round of births and deaths.",
    reference: "M.M.chapter XIX-51.page no.405/528.",
    category: 'Devotee',
  },
  {
    id: '162',
    text: "As such, it is no wonder, if final victory and infinite auspiciousness, which are the very nature of God, belong as well to the devotees, who have made a conflagration of themselves in the burning fire of God-love.",
    reference: "P.G.K.L. page no.318.",
    category: 'Devotee',
  },
  {
    id: '163',
    text: "In the experience of this Advaita-Bhakti, a devotee becomes so merged in God that he becomes one with Him. The devotee, therefore, merges himself in his object of devotion so much so that there comes about an absolute unity between them.",
    reference: "B.G.P.G.R.page no.159.142.",
    category: 'Devotee',
  },
  {
    id: '164',
    text: "The mystics teach that a rising devotee must ultimately feel his identity with his own Self. It is only then that there is perfect unison; but whatever a devotee mystically experiences is always an index of his own spiritual achievement.",
    reference: "B.G.P.G.R.page no.70/63.",
    category: 'Devotee',
  },
  {
    id: '165',
    text: "The devotee attains to the Godhead, falling just short of His entire Being. The reason for this approximation or asymptotic realisation is the physical, the mental and other limitations of the mystic.",
    reference: "B.G.P.G.R.page no. 71/64.",
    category: 'Devotee',
  },
  {
    id: '166',
    text: "Even though the devotee may reach unison with God, yet he remains a devotee. The saint remains a saint so long as he has to discharge his bodily functions.",
    reference: "B.G.P.G.R.page no.71/64.",
    category: 'Devotee',
  },
  {
    id: '167',
    text: "The Aspirant tries to become one with God..He has found out the root of both God and Man, and has immediately become one with the Ideal... In a superconscious state, he has seen the Self for all time, and brought the Aspirant's life to completion... When this mental attitude is firmly fixed in him, he begins to lead a different life in his outward actions.",
    reference: "M.M.chapter XIX-51.page no. 405/527.",
    category: 'Devotee',
  },
  {
    id: '168',
    text: "The intellect of a man in whom the Sattva quality is augmented, so fills his being that it oozes out of him. Discrimination fills all his senses; his very hands and feet become endowed with vision; the senses of such a man can discriminate between the good and the bad. What must not be heard, the ear itself refuses to hear; what must not be seen, the eye itself refuses to see; what must not be spoken, the tongue itself refuses to speak; from him bad things run away; his intellect transcends its own limits in the knowledge of the sciences; A stop is put to his activities. His mind becomes disgusted with the objects of sense. When these qualities become augmented in a man, if he happens to meet his death at such a moment,.. his new being becomes as full of the Sattva quality as the old, and he takes on a birth among those who pursue knowledge for its own sake.",
    reference: "M.M.chapter III-12.page no.56/71-72.",
    category: 'Devotee',
  },
  {
    id: '169',
    text: "The Grace of God descends upon the aspirant who is nearing his perfection in three stages. In the first place, God gives a particular bent to his intellect and volition, a stimulus and a direction in which he might work (Buddhiyoga), Secondly, after he has worked unceasingly in this direction for a long time, he becomes the recipient of God's compassion (Anukampa), And finally, God crowns his efforts with the gift of His blessing (Prasada).... It is only when the aspirant has passed through all these three stages, namely, Buddhiyoga, Anukampa and Prasada, that we might say that the Grace of God has fully descended on him.",
    reference: "B.G.P.G.R.page no.255/227.",
    category: 'Devotee',
  },
  {
    id: '170',
    text: "In the way of meditation, however, there are four pitfalls, against which an aspirant must guard himself. They are: dissipation, passion, fickleness and absorption. All these are the faults of an unsteady mind. To revolve in the mind the Sweetness of sense-objects, when one is sitting in a meditative posture, is dissipation. To attend only to love-stories or descriptions of sexual unions, is passion. To pass from one field of consciousness to another, and thus to be every moment unsteady like a madman, is fickleness. To be inattentive through sad difference to the chief object of meditation, and thus to be ultimately lost in sleep, in blue or yellow colours is absorption",
    reference: "M.M.chapter XII-51.page no.253-254/331-332.",
    category: 'Devotee',
  },
  {
    id: '171',
    text: "A devotee is he who resigns all his things to the care of the Guru, and makes himself the temple of devotion; to the devotee's heart, the place where the Guru resides is the only object of attention. He verily regards a moment spent without the Guru as greater than a world cycle. When any person brings some news from the Guru, or when the Guru himself sends some word to him, he feels as if a dead man should come to life again.",
    reference: "M.M.chapter III-36.page no.75/97.",
    category: 'Devotee',
  },
  {
    id: '172',
    text: "When our heart is purified, we see God. Mere meditation will not necessarily lead to the vision of God. Spiritual experience depends upon the purity and intensity of our heart.",
    reference: "Glimpses 133-134",
    category: 'Devotee',
  },
  {
    id: '173',
    text: "The only way towards receiving Guru's grace is to adore the saints...They are the temple of knowledge; our service constitutes its threshold; we should take possession of it by resorting to it. We should touch their feet in body and mind and thought. We should do all sorts of service to them with utter absence of egoism, and then they will tell us what we desire. Our mind shall forthwith cease to give rise to conjectures; our intellect shall grow strong in the light of their words;. ...doubt shall cease; all beings will then be seen as in God; the darkness of infatuation will disappear; the light of knowledge shall shine; and the Guru will send down his grace",
    reference: "M.M.chapter III-75.page no.113/149.",
    category: 'Devotee',
  },
  {
    id: '174',
    text: "While we are contemplating God, both body and mind are entirely transformed. When the Self has been transformed in God, and when the mind has been suffused with Illumination, the whole of creation looks divine, and all of a sudden the influx of God fills the whole world.",
    reference: "M.M.chapter XVI-81page no.346/453.",
    category: 'Devotee',
  },
  {
    id: '175',
    text: "If once God reveals Himself to the devotee in his heart, then that vision cannot be confined to the devotee's heart only. He sees God everywhere. God reveals Himself to him as the all-pervading Atman, assuming various forms. Once He is thus revealed in His true universal form, a devotee becomes dead to all world-vision.",
    reference: "M.M.chapter XII-52.page no.254/332.",
    category: 'Devotee',
  },
  {
    id: '176',
    text: "Once God is revealed, the subtle body, the cause of all bondage, perishes without a stroke. His spiritual light dispels all desires. With the destruction of desires, vanish all doubts and duties. As darkness cannot stand before the light of the Sun, dualities with their effects, Avidya with ignorance, Jiva with Siva, egoism with its knots of spirit and matter, all vanish away. Even the constant repetition of the formula 'I am Brahman' is no more to be heard. All fear of birth and death disappears, and the stage is reached where the world is not, and God alone is. His devotees reach this stage by constantly praying to Him.",
    reference: "M.M.chapter XII-52.page no.254/332.",
    category: 'Devotee',
  },
  {
    id: '177',
    text: "A devotee, who has realised God, transcends the responsibilities of all the stages of life. Constant association with God is now his duty. Now neither good action, nor renunciation, nor discrimination can bring him any profit. He, who has surrendered himself to God, has paid all his debts to deities, sages, ancestors and men. He, who has clearly understood his distinctness from body and senses can have now no gain from the controlling of his senses. To him, who has truly realised God, no higher gain can be obtained by constant meditation on Him. He is merged in Brahmic consciousness, even when he is enjoying all sense-objects",
    reference: "M.M.chapter XII-54.page no.255/333.",
    category: 'Devotee',
  },
  {
    id: '178',
    text: "Only then can a man be supposed to have reached the end of his spiritual life, when he has personally known that all his sins have come to an end; when he has known that the round of births and deaths has come to a stop; when he has known both God and Self, and when he has experienced the extreme surrender of Self to God; when he has known the stuff out of which the world is made; and when he has known who has been responsible for the creation of it. When a man still entertains doubt about these matters, then his pursuit of the spiritual life has been in vain. He has merely merged himself in doubt without any experience. This indeed is the secret of the realisation of spiritual life.",
    reference: "M.M.chapter XIX-58.page no.409/534.",
    category: 'Devotee',
  },
];