export const god = [
  {
    id: '1',
    text: 'God is not an ultimate to which other penultimate realities point. We may say that God is super-ultimate.',
    reference: 'B.G.P.G.R. page no.157/140-141',
    category: 'God',
  },
  {
    id: '2',
    text: 'God indeed is the universal mover. He moves the body as well as the universe. It is God only who can make us hear or see...... He alone can continue the mind in its egoism. He it is who can make even the leaf of a tree move.... God has filled the Whole inside and outside. What can be lacking to Him in His universal presence?"',
    reference: 'M.M.chapter XVI-68. page no.331/433',
    category: 'God',
  },
  {
    id: '3',
    text: 'God, who is hidden to the sight of ordinary men, can be attained only in the company of the Good.',
    reference: 'M.M.chapter XIX-59.page no.410/535',
    category: 'God',
  },
  {
    id: '4',
    text: 'We talk about the ten directions which envelope the universe, but God spreads His hands and feet beyond them. So omnipresent is God! There is not a nook or a cranny of the universe which is not filled with God.',
    reference: 'P.G.K.L.page no.168.',
    category: 'God',
  },
  {
    id: '5',
    text: 'God is the All - both the formed and the formless, the mortal and the immortal, the stationary and the moving, the this and the that.. He is the verity of verities, for all these are verities, and He is the supreme verity.',
    reference: 'C.S.U.P. page no.155/213.',
    category: 'God',
  },
  {
    id: '6',
    text: 'God May be regarded as the Soul of Souls. Both the moving and the stationary are the forms of God; this is as much as to say that, God is the Soul of organic as well as inorganic nature. He fills the Souls as he fills the Universe, and controls them both as their inner governor.',
    reference: 'C.S.U.P. page no.155/213.',
    category: 'God',
  },
  {
    id: '7',
    text: 'God is everywhere. God is omnipotent. Let us submit ourselves to God. When our mind has merged itself in God, then alone shall we be free from all sorts of anxieties; because everything that happens to us does so by the will and direction of God.',
    reference: 'P.G.K.L.page no.42.',
    category: 'God',
  },
  {
    id: '8',
    text: "The universally immanent God must be identified with one's self. This is as much as to say that we must have the experience of Tattvamasi or Soham. Unless this takes place the moss of delusion will not disappear, infatuation will not come to an end.",
    reference: 'P.G.H.L. page no. 118/152.',
    category: 'God',
  },
  {
    id: '9',
    text: "God, indeed, cannot be shown by a lamp, nor can he be found out by means of light. For God's vision, there is no collyrium that can be applied to the eye to make Him visible. Nor can God be revealed in the searchlight of the Sun, or in the pleasing light of the Moon. Such a God can yet be shown by the Saint to the Seeker.",
    reference: 'M.M.chapter XIX-36. Page no.395/515',
    category: 'God',
  },
  {
    id: '10',
    text: 'The one God to whom we should send our heart-felt prayer is far above all other petty deities, just as the Ganga is above all rivers, or the Lotus above all brambles.',
    reference: 'P.G.H.L. page no.127/161.',
    category: 'God',
  },
  {
    id: '11',
    text: "When God once calls a man His own, one cannot imagine what he may do. His justice, his forethought, his ready wisdom, and his knowledge of other peoples' hearts are all of them the gifts of God. His efforts, his alertness, his courage in the nick of time, his great prowess are all of them gifts of God. His fame, his power, his greatness, and his incomparably rare qualities are all the gifts of God.",
    reference: 'M.M.chapter XIX-2.page no.374-375 487.',
    category: 'God',
  },
  {
    id: '12',
    text: 'Things which are impossible to achieve without the help of God become easily possible by His Grace... The infusion of God in the mind of man leads to all the supersensuous experiences to which the world is entirely blind.',
    reference: 'P.G.H.L.page no.200,202/236.239',
    category: 'God',
  },
  {
    id: '13',
    text: "It is God's great omnipotence which has made a blind man see things, which are not accessible to the vision of ordinary men.",
    reference: 'P.G.H.L.page no.128 162.',
    category: 'God',
  },
  {
    id: '14',
    text: 'God knows how to maintain His friendship, and we should only seek after His affection. The friendship of God is unbreakable, and the love of God is undiminished........ Hence we should be friends of God, and communicate to Him our inner most desires.',
    reference: 'M.M.chapter XIX-52.page no.406/529',
    category: 'God',
  },
  {
    id: '15',
    text: 'God does ward off all evil from His Saints. He comes to their rescue all of a sudden. He seems to be nowhere, and yet comes all at once. He reserves happiness for His devotees, and takes for Himself their lot of sorrow.',
    reference: 'M.M.chapter XVI-70 page no.334/437',
    category: 'God',
  },
  {
    id: '16',
    text: 'God has ever been a protective adamant to those who have submitted themselves to His will. God will justify the devotee. God will save the sinful. God will come to the help of those who have no protector......God will succour men from all calamities, and will run to their help.',
    reference: 'M.M.chapter XIX-52.Page no.406/529',
    category: 'God',
  },
  {
    id: '17',
    text: 'When we recognize that God is the real doer in the world, Egoism cannot possess us...... God is the only reality, the self is an illusion.',
    reference: 'M.M.chapter XIX-44.Page no.400/522',
    category: 'God',
  },
  {
    id: '18',
    text: 'God may be described as मायावी, मायी, मायावान् or मायापरिवृत. But He certainly lives in a camouflage and does not allow Himself to be seen. Let us try to penetrate the camouflage. In that way we may be able to reach at least the outskirts of some concrete reality.',
    reference: 'B.G.P.G.R. page no.242/215',
    category: 'God',
  },
  {
    id: '19',
    text: 'Not merely all objects of excellence, call them विभूतिमत्, श्रीमत् or ऊर्जित, have sprung from a portion of God; but God has remained infinitely outside, an absolutely transcendent Being. God cannot be seen, God cannot be expressed by word of mouth and God cannot be heard. God is the greatest wonder of all existence.',
    reference: 'B.G.P.G.R. page no.244-245/216',
    category: 'God',
  },
  {
    id: '20',
    text: 'God stands outside the world but descends inside as an Avatara. From a transcendent being, He becomes immanent in the world. This is the doctrine of Transcendo-Immanence.',
    reference: 'B.G.P.G.R. page no.186/165.',
    category: 'God',
  },
  {
    id: '21',
    text: 'God does not live in the heaven or in the heart of the Yogins, but only where the devotees sing His praise.',
    reference: 'M.M.chapter XIX-37.page no.396 515',
    category: 'God',
  },
  {
    id: '22',
    text: 'God is a great artificer, he is a juggler, he hides his art and the powers of his art. It is for that reason, that the spiritual life goes underground from time to time. The river of spiritual experience hides itself like the Phalgu.',
    reference: 'B.G.P., R. page no. 217 218-211',
    category: 'God',
  },
  {
    id: '23',
    text: 'God is the protector of all beings, and of all worlds...... Where God is not, nothing can be, and all the beings on earth would be as good as ghosts. Where God is not, one would meet with Death. Without God, there can be no life...... Hence it is, that one should always meditate on God.',
    reference: 'M.M.chapter XIX-44.page no.400/521',
    category: 'God',
  },
  {
    id: '24',
    text: 'The whole of biology is an illustration of the working of God, just as the whole of physics also is. Science is the demonstration of the power of God.',
    reference: 'P.G.K.L. page no.41.',
    category: 'God',
  },
  {
    id: '25',
    text: 'Man may make his own effort, and yet it remains with God to crown that effort with success by His Grace.',
    reference: 'P.G.H.L.page no. 120/154.',
    category: 'God',
  },
  {
    id: '26',
    text: 'The form of God is near us and inside us, and yet we are unable to see God in our entire life. His form lies pervading the entire universe, but the vision of the seer is warped, and he is not able to see it.',
    reference: 'P.G.H.L. page no.369/407',
    category: 'God',
  },
  {
    id: '27',
    text: 'We should meditate on God, for God holds on the keys of success in His hands... Where God is not present to support us, we would be routed by anybody whatsoever... No undertaking can succeed unless it is backed up by the presence of God.',
    reference: 'M.M.chapter XIX-44.page no.400/521-522',
    category: 'God',
  },
  {
    id: '28',
    text: "Let it be remembered once for all that without God's grace a true Spiritual Teacher can never be found. In a sense, it might be said that the Guru and God are one. And secondly, God confers His grace only upon those that have been favoured by Saints.",
    reference: 'M.M.chapter XII-49.page no.253/331',
    category: 'God',
  },
  {
    id: '29',
    text: 'God Himself serves him who regards his spiritual teacher as identical with God.',
    reference: 'M.M.chapter XI-3.page no.220/287',
    category: 'God',
  },
  {
    id: '30',
    text: 'You cannot set a limit to the number of forms through which God might reveal Himself.',
    reference: 'P.G.K.L.page no.93.',
    category: 'God',
  },
  {
    id: '31',
    text: 'There is no use milking a she-goat when we have a wish-cow; similarly, why should we dissipate our energies for nothing? Let us concentrate our mind on the one omnipotent God, who is capable of taking away all our evils under all circumstances.',
    reference: 'P.G.H.L.page no.127/161.',
    category: 'God',
  },
  {
    id: '32',
    text: 'The true God, is not made of gold, or silver, or brass, or copper. The true God is not a painting drawn on a wall. The true God is not the different kinds of stones found in rivers, or the moon-stone or the sun-stone. The true God is not copper pieces or gold pieces worshipped at home...... The true God is indeed the Seer. He is One. From Him the many have sprung.',
    reference: 'M.M.chapter XIX-12.page no.381/496',
    category: 'God',
  },
  {
    id: '33',
    text: 'The greatness of God is so infinite that God cannot be known in His entirety.',
    reference: 'M.M.chapter III-24.page no.65/83',
    category: 'God',
  },
  {
    id: '34',
    text: 'There are many persons who pride themselves upon their intellectual knowledge. But they cannot hope to know God. God is not within the purview of mere knowledge. Also people pride themselves upon being great in this world; but they are nothing before the greatness of God. God has far more knowledge than all the knowers have, and is far greater than those who claim to be great.',
    reference: 'P.G.K.L.page no.167.',
    category: 'God',
  },
  {
    id: '35',
    text: 'God has to take on incarnation and the devotee engages himself in worldly life. The devotee derives happiness by God and God derives happiness in the company of the devotee. God gives the saint, a form and a name and the saint increases his glory. One should surely rest in the belief that the saint is God and God the saint.',
    reference: 'M.M.chapter XVI-75.page no.341/446.',
    category: 'God',
  },
  {
    id: '36',
    text: 'God always sides with his devotees because of their overflowing devotion and complete self-surrender to Him.',
    reference: 'P.G.K.L.page no.318.',
    category: 'God',
  },
  {
    id: '37',
    text: 'The devotee sings the praises of God in a sleeping posture, God listens to them in a sitting posture; if he praises God in a sitting posture, God stands up to listen to it and if the devotee prays in a standing posture, God listens to him in a pleased and nodding pose; and if the devotee praises God while nodding himself, He throws open the doors of heaven, makes him the master of heavens and allows him to plunder its treasures.',
    reference: 'P.G.K.L.page no.271.',
    category: 'God',
  },
  {
    id: '38',
    text: 'God is required to provide for His creation, the Devotee has no anxiety even to provide for himself. God has to take into account the merits and sins of people; to the Devotee all are equally good. God has to create and to destroy the world; the Devotee is not called upon to undertake that onerous duty. God is always engaged in His work; the Devotee enjoys the satisfaction of not doing anything at all. Does not all this prove that the Devotee is superior to God?',
    reference: 'M.M.chapter XVI-76.page no.342/447.',
    category: 'God',
  },
  {
    id: '39',
    text: 'God is not like other masters. His reward precedes service, as in the case of other masters it follows. This indicates the fore-fulfilment of the desires of the saint by God. Before any desire arises in the mind of the saint, it is already fulfilled by God.',
    reference: 'P.G.H.L.page no.325/361.',
    category: 'God',
  },
  {
    id: '40',
    text: 'It is God who by means of His motion gives a push to the sun and moon as well as keeps the canopy eternally hanging over our heads. So God is everywhere. God is omnipotent. Let us submit ourselves to God. When our mind has merged itself in God, then alone shall we be free from all sorts of anxieties; because everything that happens to us does so by the will and direction of God.',
    reference: 'P.G.K.L.page no.42.',
    category: 'God',
  },
  {
    id: '41',
    text: 'When we look at nature, we see that the Order which governs it is nothing else except the Will of God. Also if we look at the matter even physiologically, we see that our exhalations and inhalations are themselves due to the Order of God, and when God desires that we should have final exhalation, we do finally exhale and there is no further inhalation. Death is thus itself due to the Will and Order of God.',
    reference: 'B.G.P.G.R. page no.60/54-55.',
    category: 'God',
  },
  {
    id: '42',
    text: 'God is really not different from the world. Originally from a single seed grows the sprout, from the sprout the stem, from the stem the many branches, and from the branches the leaves; after the leaves comes the flower, and from the flower the fruit; and yet when we consider it all, it is only the seed unfolded. In this manner is God identical with the whole world. From God this world is spread; from the ant to the highest god, there is no being who is without God. He alone who awakes to this consciousness escapes the dream of difference.',
    reference: 'M.M.chapter III-23.page no.64/82-83.',
    category: 'God',
  },
  {
    id: '43',
    text: 'God so fills every nook and cranny of the world that every object must succumb before His infinite omnipotence. When God chooses to show His prowess, the whole world is put in consternation, and with it also the whole host of the gods.',
    reference: 'M.M.chapter III-22.page no.64/82.',
    category: 'God',
  },
  {
    id: '44',
    text: 'If God encompasses the world from the point of view of space, the devotee encompasses God from the point of view of love and devotion. So God is altogether caught up in the love of His devotee',
    reference: 'P.G.K.I. page no. 141.',
    category: 'God',
  },
  {
    id: '45',
    text: "God's power pervades all the natural forces. Also we will not be far wrong if we say that God is the sum-total of all the forces of nature.",
    reference: 'B.G.P.G.R. page no.60/54.',
    category: 'God',
  },
  {
    id: '46',
    text: 'God is indeed the body, of whom the Devotee is the soul. It is a matter of shame to God that His devotee should look piteous in the eyes of men. God regards His life as useless, if the words of the devotee come untrue.',
    reference: 'M.M.chapter XI-6.page no.225 293.',
    category: 'God',
  },
  {
    id: '47',
    text: "We are told how Krishna was at the same time Vasudeva, Bhagavan and Vishnu, Vasudeva implying that God was Omnipresent, Bhagavan that God was omnipotent, and Vishnu that God was omnilustrous. Presence, power and lustre, therefore, constitute the essence of God's being.",
    reference: 'B.G.P.G.R. page no.102/91-92.',
    category: 'God',
  },
  {
    id: '48',
    text: "When God has taken secure lodgment inside a man's heart, whatever he does is indeed the worship of God... What words come out of an intense devotion in such a man's heart may alone be regarded as words of true inspiration.",
    reference: 'M.M. chapter xix- 402/524.',
    category: 'God',
  },
  {
    id: '49',
    text: 'God knows the inner feelings of men. If a man tries to cheat God, God will first cheat him. God behaves with men only as they deserve. He gives satisfaction to His devotees only according to the quality of their devotion. But as soon as there is any deficit in their sentiment, He also moves away.',
    reference: 'м.M.chapter XIX-61.page no.410-411/536',
    category: 'God',
  },
  {
    id: '50',
    text: 'God is filled with happiness at the singing of His praise. As we sit down and sing the praise of God, God stands before us. As in devotion we stand up and call on the name of God, God dances before us. God indeed loves his Kirtana so much that He forthwith comes to the succour of His devotees in the midst of difficulties.',
    reference: 'M.M.chapter VIII-5.page no.200/262-263.',
    category: 'God',
  },
  {
    id: '51',
    text: 'We may love God not only because He may crown us with success in our undertakings but because He is Himself worthy of our highest love.',
    reference: 'M.M.chapter XIX- 45.page no.400/522',
    category: 'God',
  },
  {
    id: '52',
    text: 'God leaves his own abode and comes where his glory is sung to protect his devotees from all difficulties.',
    reference: 'E.B.V. page no59',
    category: 'God',
  },
  {
    id: '53',
    text: 'He who is befriended by God, becomes an object of favour for the whole world. God sees that such a devotee lacks nothing, and He takes on Himself the duty of protecting him in calamities. He does not stay away from His devotee even for a single moment, and on critical occasions, invariably lends His helping hand.',
    reference: 'M.M.chapter VIII-11.page no.207 271.',
    category: 'God',
  },
  {
    id: '54',
    text: 'We in this world are novices, making our own moves. But if we pray to God, it rests with Him in His benevolent omnipotence to make such a move as to destroy our moves in their badness, and lead them on to good.',
    reference: 'P.G.H.I. page no.121.155.',
    category: 'God',
  },
  {
    id: '55',
    text: 'Whatever man may do, God has the power either to extend its goodness or destroy its badness.',
    reference: 'P.G.H.L.page no.120/154.',
    category: 'God',
  },
];