export const mysticism = [
  {
    id: '1',
    text: "Mysticism is derived from the Greek word 'mustein' which means to shut one's lips. So mysticism is a philosophy or realisation and enjoyment of God in silence.",
    reference: ' S.A.G.I.S.page no.141.',
    category: 'Mysticism',
  },
  {
    id: '2',
    text: 'Mysticism denotes that attitude of mind which involves a direct, immediate, first-hand, intuitive apprehension of God. When Mysticism is understood in this sense, there is no reason why it should be taken to signify any occult or mysterious phenomena as is occasionally done. It is an irony of fate that a word which deserves to signify the highest attitude of which man is capable, namely, a restful and loving contemplation of God, should be taken to signify things which are incomparably low in the scale of being. Mysticism implies a silent enjoyment of God. It is in this sense that mystical experience has often been regarded as ineffable.',
    reference: ' M.M. preface page no. I/vii',
    category: 'Mysticism',
  },
  {
    id: '3',
    text: 'Mysticism denotes that attitude of mind which involves a direct, immediate, intuitive apprehension of God. It signifies the highest attitude of which man is capable, namely, a beatific contemplation of God, and its dissemination in the Society and the World.',
    reference: ' P.G.H.L.preface page no.2/6.',
    category: 'Mysticism',
  },
  {
    id: '4',
    text: 'Mysticism, which being the practical side of philosophy can alone give satisfaction to those who care for philosophy as a way of life.',
    reference: ' M.M.chapter 1-1.page no.1/1',
    category: 'Mysticism',
  },
  {
    id: '5',
    text: 'The Bhagavadgita is one of the greatest works on mysticism that the world has ever seen',
    reference: ' B.G.P.G.R.page no.137.',
    category: 'Mysticism',
  },
  {
    id: '6',
    text: 'God-realisation constitutes the Apurvata, the novelty or the supreme contribution of the Bhagavadgita.',
    reference: ' B.G.P.G.R.page no.137.',
    category: 'Mysticism',
  },
  {
    id: '7',
    text: 'Mysticism is a way of spiritual life which binds all humanity together. It is not enough for us merely to know what the different philosophers and the Christians, the Muslims, the Jains, the Buddhists, the Vaisnavites or the Lingayats propound for the attainment of God: it is necessary to analyse what lies behind these philosophies and these religions. We can then discern that essentially the same kind of spiritual teaching pervades them all.',
    reference: ' P.G.K.L.page no.1.',
    category: 'Mysticism',
  },
  {
    id: '8',
    text: 'Mysticism is the philosophy of God-realisation, which implies and involves the faculty of intuition.',
    reference: ' P.G.K.L.page no.2.',
    category: 'Mysticism',
  },
  {
    id: '9',
    text: 'Intuition is a faculty of supersensuous experience which is aroused in us by proper spiritual initiation and practice.',
    reference: ' P.G.K.L.page no.3.',
    category: 'Mysticism',
  },
  {
    id: '10',
    text: 'Mysticism transcends philosophy, and cares only for the intuitive apprehension of God.',
    reference: ' P.G.H.L.page no. 98/132.',
    category: 'Mysticism',
  },
  {
    id: '11',
    text: 'Intuition would not deny to Mysticism a title to Philosophy if intellect requires it. As it connotes a determinative effort towards the acquisition of Reality, it implies a definite, prolonged, and continuous exercise of the will.',
    reference: ' P.G.H.L.preface page no.2/7.',
    category: 'Mysticism',
  },
  {
    id: '12',
    text: 'A Philosophy of Mysticism might concern itself neither with the Personal nor with the Impersonal, but with the Transpersonal, meaning thereby that the category of personality has no place in a Philosophy of Mysticism.',
    reference: ' M.M. chapter 11-2. page no. 423 552',
    category: 'Mysticism',
  },
  {
    id: '13',
    text: 'Morality and mysticism are very intimately related. In fact they are interdependent. Morality leads to and supports mysticism, while mysticism brings about perfection in morality.',
    reference: ' Glimpses page no.112',
    category: 'Mysticism',
  },
  {
    id: '14',
    text: 'Just as there can be no true mysticism unless it is based upon the sure foundation of morality, so morality to be perfect must end in the mystical attitude.',
    reference: ' C.S.U.P.page no.230/315',
    category: 'Mysticism',
  },
  {
    id: '15',
    text: 'A true life of Mysticism teaches a full fledged morality in the individual, and a life of absolute good to the society.',
    reference: ' E.M.O.T. раде по.40.',
    category: 'Mysticism',
  },
  {
    id: '16',
    text: 'The surest criterion of mysticism is the reality of the experience as enjoyed by the mystic himself. It is known only to him and to his Maker.... It is in this sense that mystical experience has been regarded as ineffable.',
    reference: ' P.G.H.L.preface page no.2/6.',
    category: 'Mysticism',
  },
  {
    id: '17',
    text: 'Metaphysics, morality and mysticism are as inseparable from each other in the interest of the highest spiritual development of man, as intellect, will and emotion are inseparable for his highest psychological development.',
    reference: ' C.S.U.P. page no. 211.',
    category: 'Mysticism',
  },
  {
    id: '18',
    text: 'Intelligence without the moral backbone might only degenerate into the cleverest forms of chicanery, and a mystic without morality, if such a one were possible, might only be a hideous creature who is a blot on the spiritual evolution of man.',
    reference: ' C.S.U.P. page no.287.',
    category: 'Mysticism',
  },
  {
    id: '19',
    text: "Unless we have the vision of God, we won't attain the powers and virtues. On the other hand, the possession of these powers and virtues will facilitate spiritual realisation. Thus ethics and mysticism are inter-dependent.",
    reference: ' Glimpses page no. 147',
    category: 'Mysticism',
  },
  {
    id: '20',
    text: 'It is said by a great philosopher that it is much better to be a Socrates dissatisfied than a fool satisfied. We might extend this argument and say that it is much better to be a mystic dissatisfied than a Socrates satisfied! So this satisfaction of the mystic is what is called beatification, bliss or ecstasy.',
    reference: ' P.G.K.L..page no.5.',
    category: 'Mysticism',
  },
  {
    id: '21',
    text: 'To the extent to which a philosopher might be regarded as being above one, who is materially satisfied, to that extent a mystic might be regarded as being above a philosopher. Such a mystic, when he is also a spiritual teacher, raises his devotees to the plane of liberation.',
    reference: ' P.G.K.L.page no.81.',
    category: 'Mysticism',
  },
  {
    id: '22',
    text: 'The real end of bodily existence should be God-vision.',
    reference: ' M.M.chapter xix-24 page no 388/505',
    category: 'Mysticism',
  },
  {
    id: '23',
    text: 'In this mortal fair the only profit that we should seek is God. Mortal things remain in this world and nobody can take them away for a future existence. Hence we should grow indifferent to all things and give ourselves up to contemplation, by which the infinite profit of God will be attained.',
    reference: 'M.M.chapter-xix-23.page no.387/504',
    category: 'Mysticism',
  },
  {
    id: '24',
    text: "If all men are equal before God, and if men have got the same 'Deiform faculty', which enables them to 'see God face to face', then there is no meaning in saying that there is a difference between the quality of God-realisation in some, as contrasted with the quality of God-realisation in others. It is true that there may be physical, mental and temperamental differences, but there is no difference in the quality of their mystical or intuitive realisation.",
    reference: ' M.M.preface page no.25/xxxii-xxxiii',
    category: 'Mysticism',
  },
  {
    id: '25',
    text: 'To realise God for oneself and for others is and should be the end of human life.',
    reference: ' चरित्र आणि तत्त्वज्ञान - पा. क्र.१२२.',
    category: 'Mysticism',
  },
  {
    id: '26',
    text: 'According to the law of Spiritual Gravitation, the experience of a worthy Spiritual Teacher must automatically descend to his disciples. As water at a higher level must descend to a lower level, so the experience of a spiritual teacher must descend automatically to those who are walking on the path which he has trodden.',
    reference: ' P.G.H.L. page no.142/176',
    category: 'Mysticism',
  },
  {
    id: '27',
    text: 'It is only the mystical view of Reality that will come as a reconciling factor between the different attitudes and different doctrines about God, the world and the self.',
    reference: ' B.G.P.G.R.page no.186/165.',
    category: 'Mysticism',
  },
  {
    id: '28',
    text: 'Mystical view of Reality alone will enable us to reconcile all the intellectual dogmas that have infested the philosophies of the world.',
    reference: ' B.G.P.G.R.page no.191.169.',
    category: 'Mysticism',
  },
  {
    id: '29',
    text: 'It should be noted that philosophy is a fence that does not allow the stray cattle of superstition to enter into the garden of mysticism.',
    reference: ' Glimpses page no. 108.',
    category: 'Mysticism',
  },
  {
    id: '30',
    text: 'The spiritual aspirant gains the ripe fruit of self-realisation only when he implicitly acts according to the orders of his spiritual teacher.',
    reference: ' M.M. chapter VIII-6. page no.202/264',
    category: 'Mysticism',
  },
  {
    id: '31',
    text: "What is the relationship between these two forms of expression, Soham and Tattvamasi? You will see that Tattvamasi is in the third person and Soham is in the first person. 'I am Reality' is one thing, and 'Thou art That' is another. Ultimately you will see that Soham would stand on a higher level than Tattvamasi, because it brings you directly and personally into relation with Reality, though ultimately the meaning is the same viz., the unity of subject and object.",
    reference: 'P.G.K.L.page no.222.',
    category: 'Mysticism',
  },
  {
    id: '32',
    text: 'We should empty the heart of its contents, and then will God live in it. No other remedy is required to see God. We should nip all our desires in the bud. Where desires end, God comes to inhabit.',
    reference: ' M.M. chapter XVI-51. Page no.316/413',
    category: 'Mysticism',
  },
  {
    id: '33',
    text: 'As a matter of fact, God so fills every nook and cranny of the world that every object must succumb before His infinite omnipotence.',
    reference: ' M.M. chapter 111-22. page no.64/82',
    category: 'Mysticism',
  },
  {
    id: '34',
    text: 'In a true life of mysticism emotions must be transmuted into an intellectual love of God.',
    reference: ' P.G.H.L.Preface page no. 6',
    category: 'Mysticism',
  },
  {
    id: '35',
    text: 'The mystics teach that a rising devotee must ultimately feel his identity with his own Self.',
    reference: ' B.G.P.G.R. page no. 69/63',
    category: 'Mysticism',
  },
  {
    id: '36',
    text: 'Spiritual life must be sought for and cultivated as an end in itself and never as a means to achieve other ends. Then alone we would attain our cherished goal, viz. God-realisation; otherwise not.',
    reference: ' Glimpses 145.',
    category: 'Mysticism',
  },
  {
    id: '37',
    text: "Firm devotion, earnest meditation and service of saints constitute what is termed 'My work i.e.divine work'. This is the path of God- realisation.",
    reference: ' Glimpses 115',
    category: 'Mysticism',
  },
  {
    id: '38',
    text: 'After having walked on the pathway for a long time, and through travails and turmoils of body and mind, of nature and society, devotees can envisage to themselves certain landmarks, certain lamp-posts, which will help them to walk with courage and confidence on the pathway to God, and attain to the highest ideal they have been seeking.',
    reference: ' P.G.H.L.page no.1-2/34-35.',
    category: 'Mysticism',
  },
  {
    id: '39',
    text: 'If you want to unravel the mystery of being, you have to go beyond the limitations of your experience of this world.',
    reference: ' P.G.K.L.page no.171.',
    category: 'Mysticism',
  },
  {
    id: '40',
    text: 'We must not, however, fail to note that Bhava or Bhakti, an unexplained and inexplicable love of God, is a fundamental requirement of spiritual life; meditation from hour to hour and day to day and even concentration on the name of God are of secondary importance.',
    reference: ' B.G.P.G.R. page no.254/226.',
    category: 'Mysticism',
  },
  {
    id: '41',
    text: 'We must have control over our breaths, we must meditate upon God, we must belong to the spiritual tradition and we must have the grace of Antaryamin. It is only then that we can realise God.',
    reference: 'P.G.K.L. page no.231.',
    category: 'Mysticism',
  },
  {
    id: '42',
    text: 'Our bliss is with ourselves; it does not lie in any external object. If we possess merely discrimination and dispassion, the way is open for us to know God.',
    reference: ' м.м. chapter VIII-7. page no.202/265',
    category: 'Mysticism',
  },
  {
    id: '43',
    text: 'Unless we take leave of all egoism, God shall not come to our hands.',
    reference: ' M.M. chapter VIII-11. Page no.205/269',
    category: 'Mysticism',
  },
  {
    id: '44',
    text: 'To know the Reality, the uprooting of the three main desires namely progeny, prosperity and popularity essential.',
    reference: ' E.B.V. page no.42.',
    category: 'Mysticism',
  },
  {
    id: '45',
    text: 'What is the use of coming into this world if we are not able to visualize God? In this mortal fair, our only profit should be God. Everything, in other words, except the pursuit of God is a vanity.',
    reference: ' P.G.K.L.page no.10.',
    category: 'Mysticism',
  },
  {
    id: '46',
    text: 'The study of philosophy for oneself and for others (आतमविद्या) becomes a cardinal requisite for the determination of the nature of God, and consequently for our attachment to Him.',
    reference: 'P.G.H.L.page no.96.',
    category: 'Mysticism',
  },
  {
    id: '47',
    text: 'A man whose brain is confused, a man who is labouring under delusions, a man who is likely to suffer from hallucinations, a man who is neurally pathological, can never hope to attain to real mystical experience.',
    reference: ' M.M. preface page no.25/xxxiii',
    category: 'Mysticism',
  },
  {
    id: '48',
    text: 'According to the mystics the relation of Self and God may be likened to the relation between an image and its prototype, but is never fully represented by it. The union is so close as to defy all expression; but if any analogy is to be found, it may be found in the infinite reflections of one mirror in another when placed over against it, and of this again into the first, anticipating closely a famous phenomenon in Optics.',
    reference: ' M.M. preface page no.7/xiv',
    category: 'Mysticism',
  },
  {
    id: '49',
    text: "The true method of worship by which God can be propitiated is to bathe him with honour, to anoint him with love, to place flowers of sweet and humble words on his forehead, and to make him a continuous oblation of one's self.",
    reference: ' P.G.H.L.page no.210/247.',
    category: 'Mysticism',
  },
  {
    id: '50',
    text: 'The self is interested in seeing other objects; but it is not so much interested in seeing itself which it ought to. When it becomes interested in seeing itself, it becomes self-conscious and then only one reaches Reality.',
    reference: ' P.G.K.L.page.no.226.',
    category: 'Mysticism',
  },
  {
    id: '51',
    text: 'The Yogin might be expert in performing any Asanas he pleases, or in exhibiting any Mudras he likes. He may reduce his body to a mere skeleton by famishing himself, or he might besmear his body all over with ashes, wet or dry. He might make the Kundalini enter the Brahma Randhra and yet he may not attain to any mystical experience.',
    reference: ' P.G.H.L.page no.169/204',
    category: 'Mysticism',
  },
  {
    id: '52',
    text: 'The Yogin may come in possession of miraculous powers by means of his Yoga. He might at pleasure extract his Soul from his body, and make it enter into any desired body he pleases. The Yogin might disappear at the place where he is seen, and may re-appear at distant places like Gokul, Mathura, and Kashi. He may be able to walk on the surface of the waters, and whatever he might speak by word of mouth may come out true; and yet a mere possession of such miraculous powers may not enable him to attain mystical experience.',
    reference: ' P.G.H.L.page no.170/204',
    category: 'Mysticism',
  },
  {
    id: '53',
    text: 'We suppose that the objectivity and necessity conferred by mystical experience is of a higher order than that of any other kind of human experience just because it is "deiform". It is this element of divinity in it that makes it so supremely compelling and valid.',
    reference: ' M.M. preface page no.25',
    category: 'Mysticism',
  },
  {
    id: '54',
    text: 'The attainment of high intellectual powers may not also demarcate a man as a mystic nor will a mere possession of high moral qualities help him much. Until a man is able to see his own Form by the Grace of his spiritual teacher, he may not be regarded as having attained to the highest mystical experience.',
    reference: ' P.G.H.L.page no.170/204-205',
    category: 'Mysticism',
  },
  {
    id: '55',
    text: 'When it is said that the Self is to be realised, we are asked to take into account the whole ethical and mystical process by which the allurements of the not-Self naturally ingrained in the human being are to be gradually weaned out, and the Self to be made to stand in its native purity and grandeur.',
    reference: 'C.S.U.P. page no.302.',
    category: 'Mysticism',
  },
  {
    id: '56',
    text: 'It is only when a perfect catharsis of the whole moral being takes place by the clearness of illumination, that one is able to realise the immaculate God after meditation; for He can be attained neither by sight, nor by word of mouth, nor by any other sense, nor by penance, nor by any actions whatsoever.',
    reference: ' C.S.U.P. page no 249-250/341.',
    category: 'Mysticism',
  },
  {
    id: '57',
    text: "It is only when one loses one's bodily consciousness that one attains to the state of self-realisation and visualises his own self:",
    reference: 'P.G.K.I..page no.256.',
    category: 'Mysticism',
  },
  {
    id: '58',
    text: 'When our heart is purified, we see God. Mere meditation will not necessarily lead to the vision of God. Spiritual experience depends upon the purity and intensity of our heart.',
    reference: ' Glimpses page no.133-134.',
    category: 'Mysticism',
  },
  {
    id: '59',
    text: 'For the realisation of the Self, one should lead a life of introversion, with an utter disgust for the world and catharsis from sins, a spirit of humbleness, and a life of tranquility, truth, penance, insight, strength, and right pursuit. Unless these conditions are fulfilled, the aspirant after spiritual life may never hope to realise the Self.',
    reference: ' C.S.U.P.page no.221/329.',
    category: 'Mysticism',
  },
  {
    id: '60',
    text: 'This Atman who is hidden in all beings is not patent to the eyes of all. It is only the subtle seers who can look with the one-pointed and piercing faculty of Intuition (Buddhi) that are able to realise God',
    reference: ' C.S.U.P. page no 340.',
    category: 'Mysticism',
  },
  {
    id: '61',
    text: 'Mystic experience is a sealed book to many, for verily they do not know the secret of the company of the Good.',
    reference: ' M.M. chapter XIX-62 page no. 411.536',
    category: 'Mysticism',
  },
  {
    id: '62',
    text: 'The mystic way is not like other ways. These only promise and never fulfil. The mystic way points out the inner secret of the revealed scriptures... Only the Sages can know the secret path in the heavens which leads to God.',
    reference: ' M.M. chapter XIX-62. page no. 411/536',
    category: 'Mysticism',
  },
   {
    id: '63',
    text: 'We must have control over our breaths, we must meditate upon God, we must belong to the spiritual tradition and we must have the grace of Antaryamin. It is only then that we can realise God.',
    reference: ' P.G.K.L.page.no.231.',
    category: 'Mysticism',
  },
  {
    id: '64',
    text: 'When we try to realise God. He cannot be realised. When we try to leave Him away. He cannot be left. We are connected with God forever, and the connection is unbreakable.',
    reference: ' M.M. chapter XIX-60.page no. 410/535',
    category: 'Mysticism',
  },
  {
    id: '65',
    text: "Nature of God realisation is like that of a 'fact'. You can never question it. You can never argue about it. You can never think about it. If you only know that God is, then alone is God realised by you.",
    reference: ' C.S.U.P. page no 340.',
    category: 'Mysticism',
  },
  {
    id: '66',
    text: 'God always is, and when we begin to see Him, He moves away from us. But when we do not look at Him, He immediately appears before us. The means for His attainment are only the means for His disappearance, and the means for His disappearance are really the means for His attainment. Only that man can know the meaning of this, who has attained to spiritual experience himself.',
    reference: ' M.M. chapter XIX-60. page no. 410/535',
    category: 'Mysticism',
  },
  {
    id: '67',
    text: 'The so-called Samadhi is a mere mental attunement with God. Our beatific experience is far beyond that state; there you merge in God entirely. In that state, the Sadhaka becomes one with God. There is assimilation at that time.',
    reference: ' Glimpses page no.130',
    category: 'Mysticism',
  },
  {
    id: '68',
    text: 'Before spiritual experience, everything that comes within the ken of the five elements appears as false and mean.',
    reference: ' M.M.chapter XIX-62. page no. 411 536-537',
    category: 'Mysticism',
  },
  {
    id: '69',
    text: 'When spiritual experience gets secure lodgment in us, our doubts will be dispelled to the confines of the universe, and the visible world will cease to exist.',
    reference: ' M.M.chapter XIX-62. page no. 411 536-537',
    category: 'Mysticism',
  },
  {
    id: '70',
    text: 'It is impossible accurately to describe the worth of spiritual experience. By this experience the greatest sages have attained to inmost satisfaction.',
    reference: ' M.M.chapter XIX-62. page no. 411/536-537',
    category: 'Mysticism',
  },
  {
    id: '71',
    text: 'He who attains spiritual experience can save other beings. He is a King of the spiritual world. He who has it not is a beggar.',
    reference: ' M.M.chapter XIX-62. page no. 411/536-537',
    category: 'Mysticism',
  },
  {
    id: '72',
    text: 'The spiritual experience can be obtained only on the strength of the merit during the whole course of our lives, and then shall the supreme God reveal Himself to us.',
    reference: ' M.M.chapter XIX-62. page no. 411/536-537',
    category: 'Mysticism',
  },
  {
    id: '73',
    text: 'You cannot set a limit to the number of forms through which God might reveal Himself.',
    reference: ' P.G.K.L.page no.93.',
    category: 'Mysticism',
  },
  {
    id: '74',
    text: 'There is no fixed sequence in spiritual experiences. Every Sadhaka has his own peculiar order of having these experiences. Spiritual evolution is multilinear. A seeker may get these experiences all at once. Hence the question of sequence in them becomes absolutely irrelevant.',
    reference: ' Glimpses page no. 124-125.',
    category: 'Mysticism',
  },
  {
    id: '75',
    text: 'Mystic experience has shown that it is not merely by shutting our ears that we are able to hear the mystic sound, that we can hear it even with our ears quite open, and that finally even a deaf man who cannot hear anything else is yet able to hear this sound.',
    reference: ' C.S.U.P. page no.344',
    category: 'Mysticism',
  },
  {
    id: '76',
    text: 'You must be able by a sort of supersensuous experience to visualise the form of God. It is seeing without eyes and hearing without ears. It is only when you are able to have such an experience inside yourself that you are able to attain to His real Form as well as His real celestial Name.',
    reference: ' P.G.K.L.page no.191.',
    category: 'Mysticism',
  },
  {
    id: '77',
    text: 'The way of God\'s love is the way of fire. He who throws himself into it will be saved, and he who will merely look on and keep aside will be burnt to death. It is the active part in this meditation which will enable us to get out of difficulties and perils.',
    reference: ' P.G.H.L.page no.229/266.',
    category: 'Mysticism',
  },
  {
    id: '78',
    text: 'Great and lustrous is that incontemplatable Being, and yet he is subtler than the subtle. He is farther than any far-off end, and yet quite near to us, being shut up in the cave of our heart.',
    reference: ' C.S.U.P. page no.346',
    category: 'Mysticism',
  },
  {
    id: '79',
    text: 'Atman is neither male nor female, that He moves and yet does not move, that He is both far and near, that He is greater than the great and smaller than the small, or that He is of the size of a thumb, only the mystics can know.',
    reference: ' C.S.U.P. page no.347',
    category: 'Mysticism',
  },
  {
    id: '80',
    text: 'We should steadily perform our Sadhana and get spiritual experiences ourselves. We should accept that form of God to be real of which we have got an actual vision.',
    reference: ' Glimpses page no.141.',
    category: 'Mysticism',
  },
  {
    id: '81',
    text: 'We should enkindle the divine lamp within us. Then His light would automatically radiate in all directions. If the flower blooms, its fragrance would spread far and wide of its own accord.',
    reference: ' Glimpses page no.141.',
    category: 'Mysticism',
  },
  {
    id: '82',
    text: 'God is blissful. Spiritual life begins with the experience of at least an iota of that bliss.',
    reference: ' Glimpses page no.141.',
    category: 'Mysticism',
  },
  {
    id: '83',
    text: "We may note that super-sensuousness, intuition and central initiation are merely different ways of speaking about the same matter. Super-sensuousness is what corresponds to transcendence of senses. Intuition refers to the faculty by which we get that spiritual experience. 'Central initiation' is a peculiar expression. In the physiological sphere it is opposed to what we may call peripheral.",
    reference: 'B.G.P.G.R.page no.232/206.',
    category: 'Mysticism',
  },
  {
    id: '84',
    text: 'It is not anything impinging upon our senses from the outside that constitutes beatific experience; it is something which comes from inside.',
    reference: ' B.G.P.G.R.page no.232/207.',
    category: 'Mysticism',
  },
  {
    id: '85',
    text: 'Intuition, supersensuous experience and central initiation are involved in the evolution of mystical experience.',
    reference: ' P.G.K.L.page no.3.',
    category: 'Mysticism',
  },
  {
    id: '86',
    text: 'Supersensuousness, intuition and central initiation as opposed to peripheral initiation is what constitutes the first criterion of mystical experience.',
    reference: 'B.G.P.G.R.page no.232/207.',
    category: 'Mysticism',
  },
  {
    id: '87',
    text: 'Things which are impossible to achieve without the help of God become easily possible by His Grace... The infusion of God in the mind of man leads to all the supersensuous experiences to which the world is entirely blind.',
    reference: 'P.G.H.L.page no.200,202/236,239',
    category: 'Mysticism',
  },
  {
    id: '88',
    text: 'In fact, no mystical experience is possible unless we have a plenitude of finer emotions, all turned to the experience of God. A mystical life so far from being unemotional, is, we must say, supremely emotional; only the emotions ought to be exercised and kept under control by intellect.',
    reference: ' M.M. preface page no.26/xxxiv.',
    category: 'Mysticism',
  },
  {
    id: '89',
    text: 'Unless we are morally pure, we cannot make any progress in our spiritual life and realise God. And unless we realise God, we cannot be perfect in our moral life.',
    reference: ' Glimpses page no.112.',
    category: 'Mysticism',
  },
  {
    id: '90',
    text: 'Of all aspects of morality, the mystical aspect alone is of utmost importance. In fact, we may say that, that which conduces to mystical elevation is alone moral. All other things are not really moral. We may very well define morality in these words.',
    reference: ' Glimpses page no.112.',
    category: 'Mysticism',
  },
  {
    id: '91',
    text: 'It is a matter of common knowledge that even for heights to be reached in artistic, scientific, or poetic activity, a certain amount of direct, immediate, almost cataclysmic, contact with Reality is required. Far more is this the case in the matter of mystical realisation.',
    reference: ' M.M. preface page no.1/vii',
    category: 'Mysticism',
  },
  {
    id: '92',
    text: 'The faculty of God-realisation is a God-given gift. The faculty of realising God is a native faculty, and by that alone will one be able to realise God.',
    reference: ' M.M. chapter viii-5. page no. 199/261',
    category: 'Mysticism',
  },
  {
    id: '93',
    text: 'As a mirror may be covered by dust, as fire may be covered by smoke or as a foetus might be covered by amniotic membrane, even so our spiritual life may be covered by lust. We have to drive it away; then alone would the Atman be born.',
    reference: ' B.G.P.G.R. page no.252/224.',
    category: 'Mysticism',
  },
  {
    id: '94',
    text: 'When the wick of dispassion is soaked in the ghee of devotion, and when it is ignited by the flame of knowledge through concentration, the light of spiritual realisation shines out.',
    reference: ' P.G.K.L.page no.76.',
    category: 'Mysticism',
  },
  {
    id: '95',
    text: 'Whatever a devotee mystically experiences is always an index of his own spiritual achievement.',
    reference: ' B.G.P.G.R. page no. 69/63',
    category: 'Mysticism',
  },
  {
    id: '96',
    text: 'Mystical phenomena are a necessary accompaniment of mystical life. But what constitutes the essence of mystic realisation is not these mystical phenomena themselves, but an unfaltering, unbending, unending love of God.',
    reference: ' M.M. preface page no. 21 xxvii.',
    category: 'Mysticism',
  },
  {
    id: '97',
    text: 'If you are firm in devotion the vision of God will also be continuous and firm; otherwise, it will be unsteady.',
    reference: ' P.G.K.L.page no.231.',
    category: 'Mysticism',
  },
  {
    id: '98',
    text: 'In your meditation you must forget the distinction between the day and the night. and God will give you such experience that will make you to forget the distinction between day and night.',
    reference: '',
    category: 'Mysticism',
  },
  {
    id: '99',
    text: 'You have to meditate entirely within yourself by the help of the breath, and one of the characteristics of the success of your meditation would be that the Name would reveal itself before you.',
    reference: ' P.G.H.L.page no. 154/188',
    category: 'Mysticism',
  },
  {
    id: '100',
    text: 'The name that you are using in meditation will be the carrier of both light and sound, as well as of the form of God.',
    reference: ' P.G.K.L.page no.200.',
    category: 'Mysticism',
  },
  {
    id: '101',
    text: `When the light and the sound experiences have been attained, God might take it into His head to make an appearance before you. But lest He might appear and run away, 'we should look at Him gently, continuously'. Do not allow Him to run away.`,
    reference: ' P.G.K.L.page no.200.',
    category: 'Mysticism',
  },
  {
    id: '102',
    text: 'When one has trodden the path of God for some time, he will be able to cognise the subtle movements of God. He will see the motions of God in various supersensuous ways. He should know the subtle movements and should not forget them in his heart. This constitutes the sign-post on your way towards God.',
    reference: ' P.G.K.L. chapter IV- page no. 58',
    category: 'Mysticism',
  },
  {
    id: '103',
    text: 'We should not be idle or rest content merely with the intuitive experience we have; that experience must grow from day to day and from year to year, and the ultimate result of the growth of this kind of supersensuous experience would be a sort of an asymptotic approximation to Reality.',
    reference: ' P.G.K.L.page no.4.',
    category: 'Mysticism',
  },
  {
    id: '104',
    text: `'The light of Atman is seen like a shining pearl',\n\n1.You cannot catch hold of it even though you try utmost to hold it fast.\n\n2.Secondly, you cannot fix it on the nose or make a nose-ring of it, because it is not physical.\n\n3. You can have a necklace of these pearls if you want.`,
    reference: ' P.G.K.L.page no.229.',
    category: 'Mysticism',
  },
  {
    id: '105',
    text: 'Anybody who dives into the ocean of the spiritual life, even for a short time, is able not merely to see the pearl but also a necklace of pearls and even an unending series of necklaces.\n\nSo the vision of this pearl is the thresh-hold of spiritual experience.',
    reference: ' P.G.K.L.page no.229.',
    category: 'Mysticism',
  },
  {
    id: '106',
    text: 'God appears to those who surrender themselves to Him. Those who are having spiritual intuition and those who are poor in spirit have the vision of God.',
    reference: ' P.G.K.L.page.no.164.',
    category: 'Mysticism',
  },
  {
    id: '107',
    text: 'We must control our senses, and use them not for worldly pleasure, but in the service of God, so that we may taste by the grace of God the ambrosial juice from the name of God.',
    reference: ' P.G.K.L. page no. 48.',
    category: 'Mysticism',
  },
  {
    id: '108',
    text: 'When we shut all the sense organs to outer perceptions, then probably by proper meditation on God, and by His Grace, internal senses open, and we are able to perceive, hear and speak things which it would be ordinarily impossible for human beings to do.',
    reference: ' P.G.H..L.page no. 200/236',
    category: 'Mysticism',
  },
  {
    id: '109',
    text: 'God is both before and behind, God moves all round about us. God assumes form after form. They are infinite. If God is pleased to show us any of them, that is enough for us.',
    reference: 'P.G.K.L.page no.93.',
    category: 'Mysticism',
  },
  {
    id: '110',
    text: 'The spiritual aspirant must be full of concentration. Concentration should be so intense that as soon as you begin to concentrate, the form of God should appear before you. He must have that spiritual concentration and that devotion to God, which should result in multi-coloured experience.',
    reference: ' P.G.H.L.page no.158-166/192-201',
    category: 'Mysticism',
  },
  {
    id: '111',
    text: 'Aham Brahmasmi, Tattvamasi are good pieces of advice, no doubt, but a repetition of them Mantra-wise, with or without the rosary, would be of no avail. What matters is the experience of the identity of Self and God, not a mere assertion of the identity.',
    reference: 'P.G.H.L..page no.171/206.',
    category: 'Mysticism',
  },
  {
    id: '112',
    text: 'When you have been able to see God by the internal eye, open your eyes and see whether you are able to see him by the physical eye, if you can do so it would be a corroboration of the veracity of the inner vision of your eye. So the two things must go together pari passu, the inner vision and the outer vision. When the two support each other, then alone there is experience of Reality.',
    reference: ' P.G.K.L. page no. 208',
    category: 'Mysticism',
  },
  {
    id: '113',
    text: `The universally immanent God must be identified with one's self. This is as much as to say that we must have the experience of Tattvamasi or Soham. Unless this takes place the moss of delusion will not disappear, infatuation will not come to an end.`,
    reference: 'P.G.H.L. page no. 118/152.',
    category: 'Mysticism',
  },
  {
    id: '114',
    text: `God must be seen both internally and externally; further, God must be identified with one's own self; and finally, it is only when this experience is attained that illusion may disappear.`,
    reference: ' P.G.H.L..page no.118/152.',
    category: 'Mysticism',
  },
  {
    id: '115',
    text: 'Mystical light makes other objects invisible. Mystic sound likewise absorbs all other sounds.',
    reference: ' Glimpses page no.134.',
    category: 'Mysticism',
  },
  {
    id: '116',
    text: 'If you are firm in devotion the vision of God will also be continuous and firm; otherwise, it will be unsteady.',
    reference: ' P.G.K.L.page no.231.',
    category: 'Mysticism',
  },
  {
    id: '117',
    text: 'The different forms which the mystic sees, the sounds that he hears, the smells that he enjoys and so on, are not drawn from the outside world. They come from within. They are centrally initiated.',
    reference: ' B.G.P.G.R. page no.233/207.',
    category: 'Mysticism',
  },
  {
    id: '118',
    text: 'Vision of God remains steady before the mystic when he is in the company of the saints. When alone to himself, his mind may not be equipoised; but when he is in the company of the saints, it remains absolutely steady, untouching, unmoving and equanimous which may well be regarded as the height of spiritual experience.',
    reference: ' P.G.K.L.page.no.275.',
    category: 'Mysticism',
  },
  {
    id: '119',
    text: 'We must perceive God in all beings, in everything. We must be able to see and perceive Him with eyes shut or open. Spiritual vision is supersensuous. A blind man sees the vision better as there is nothing to blur it.',
    reference: ' Glimpses page no.147.',
    category: 'Mysticism',
  },
  {
    id: '120',
    text: 'What little spiritual experience we are blessed with, should itself gradually evolve and culminate in that grand, final experience, Sarvam Khalvidam Brahma.',
    reference: ' Glimpses page no. 109.',
    category: 'Mysticism',
  },
  {
    id: '121',
    text: 'A simple intellectual apprehension of Reality will never lead one to actual spiritual experience. Thus it can neither be an end nor a means of God-realisation. At the most, it can serve as a minor aid to it.',
    reference: ' Glimpses page no. 109.',
    category: 'Mysticism',
  },
  {
    id: '122',
    text: `The mind should be placed on the feet of God. When it has been so placed, we should not lift it up again; for, God's form will melt away if it be moved but a little. God will now embrace the Saint, and will keep him beside Himself.`,
    reference: ' M.M. chapter XVI-82. page no.348/455',
    category: 'Mysticism',
  },
  {
    id: '123',
    text: 'Indeed it is in the nature of all mystical experience to appear contradictory. As soon as we begin to be aware of it, we forget it. But as soon as we forget it, it comes within the ken of our consciousness.',
    reference: ' M.M. chapter xix-60. page no. 410/535',
    category: 'Mysticism',
  },
  {
    id: '124',
    text: 'The Infinite must be invoked with a devotional heart. But it is very difficult to entertain such intense devotion, such a passionate longing for the Lord. It is only the company of saints that can induce it.',
    reference: ' Glimpses page no.149.',
    category: 'Mysticism',
  },
  {
    id: '125',
    text: `Good meditation is an outcome of the grace of God. According to the spiritual law of tropism, God Himself attracts the devotee and draws him nearer and nearer. It is the growing attractive power of the 'Vastu' that heightens the quality of meditation.`,
    reference: 'Glimpses page no.125-126.',
    category: 'Mysticism',
  },
  {
    id: '126',
    text: 'The enjoyment of ecstatic bliss inside ourselves is the same thing as becoming one with Brahman.',
    reference: ' B.G.P.G.R. page no.224/199.',
    category: 'Mysticism',
  },
  {
    id: '127',
    text: 'Atman cannot be realised except by one whom the Atman himself chooses, before such a one does the Atman reveal his proper form. This is verily the doctrine of Grace.',
    reference: ' C.S.U.P. page no. 345.',
    category: 'Mysticism',
  },
  {
    id: '128',
    text: 'Unless the emotions are purified, and are turned towards the service of God, no seeing of Him face to face is ever possible. It seems that Intelligence, Will, and Feeling are all necessary in the case of the Mystical endeavour: only Intuition must back them all.',
    reference: ' M.M.preface page no. 2/viii',
    category: 'Mysticism',
  },
  {
    id: '129',
    text: `If we take into account the integrity of man's consciousness as a whole, it would seem absolutely impossible, in the interest of the highest development of which man's consciousness is capable, to sunder the intellectual from the moral, as the moral from the mystical element.`,
    reference: ' C.S.U.P. page no.211/287-288.',
    category: 'Mysticism',
  },
  {
    id: '130',
    text: `Vastu:- Philosophically it means the thing-in-itself... This vastu, this thing-in-itself, is beyond all thought and imagination...The vastu is the real entity, what is called a 'spiriton' or atomic or monadic form of God. Any form which it assumes might be called vastu.`,
    reference: ' P.G.K.L.page no.241.',
    category: 'Mysticism',
  },
  {
    id: '131',
    text: `A scientific aspect of the vastu:- You cannot fathom its depth. No plummet can sound its depth and at the same time, 'it fills the whole universe', It is not only immanent but also transcendent. So in every nook and corner of the world, you find this vastu.`,
    reference: ' P.G.K.L.page no.241.',
    category: 'Mysticism',
  },
  {
    id: '132',
    text: `There is a vast difference between the vision of 'Vastu' and that of other objects. The former is produced from within, the latter from without. External vision requires an empirical object. This is not the case with internal vision. As regards 'vastu' there is central initiation, i.e., it is created internally and is experienced without external paraphernalia.`,
    reference: ' Glimpses page no.127.',
    category: 'Mysticism',
  },
  {
    id: '133',
    text: `For the vision of an external object, light is required; eyes must be in a normal, healthy condition; and at the same time, they must be open. But for the vision of 'Vastu' none of these factors is necessary.`,
    reference: ' Glimpses page no.127.',
    category: 'Mysticism',
  },
  {
    id: '134',
    text: `The Vastu possesses the attractive power from the very beginning. Power is inherent in the 'Vastu'. We fail to realise the power in the beginning on account of our mental impurity. As soon as the process of purification of our heart starts, we begin to realise and appreciate the attraction and respond to it properly.`,
    reference: ' Glimpses page no.128.',
    category: 'Mysticism',
  },
  {
    id: '135',
    text: 'No man can hope to attain vastu unless he has got real bhava or devotion.',
    reference: 'P.G.K.L.page no.242.',
    category: 'Mysticism',
  },
  {
    id: '136',
    text: 'We may say that, that kind of mystical experience must be invalid which does not tend to an intellectual clarification of thought.',
    reference: ' M.M. preface page no.25/xxxiii.',
    category: 'Mysticism',
  },
  {
    id: '137',
    text: `You can see God inside, outside, to the left, to the right, above, below and everywhere... When you can see God in such a manner then alone you may be entitled to the name of a 'Sthitaprajna'.`,
    reference: ' B.G.P.G.R. page no.222/197,',
    category: 'Mysticism',
  },
  {
    id: '138',
    text: 'There is neither any rising nor any setting of the intense light, both internal and external and for which there is neither beginning nor end. This ecstatic joy is pure and unadulterated; it is always sweet; it does not suffer any diminution and it is enjoyed every-day by the wise who realise the self.',
    reference: ' P.G.K.L.page no.257.',
    category: 'Mysticism',
  },
  {
    id: '139',
    text: 'That Name which will reveal itself before you in meditation automatically, unconsciously, even without your thinking about it, is the only Name which is Ajara and Amara.',
    reference: ' P.G.H.L.page no. 154/188.',
    category: 'Mysticism',
  },
  {
    id: '140',
    text: 'While we are meditating there is a celestial Name which unfolds itself to our auditory sense at the height of meditation. That Name is Ajara and Amara. When a man comes into possession of this Name, his path Godward becomes clear.',
    reference: ' P.G.H.L. page no.156/191.',
    category: 'Mysticism',
  },
  {
    id: '141',
    text: 'There are eight marks to be found in a state of God realisation - the hair stand on end; the body begins to perspire; a shiver passes through the system; tears flow from the eyes; the heart is filled with joy the throat becomes choked; there is a mystical epoche; and there are long inspirations and expirations.',
    reference: ' M.M. chapter xi-7. page no. 225/294.',
    category: 'Mysticism',
  },
  {
    id: '142',
    text: 'Life is evanescent; but while it lasts try to merge yourself in God and when you have reached that state you will find that you have become your own real Self. ',
    reference: ' P.G.K.L.page.no.271. ',
    category: 'Mysticism',
  },
  {
    id: '143',
    text: 'God is our very life and we should not be indifferent to Him.  There is intense and brilliant moon-light without the moon, covering the whole surface of the earth and all our senses are continuously engaged in enjoying it with great delight.  Inside the heart, there is a supremely beautiful divine Form and from it, is overflowing intense and radiant happiness which comes only when the working of the mind stops. ',
    reference: ' P.G.K.L.page no.269. ',
    category: 'Mysticism',
  },
  {
    id: '144',
    text: 'When the devotee sings the praises of God in a sleeping posture, God listens to them in a sitting posture;  if he praises God in a sitting posture, God stands up to listen to it and if the devotee prays in a standing posture, God listens to him in a pleased and nodding pose;  and if the devotee praises God while nodding himself, He throws open the doors of heaven, makes him the master of heavens and allows him to plunder its treasures. ',
    reference: ' P.G.K.L.page.no.271. ',
    category: 'Mysticism',
  },
  {
    id: '145',
    text: 'When we have seen God, all this world vanishes from us.  We are unable to see the moon, and the sun, and the stars.  We are unable to see the earth and the sky.  Every nook and cranny of the universe becomes filled with God... The whole world indeed becomes God, and there remains no distinction between God and Devotee. ',
    reference: ' M.M. chapter V-2. page no. 167/222 ',
    category: 'Mysticism',
  },
  {
    id: '146',
    text: 'Spiritual realiser is so engrossed in the happiness of his own Self, that he does not care for any powers that may accrue to him.  He is content with the knowledge of Self; He feeds on the highest joy;  He drives away all egoism, leaves away all passion, becomes the world, and moves in the world. ',
    reference: 'M.M. chapter III-86. page no.121/159 [cite: 36, 37]',
    category: 'Mysticism',
  },
  {
    id: '147',
    text: 'If once God reveals Himself to the devotee in his heart, then that vision cannot be confined to the devotee\'s heart only.  He sees God everywhere. God reveals Himself to him as the all-pervading Atman, assuming various forms. ',
    reference: ' M.M. chapter XII-52. page no.254/332 [cite: 43, 44]',
    category: 'Mysticism',
  },
  {
    id: '148',
    text: 'When the aspirant realises the various beings as resting in the One and evolve from the One alone, he attains Brahman. [cite: 50, 51]',
    reference: ' Glimpses page no.119. ',
    category: 'Mysticism',
  },
  {
    id: '149',
    text: 'The whole universe is centred in one place and the world has proceeded from the same place.  That is the One Supreme Being. A person who has directly experienced this can alone be called a realised Saint. ',
    reference: ' Glimpses page no.119. ',
    category: 'Mysticism',
  },
  {
    id: '150',
    text: 'It is beatification that constitutes the ultimate end, and it is this that has been aimed at by all the mystics of the world.  It is this ideal of the enjoyment of perfect bliss which binds the community of saints together. ',
    reference: ' P.G.K.L.page no.6. ',
    category: 'Mysticism',
  },
  {
    id: '151',
    text: 'There is all-pervading sunlight filling up all space, when there is no sun.  This fact is known only to the self-realised person who loses himself wholly in the self-conscious state. ',
    reference: ' P.G.K.L.page no.269. ',
    category: 'Mysticism',
  },
  {
    id: '152',
    text: 'The self-conscious state is not something which can be expressed in profuse and plentiful words.  It is a state of pure and absolute knowledge, It is a matter to be known only after having intimate and personal experience of God who is our very life-breath. ',
    reference: ' P.G.K.L.page no.269. ',
    category: 'Mysticism',
  },
  {
    id: '153',
    text: 'When we are actually before God, the kettle-drum is ceaselessly sounded.  Secondly, you must be able to visualise the lustrous form of God and at the same time see various colours.  God appears all the more beautiful when he appears in this light and accompanied at the same time with sound, and followed by colours. ',
    reference: ' P.G.K.L.page no.244. ',
    category: 'Mysticism',
  },
  {
    id: '154',
    text: 'There is synchronousness of light and sound. You do not see the light first, and Anahata sound after some time.  No. They are synchronous. They are simultaneous. Your mind is full and flooded.  You do not know whether you are hearing or seeing. ',
    reference: ' P.G.K.L.page no.250. ',
    category: 'Mysticism',
  },
  {
    id: '155',
    text: 'We talk about the ten directions which envelope the universe, but God spreads His hands and feet beyond them.  So omnipresent is God! There is not a nook or a cranny of the universe which is not filled with God. ',
    reference: ' P.G.K.L.page.no.168. ',
    category: 'Mysticism',
  },
  {
    id: '156',
    text: 'The real feet are the spiritual feet and the highest realisation would consist in being able to see the feet of God. It is these feet we have to worship [cite: 103, 106, 107]',
    reference: ' P.G.K.L.page no.102. ',
    category: 'Mysticism',
  },
  {
    id: '157',
    text: 'Divine juice cannot be obtained, except at the price of desperate devotion to God.  A great deal of torture and trouble must be experienced before one gets even a small quantity of this divine juice.  Divine juice could be partaken of only by a man who has no head over his shoulders.  It is only when we throw down our life that we can rise to the heights of God\'s experience. ',
    reference: ' P.G.H.L.page no.229/266. ',
    category: 'Mysticism',
  },
  {
    id: '158',
    text: 'Just as a serpent nods, and probably nods frequently, while hearing the sound of a flute, so the disciple too may nod, provided he hears that divine music... Nodding frequently is the highest step in spiritual progress. ',
    reference: ' P.G.K.L.page no113,117. ',
    category: 'Mysticism',
  },
  {
    id: '159',
    text: 'In mystical experience is Darshana, Sparshana and Sambhashana, to see God, to touch Him and to have conversation with Him.  These are regarded as the three final stages of a man\'s experience of God. ',
    reference: ' P.G.K.L.page.no.170. ',
    category: 'Mysticism',
  },
  {
    id: '160',
    text: 'We must be able to visualise the form of God.  Sitting in enjoyment of Nadas and sitting under the canopy of illumination would not be enough.  We must be able to see the Form of God and rise through the spinal cord of the Sushuma to the Trikuta, or what might be called the spaceless region, and there enjoy beatitude. ',
    reference: ' P.G.K.L.page no.103,104. ',
    category: 'Mysticism',
  },
  {
    id: '161',
    text: 'It is the combined character of mystical experience, namely, its ineffable and intuitive character, which has served to make all God-aspiring humanity a common and hidden Society, the laws of which are known to themselves if at all.  We may even say, that they are known only to God, and not even to them! ',
    reference: ' M.M. preface page no.2/viii [cite: 141, 142]',
    category: 'Mysticism',
  },
  {
    id: '162',
    text: 'Every nerve cell begins to vibrate with the name of God, because of the spiritual experience.  You see and hear by brain instead of eye and ear. ',
    reference: ' अमर संदेश सुधा. पा.क्र.287. ',
    category: 'Mysticism',
  },
  {
    id: '163',
    text: 'Having realised God in every nook and corner of the universe, and in fact in all forms of existence-cosmic, psychic, epistemological and mystical, the saint plunges himself into a wonderful rapture... The mystic experiences a rapturous vision of the immaculate Spirit, whereby the whole world looks transfigured. ',
    reference: ' P.G.K.L.page.no.284.287-288 ',
    category: 'Mysticism',
  },
  {
    id: '164',
    text: 'Until a man is able to see his own Form by the grace of his spiritual teacher, he may not be regarded as having attained to the highest mystical experience. ',
    reference: ' P.G.H.L.page no. 170/205. ',
    category: 'Mysticism',
  },
  {
    id: '165',
    text: 'If you experience the flow of spiritual energy inside you, particularly in the nervous system from the navel to the lateral ventricle, through the spinal cord, then even your skin would be a sort of reverberatory organ for your spiritual experience.  Every hair will stand on its end. \'All the hairs on the skin become living eyes that keep on looking at the form of God.\' ',
    reference: ' P.G.K.L.page no.59. ',
    category: 'Mysticism',
  },
  {
    id: '166',
    text: 'When you attain entire unison with yourSelf and when you have lost the consciousness of your body in the blissful enjoyment of the Self, you will visualise the Reality here, there and everywhere;  it is wholly a subtle matter known only to the wise who have realised it. ',
    reference: ' P.G.K.L.page no.268. ',
    category: 'Mysticism',
  },
  {
    id: '167',
    text: 'The experience of God can be attained in all the states of consciousness - in the waking state, in the dream state, in the deep sleep state, as well in the super-conscious state.  When all these states become alike, then God is attained. ',
    reference: ' M.M. chapter xix-48. page no. 229/173 ',
    category: 'Mysticism',
  },
  {
    id: '168',
    text: 'The mystics teach that a rising devotee must ultimately feel his identity with his own Self.  It is only then that there is perfect unison. ',
    reference: ' B.G.P.G.R.page no.70/63. ',
    category: 'Mysticism',
  },
  {
    id: '171',
    text: 'One can enjoy the Bliss of experience only in mystic silence.  Just as a dumb man cannot express the sweetness of the sugar he is eating, similarly, by our bliss we enjoy bliss, and in that way attain to emancipation even during life. ',
    reference: ' M.M. chapter VIII-6. page no.202/264 [cite: 194, 195]',
    category: 'Mysticism',
  },
  {
    id: '172',
    text: 'Mystical experience is Self-awareness, is full of bliss and is ever-growing. Hence our mind becomes more and more powerful. [cite: 199, 200]',
    reference: ' Glimpses page no. 122. ',
    category: 'Mysticism',
  },
  {
    id: '173',
    text: 'Continuity, universality and bliss are criteria of Mystical experience. Hypnotic power diminishes by its use while mystical experience grows day by day. ',
    reference: ' Glimpses page no. 122. ',
    category: 'Mysticism',
  },
  {
    id: '174',
    text: 'The God-realiser rises superior to the considerations of the body, and is indifferent to its growth or decay because he has attained to liberation while living and though living. ',
    reference: ' P.G.K.L.page no.280. ',
    category: 'Mysticism',
  },
  {
    id: '175',
    text: 'When we have once seen God, it matters little to what place we go.  As soon as we remember God, God shall be near us.  We shall forget our hunger and thirst in the pleasure of God\'s Name. ',
    reference: 'M.M. chapter viii-5. page no. 199/261 ',
    category: 'Mysticism',
  },
  {
    id: '176',
    text: 'Whatever we may desire from the bottom of our heart shall come to take place by the grace of God, and all obstacles will come to an end.  By Meditation on God is acquired Illumination. By Meditation on God, Greatness is attained.  Therefore one\'s first duty ought to be to meditate on God. This is indeed a matter of one\'s own experience. ',
    reference: ' M.M. chapter xix-5. page no.376/489 ',
    category: 'Mysticism',
  },
  {
    id: '177',
    text: 'There is indeed no limit to the merit of a man who has seen the Self. For him, all sins are at an end. [cite: 234, 235]',
    reference: ' M.M. chapter xix-8 page no 379/493. ',
    category: 'Mysticism',
  },
  {
    id: '178',
    text: 'God\'s experience is to be regarded as a mountain, the approach, the attack and the appropriation of which is equally difficult;  but once the process is started, its immanent energy or hope will carry you to the end in the midst of, and inspite of difficulties. ',
    reference: ' पुण्य-स्मृती पा.क्र. 75 ',
    category: 'Mysticism',
  },
  {
    id: '179',
    text: 'Spiritual energy is infinite and eternal and that the whole universe arises from it and dissolves in it.... This spiritual energy, when generated, also produces in us such emotions as love, compassion, modesty, dispassion, wonder, terror and bliss.  The compassion and dispassion produced as a result of the growth of thi energy, would alone be stable and enduring.  Hence real dispassion desirelessness and fearlessness would be possible only when spiritu experiences develop. ',
    reference: ' Glimpses page no.138. ',
    category: 'Mysticism',
  },
  {
    id: '180',
    text: 'The mystic while enjoying ecstatic bliss, might appear to others as sleeping, whereas he is really fully awake.  How can such a man sleep when God\'s presence always keeps him awake? ',
    reference: ' P.G.K.L.page.no.305. ',
    category: 'Mysticism',
  },
  {
    id: '181',
    text: 'A man who has realised his ultimate spiritual nature, shall never be born again and he will remain ever merged in an extremely blissful condition. ',
    reference: 'P.G.K.L.page no.278. ',
    category: 'Mysticism',
  },
  {
    id: '182',
    text: 'The saint who is one with \'spiritual light\', renounces everything worldly, and becomes famous as a donor of the gift of spiritual life to others. ',
    reference: ' P.G.K.L.page no.280. ',
    category: 'Mysticism',
  },
  {
    id: '183',
    text: 'An Ensign, an emblem given by God takes the aspirant safely to his destination through all toil and termoil of life.  Forms, light, sound and colour which a mystic experiences are merely the outward correlates of the qualities of his heart. ',
    reference: ' P.G.K.L.page no.261. ',
    category: 'Mysticism',
  },
  {
    id: '184',
    text: 'Whatever the mystic experiences by any sense, corresponds exactly to the stage of development of his own spiritual temper and capacity.  His spiritual status may be measured by what he is able to see.  Mystical experience and the quality of the heart correspond with each other. ',
    reference: ' P.G.K.L.page no.261. ',
    category: 'Mysticism',
  },
  {
    id: '185',
    text: 'It has been the usual teaching of the great mystics that the forms which they see in mystical experience are ultimately identical with themselves, and a man has to sit in judgment upon the quality of his own mind and his own experience by taking into account the different forms of mystical realisation which he experiences. ',
    reference: ' B.G.P.G.R. page no. 69/63 ',
    category: 'Mysticism',
  },
  {
    id: '186',
    text: 'We are full of joy when we are in the contemplation and realisation of God.  That state of beatification is itself our liberation. Liberation is not to be found after death.  But to know God, to do His work, to enjoy His presence and to devote oneself to His service are exactly what a Jivan-mukta ought to do and that is the teaching of the Bhagavadgita. ',
    reference: ' B.G.P.G.R.page no.190/169. ',
    category: 'Mysticism',
  },
  {
    id: '187',
    text: "When God has taken secure lodgment inside a man's heart, whatever he does is indeed the worship of God... What words come out of an intense devotion in such a man's heart may alone be regarded as words of true inspiration.",
    reference: ' M.M. chapter xix-48 page no. 402/524',
    category: 'Mysticism',
  },
  {
    id: '188',
    text: 'It is only when these three things meet, namely, the spiritual teacher, devotion and mystical experience, that we have the possibility of crossing that great flood of illusion.',
    reference: 'B.G.P.G.R. page no.62/56.',
    category: 'Mysticism',
  },
  {
    id: '189',
    text: 'The spiritual waves spread out from a spiritually realised soul and influence the world... If physical sound can produce wonderful results in surgery etc. then Anahata sound can produce more.',
    reference: ' Glimpses page no.126.',
    category: 'Mysticism',
  },
  {
    id: '190',
    text: 'While we are contemplating God, both body and mind are entirely transformed. When the Self has been transformed in God, and when the mind has been suffused in illumination, the whole of creation looks divine, and all of a sudden the influx of God fills the whole world.',
    reference: 'M.M. chapter XVI-81. page no.346/453',
    category: 'Mysticism',
  },
  {
    id: '191',
    text: 'He who has enjoyed the happiness of the Self, lives in himself; and there is no wonder that he should leave all sensual enjoyment.',
    reference: ' M.M. chapter 111-86. page no.120.158',
    category: 'Mysticism',
  },
  {
    id: '192',
    text: 'There is nothing comparable to the happiness of the Self, and that therefore sensual enjoyment ceases to have any attraction for the mystic. He has become the world himself, and therefore all notion of difference vanishes. Similarly, all hatred forthwith ceases.',
    reference: ' M.M. chapter 111-86. page no.120/158.',
    category: 'Mysticism',
  },
  {
    id: '193',
    text: 'Once God is revealed in His true universal form, a devotee becomes dead to all world-vision. Once He is revealed, the subtle body, the cause of all bondage, perishes without a stroke. All fear of birth and death disappears, and the stage is reached where the world is not, and God alone is. His devotees reach this stage by constantly praying to Him.',
    reference: ' M.M. chapter XII-52. page no.254/332',
    category: 'Mysticism',
  },
  {
    id: '194',
    text: 'No experience can be called valid or real, unless at the same time it is universal and necessary. Such universal and necessary experience is objectively valid objectivity, necessity and validity, all these marks are present in mystical experience.',
    reference: ' P.G.K.L.page no.4.',
    category: 'Mysticism',
  },
  {
    id: '195',
    text: 'The surest criterion of Mysticism is the validity of the experience as enjoyed by the mystic himself. Before that, there is no appeal; for it, there is no criterion.',
    reference: ' M.M. preface page no.29-30/xxxviii',
    category: 'Mysticism',
  },
  {
    id: '196',
    text: "The only criterion for the reality of a man's experience is himself and God and nobody else. There is no intellectual argument, no logical proof which can either support or refute or deny what he might say. The reality of his experience and the heights which he has reached are known only to himself and to his Maker..",
    reference: 'B.G.P.G.R. page no. 235-236/210.',
    category: 'Mysticism',
  },
  {
    id: '197',
    text: "The vision of God must not be imagination, it must not be hallucination, it must be a veritable perception of God. It is only when this experience namely बाहर भीतर एकही जानो is attained that the mind can be said to have realised the spiritual existence of God. And that this universally immanent God must be identified with one's self.",
    reference: ' P.G.H.L.page no. 117/152',
    category: 'Mysticism',
  },
  {
    id: '198',
    text: 'Daily growth in spiritual experience is also a vital factor in its continuity or permanence. Our mystical experience must not only be super-sensuous and blissful, but it must also be continuous and permanent. It must not desert us; we may desert it, because at the time of death we are nowhere but that experience remains. That Anahata Shabda which we hear remains, that mystical form which we see remains, while our body falls off.',
    reference: ' B.G.P.G.R. page no. 232/207.',
    category: 'Mysticism',
  },
  {
    id: '199',
    text: 'The internal and external perception of God must be alike. If there is internal perception to which nothing external corresponds, it may be a case of imagination, hallucination or illusion. If, on the other hand, there is something external to which nothing internal corresponds, then it cannot be evidently a case of supersensuous experience and may be ultimately unreal.',
    reference: 'P.G.H.L.page no.141/176',
    category: 'Mysticism',
  },
  {
    id: '200',
    text: 'A Spiritual Realiser alone can understand the signs of a Spiritual Realiser.',
    reference: ' हिं.प.सो. पा.क्र. 320',
    category: 'Mysticism',
  },
  {
    id: '201',
    text: 'One of the real tests of spiritual experience is that you must be able to vindicate your own position and win the debate with your intellectual antagonists.',
    reference: ' P.G.K.L. page no.116-117.',
    category: 'Mysticism',
  },
  {
    id: '202',
    text: 'It is our own experience that matters and it is that experience which makes Reality real.',
    reference: ' P.G.K.L.page no.218.',
    category: 'Mysticism',
  },
  {
    id: '203',
    text: "If he appears to be true to himself, if his whole life is an embodiment of absolute right and truth, if he does not deviate an inch from the path of goodness and virtue, if his whole life is dedicated to the contemplation of God and the service of Humanity, if he regards his own mystical advancement as a step towards the realisation of either of these ends, then we do not think that a mystic's search after God and its validity need be much called into question.",
    reference: ' M.M.Preface page no.29-30/xxxviii',
    category: 'Mysticism',
  },
  {
    id: '204',
    text: 'When you perform your spiritual meditation well, you become overjoyed as by drinking half a seer of milk. It means that the spiritual experience has the power in it, not merely to conquer the mind, but to affect and conquer even the body.',
    reference: ' P.G.K.L.page no.122.',
    category: 'Mysticism',
  },
  {
    id: '205',
    text: 'What is the use of our Samadhic experience unless it resolves itself into psychological, moral, metaphysical, and even eschatological consequences?',
    reference: 'P.G.H.L.page no.226/263.',
    category: 'Mysticism',
  },
  {
    id: '206',
    text: 'The Spiritual teacher enables us to transcend our philosophic doubts. It is only the power of realisation which will carry you beyond these philosophic doubts.',
    reference: ' P.G.K.L.page no.102.',
    category: 'Mysticism',
  },
  {
    id: '207',
    text: 'The immediate effects of God-realization upon the mystic are the entire abatement of bodily excitement, the resolution of all doubts, the obtainment of infinite power, the enjoyment of illimitable joy, destruction of all fear and the fulfillment of any end that may be contemplated by the mystic.',
    reference: ' C.S.U.P. page no 350.',
    category: 'Mysticism',
  },
  {
    id: '208',
    text: 'Terrific death is afraid to come near us when we are thinking about God. Lust, anger, arrogance and avarice must cease. Also, all desires, all actions, all illusions, all sins and all diseases must disappear. When such a state is reached, true immortality is attained',
    reference: 'P.G.H.L.page no.226/263.',
    category: 'Mysticism',
  },
  {
    id: '209',
    text: 'So far as the utility of the mystic to the society is concerned, we may almost take it to be a truism, that a mystic who is not of supreme service to the society is not a mystic at all.',
    reference: ' E.O.M.O.T. - page no.41./M.M.Preface page no.28/xxxvi-xxxvii',
    category: 'Mysticism',
  },
  {
    id: '210',
    text: 'Liberation means the vision of the manifold form of God.',
    reference: ' क.प.सो.66.',
    category: 'Mysticism',
  },
  {
    id: '211',
    text: 'The power of the spiritual teacher enables the disciple to visualise the form of God wherever his eyes are cast. Such vision itself constitutes the essence of liberation.',
    reference: ' P.G.K.L.page no.78.',
    category: 'Mysticism',
  },
  {
    id: '212',
    text: 'The devotee attains to the Godhead, falling just short of His entire Being. The reason for this approximation or asymptotic realisation is the physical, the mental and other limitations of the mystic. So long as he has a body and a mind and has to live in the world, to that extent and till that time he must fall short of complete divine attainment.',
    reference: ' B.G.P.G.R. page no. 70/64',
    category: 'Mysticism',
  },
  {
    id: '213',
    text: "'Vastu' is the root of all liberation while alive. When you have seen the Form of God, that itself constitutes jivanmukti. You will be liberated while living, and though living.",
    reference: ' P.G.K.L.page no.242.',
    category: 'Mysticism',
  },
  {
    id: '214',
    text: 'Uttering the name of God, feeling His presence near himself, experiencing His immanence in the mind, or realising his identity with God, the seeker goes on to the last Mukti, namely, शरणगमनमुक्ति.',
    reference: ' P.G.H.L. page no.132/166.',
    category: 'Mysticism',
  },
  {
    id: '215',
    text: 'The great mystics of various ages and climes have an identical teaching about the vision of the Self, which is the acme of their spiritual realisation.',
    reference: ' M.M. preface page no.7/xiii',
    category: 'Mysticism',
  },
  {
    id: '216',
    text: 'God-realisers constitute a blessed community, and on account of their intense love for afflicted mankind, they live only for its benefaction and betterment, proclaiming from pole to pole, like a rumbling cloud, the eternal Gospel of God from everlasting to everlasting.',
    reference: ' P.G.K.L.page no. 318',
    category: 'Mysticism',
  },
  {
    id: '217',
    text: 'The Mystic may be a Philosopher, but is not necessarily so. His mystic experience is sufficient for his own elevation into Divinity; but if he philosophises, he may raise thinking humanity into a Divine Kingdom of Ends.',
    reference: ' M.M. Bibliographical Note page no.494.',
    category: 'Mysticism',
  },
  {
    id: '218',
    text: 'Unless at least an iota of the power of creation has descended upon the God-realiser, he may hardly be said to have realised God at all.',
    reference: ' B.G.P.G.R. page no. 267',
    category: 'Mysticism',
  },
  {
    id: '219',
    text: 'He, whose mind is purified by the discharge of his duty and constant prayer to God, feels non-attachment to worldly objects. He then learns to discriminate truly the real from the unreal. This discrimination is knowledge. It is by this that the wise know that the true self is not the body, but the self-effulgent Atman, who informs the physical and the subtle body....the discriminating first realize the unreality of the seemingly solid physical body, then destroy the subtle body, while finally they annihilate egoism and become Brahman themselves.',
    reference: ' M.M.chapter XII-39.page no.247/323',
    category: 'Mysticism',
  },
  {
    id: '220',
    text: 'The philosophy of beatification involves a sort of catalepsia. It is one finger, five fingers, open palm, the one hand being entwined with the other. Such folding together is represented in mystical experience also, by the experience of the eye supported by the experience of the ear, tongue, skin, movement and so forth. This is what the Stoics used to call catalepsia. It is this kind of binding together and integration of supersensuous experiences that constitute absolute beatification.',
    reference: ' P.G.K.L.page no.5.',
    category: 'Mysticism',
  },
  {
    id: '221',
    text: "The Yoga of Namasmarana is the only path that can enable the Sadhaka to attain God-head. This path alone can take a Sadhaka into the inner sanctuary and grant him the vision and bliss of divinity. 'नान्यः पंथाः विद्यते अयनाय' there is no other path for going there. All the saints of the world, have followed the same Pathway and have bequeathed its knowledge to posterity. The Yogas of knowledge, Action and Devotion are contributory to Namasmarana. They cleanse our hearts, fortify our faith, remove our intellectual doubts and facilitate our journey along the Pathway. That is all that they can do.",
    reference: ' Glimpses page no.147.',
    category: 'Mysticism',
  },
  {
    id: '222',
    text: '"The mystics of all ages and countries have spoken the same language, as they are denizens of the same spiritual world. There are no racial, no communal, no national prejudices among them. Time and Space have nothing to do with the eternal and infinite character of their mystical experience. These together constitute a band of divine musicians, each contributing his own note, and all together producing a harmony that is wonderful."',
    reference: ' P.G.H.L.page no.2.',
    category: 'Mysticism',
  },
  {
    id: '223',
    text: 'Shri Kakasaheb Tulpule once asked P.P. Shri Gurudev, "What is your mental condition when your meditation reaches its highest pitch?" Shri Gurudev said, "Nam, different sounds, colours and lights as well as form and bliss are all fused together so completely that it is impossible to experience them separately in that state. Believe me Ganpatrao, believe me, even when two hours passed in this stage, one feels as if only ten minutes have passed"',
    reference: 'Reminiscence',
    category: 'Mysticism',
  }
];