export const namasadan = [
  {
    id: '1',
    category: 'Namasadhan',
    text: 'The first ideal of human life, is to pray incessantly and unceasingly to the God.',
    reference: 'P.G.K.L. page no. 17',
  },
  {
    id: '2',
    category: 'Namasadhan',
    text: 'Name is a symbol of the Divine carrying spiritual energy and therefore the process of Namasmaran is the process of constant identification with the Divine.',
    reference: 'नामसाधनेचे मानसशास्त्र- ग.वि.तुळपुळे. पा.क्र.७२-७३.',
  },
  {
    id: '3',
    category: 'Namasadhan',
    text: 'The name that you are using in meditation will be the carrier of both light and sound as well as of the form of God.',
    reference: 'P.G.K.L.page no.200',
  },
  {
    id: '4',
    category: 'Namasadhan',
    text: 'The real spiritual name, the Divya Nama, is the name which comes laden with spiritual meaning. It is this which is conveyed by the spiritual teacher to his disciple. It comes directly from God and is communicated to the disciple as \'God in posse\'.',
    reference: 'P.G.K.L.page no.189',
  },
  {
    id: '5',
    category: 'Namasadhan',
    text: 'The Name of God is superior to God with form, as well as to God without form. The Name of God is like a lamp placed on the threshold of the tongue, so that it might illumine both the inside and the outside of man.',
    reference: 'P.G.H.L.page no.342/379 & 348/385',
  },
  {
    id: '6',
    category: 'Namasadhan',
    text: 'It is not the Name which we of our own accord take for ourselves that constitutes the Ajara and Amara Name. While we are meditating there is a celestial Name which unfolds itself to our auditory sense at the height of meditation. That Name is Ajara and Amara. So when a man comes into possession of this Name, his path Godward becomes clear.',
    reference: 'P.G.H.L. page no.156/191',
  },
  {
    id: '7',
    category: 'Namasadhan',
    text: 'From the epistemological point of view, we might have names which come laden with meaning, and others which are not so laden - significant names and non-significant names. From the point of view of science, a name might have the highest potentiality of spiritual energy, and another which has no such potentiality. The first kind of name would be the real atom-bomb of spiritual experience.',
    reference: 'P.G.H.L.page no. 347/384',
  },
  {
    id: '8',
    category: 'Namasadhan',
    text: 'That Name which will reveal itself before you in meditation automatically, unconsciously, even without your thinking about it, is the only Name which is Ajara and Amara.',
    reference: 'P.G.H.L.page no. 154/188',
  },
  {
    id: '9',
    category: 'Namasadhan',
    text: 'It is only the Name, which an aspirant might receive from his spiritual teacher who has reached the heights of spiritual realisation, that can be of any avail. The real Name is the name which fructifies. It is entirely \'sui generis\', unique and in a different category altogether.',
    reference: 'P.G.H.L.page no.348/385',
  },
  {
    id: '10',
    category: 'Namasadhan',
    text: 'Meditation should be sincere and devout. Nama is a symbol for realising the ultimate Reality underlying the universe. (Om is the Absolute). We should understand the significance of this Mantra (hymn). Mere vocal utterance of Nama becomes mechanical. We should properly understand the relation of Rupa (Form), Bhava (Devotion), and Nama (Name). Form is a mystical entity or spiritual entity, devotion is a psychological or moral entity while Nama is a mysterious entity, which includes the other two.',
    reference: 'Glimpses page no. -148/165',
  },
  {
    id: '11',
    category: 'Namasadhan',
    text: 'Fixing of the gaze on the tip or top of the nose, observation of the incoming and outgoing breath, mental repetition of the Name along with the breaths distinctly - all these are, no doubt, important factors in the process of meditation. They are all, really, very useful for concentration. But with all that, if the Name has not been imparted by a worthy spiritual teacher, it would never enable a seeker to attain spiritual realisation. The efficacy of the Name rests in the intense Sadhana and spiritual realisation of the Sadguru.',
    reference: 'Glimpses page no.149/166',
  },
  {
    id: '12',
    category: 'Namasadhan',
    text: 'The efficacy of the Name rests in the intense Sadhana and spiritual realisation of the Sadguru. The Name is the carrier of the grace and power of the Lord Himself. We may meditate on the Name imparted by such a Sadguru in any posture that helps concentration. It would not fail to grant the desired fruit of God-vision.',
    reference: 'Glimpses page no.149/166',
  },
  {
    id: '13',
    category: 'Namasadhan',
    text: 'Name is उभयप्रबोधक the illuminator, सुसाखी the witness, and दुभाखी the interpreter between सगुण and निर्गुण. It teaches Saguna to respect Nirguna, and Nirguna to respect Saguna. The great function of schematism in bringing together the opposite irreconciliables is the function here performed by Nama.',
    reference: 'P.G.H.L. page no.148/182',
  },
  {
    id: '14',
    category: 'Namasadhan',
    text: 'The sweetness of the Name is indeed indescribable. The tongue soon gets averse to other kinds of flavour; but the flavour of the Name increases every moment. In fact, the sweetness of the Name cannot be known to God Himself.',
    reference: 'P.G.M.L. preface page no.15-16/ xxii',
  },
  {
    id: '15',
    category: 'Namasadhan',
    text: 'Even if one were to give in charity the whole earth encircled by the seas, that cannot equal the merit of uttering the Name... A repetition of all the Vedas cannot equal one Name of God. All places of pilgrimage have no value before God\'s Name. All sorts of bodily toils are useless before the Name of God.',
    reference: 'P.G.M.L. Page no. 320/418. chapter XVI-55',
  },
  {
    id: '16',
    category: 'Namasadhan',
    text: 'The Name of God is the Form of God, and the Form of God is the Name of God. There is no other remedy except the Name of God; Anybody who says there is another is a fool.',
    reference: 'P.G.M.L.Page no.195/255.chapter VIII-2',
  },
  {
    id: '17',
    category: 'Namasadhan',
    text: 'According to mystics, intuition is a faculty of supersensuous experience which is aroused in us by proper spiritual initiation and practice (Namasmaran).',
    reference: 'P.G.K.L.page no.3',
  },
  {
    id: '18',
    category: 'Namasadhan',
    text: 'The Yogas of knowledge, Action and Devotion are contributory to Namasmarana. They cleanse our hearts, fortify our faith, remove our intellectual doubts and facilitate our journey along the Pathway. That is all that they can do. On account of temperamental differences, the Sadhakas begin their Sadhana by adopting one or the other of these Yogas that suits their nature best. But, in the long run, they must necessarily take recourse to the primary Pathway of Namasmarana. Otherwise, they will not attain their ideal of God realisation. Thus meditation on the Divine Nama is the only Pathway to God.',
    reference: 'Glimpses page no. 147-148/164',
  },
  {
    id: '19',
    category: 'Namasadhan',
    text: 'Our tongue should rise by the spiritual ladder and attain to the supra-sensuous and supreme bliss of God-realisation, by constantly and silently uttering the name of God. When we bark out the name reflexly, automatically, unconsciously, we might rightly be called the dogs of God.',
    reference: 'P.G.K.L.page no.49 & page no. 177',
  },
  {
    id: '20',
    category: 'Namasadhan',
    text: 'There are higher and highest loyalties. Our highest loyalties should be to Naam and God.',
    reference: 'गुरुदेव रानडे जीवनदर्शन - अमर संदेशसुधा २७२.',
  },
  {
    id: '21',
    category: 'Namasadhan',
    text: 'The sole way to the realisation of God, is the constant repetition of God\'s name. One should sit silent, compose his mind and make it pure, and then happiness will know no bounds. God will certainly come and dwell in his heart. This will be the result of his long effort.',
    reference: 'P.G.M.L. page no. 318/415. chapter XVI',
  },
  {
    id: '22',
    category: 'Namasadhan',
    text: 'A mental requirement for successful meditation is the occupation of the mind by only one idea and no other. When the eye is full of the vision of the only one object of our love, no other vision is possible.',
    reference: 'P.G.H.L.page no.356/393',
  },
  {
    id: '23',
    category: 'Namasadhan',
    text: 'Behind work there should be meditation; without meditation, work cannot be performed in a way which conduces to spiritual growth; nor is work nicely performed, without having a spiritual background. Work is useless unless it is related to God.',
    reference: 'गुरुदेव रानडे जीवनदर्शन - अमर संदेशसुधा २७२.',
  },
  {
    id: '24',
    category: 'Namasadhan',
    text: 'The sixty minutes of one hour or the sixty seconds of one minute, not even in one of which we should allow our mind to wander from God. Not a single Shvasa or breath should go in vain, not a single second, not a single minute without God\'s remembrance.',
    reference: 'P.G.K.L.page no.225',
  },
  {
    id: '25',
    category: 'Namasadhan',
    text: 'We should never forget to meditate in the morning, at mid-day, and in the evening, and should at all times give ourselves to the uttering of God\'s Name. We should never forget God\'s name whether we may be merged in happiness or in sorrow, in dejection or in anxiety. At the time of joy and at the time of calamity.... at the time of rest and at the time of sleep we should always utter the name of God.',
    reference: 'P.G.M.L.page no. 399/520. chapter XIX-43',
  },
  {
    id: '26',
    category: 'Namasadhan',
    text: 'You ought to associate yourself with the good in order that you might be able to meditate on God intensely inside your heart. That is the highest thing a man is capable of, and that cannot be accomplished without the company of the good.',
    reference: 'P.G.K.L..page no. 44-45',
  },
  {
    id: '27',
    category: 'Namasadhan',
    text: 'Real meditation is meditation in the presence of God, yet a beginner who might be unable to see the form of God should meditate on the Name with love. The utterance of the Name should not be done mechanically, but the नाम should be meditated upon with a feeling of love, regard and joy. The Name should be tied to every breath lovingly.',
    reference: 'Gurudev R.D.Ranade A Glance At His Allahabad University Days And Other Essays page No.85',
  },
  {
    id: '28',
    category: 'Namasadhan',
    text: 'God is numberless, and the number of times we have uttered the Name of God has nothing to do with His realisation. What is wanted is only the quality and intensity of the heart.',
    reference: 'P.G.H.L.page no.353/390',
  },
  {
    id: '29',
    category: 'Namasadhan',
    text: 'In your meditation you must forget the distinction between the day and the night, and God will give you such experience that will make you to forget the distinction between day and night.',
    reference: 'गुरुदेव रानडे जीवनदर्शन-अमर संदेशसुधा २६२.',
  },
  {
    id: '30',
    category: 'Namasadhan',
    text: 'Khechari, Bhuchari and other Mudras are not the real Mudras. In fact, any kind of poise of the brain and the eyes in which you can concentrate your attention is the Mudra. For example, if you look ahead and see something and concentrate your eyes on it, it is a Mudra. If you concentrate on Anahata-nada it is a Mudra. So Mudra is any poise by means of which you concentrate your attention in any way you like.',
    reference: 'P.G.K.L.page no.107',
  },
  {
    id: '31',
    category: 'Namasadhan',
    text: 'The Methodology of Meditation by means of which one could attain to Reality. Silence should be observed. A certain poise of meditation should be made steady. The mind should feel happy in the illumination of knowledge, and finally One should enjoy the ambrosia of self realisation. When we have done that, and succeeded in doing it for a long time, then it is possible that we might get an insight into the nature of God-head.',
    reference: 'P.G.K.L. page no. 106-107',
  },
  {
    id: '32',
    category: 'Namasadhan',
    text: 'Concentration, is a very important element which almost everybody, who practises meditation tries to achieve. Any man who by looking within finds that his mind is wandering all round must turn it away from all objects and ideas and concentrate it on the one object, namely, God. Let our mind be composed; let fear be away from our mind; let there be no regnant emotion in our system. Then alone would we be able to concentrate on God.',
    reference: 'B.G.P.G.R. page no. 253/224',
  },
  {
    id: '33',
    category: 'Namasadhan',
    text: 'Unless the mind is cleared of the weeds of ideas, the Name of God would not take root in it. The driving of ideas should properly be accomplished in the psycho-ethical manner. If this is not possible, then the disciple might invert and revert his breath, and concentrate on it, or else make his mind travel between the मूलाधार and सहस्रार. Thus, when the mind is caught up either in the name of God, or in the breath, or in the passage from मूलाधार to सहस्रार, other ideas will cease, and the idea of God will be regnant in the mind of the aspirant, who will thus be enabled to reach the \'Unmani\' state. The eye-lashes will now cease to function, and the unmoving eyes will remain focussed on an unmoving spiritual form of God.',
    reference: 'P.G.H.L.page no.214/251',
  },
  {
    id: '34',
    category: 'Namasadhan',
    text: 'In the first place, we should be inspired with one-pointed devotion towards God. We should have no other object of attachment. - अनन्यचेतस्त्वम्. Then secondly, we must practise meditation without sacrificing a single moment. नित्यशः and finally this must be continued from day to day, month to month and year to year to the very end of our life - नित्ययुक्तत्वम्.',
    reference: 'B.G.P.G.R. page no.254/225-226',
  },
  {
    id: '35',
    category: 'Namasadhan',
    text: 'God\'s name is identified with Reality. One realises the sweet music issuing from the very depths of one\'s heart when one meditates on the name of God with equanimity and devotion. All external means of counting beads, practising penance, fasting and torturing the body, are of no avail in the, process of the realisation of God. It is easily possible by repeating His name with every breath and at all times and secretly in one\'s own heart.',
    reference: 'P.G.K.L. page no.173',
  },
  {
    id: '36',
    category: 'Namasadhan',
    text: 'Repetition of God\'s name is the only adequate means to realise Him. God never minds the want of intelligence in His devotee, nor his highly sinful nature. Howsoever low be the caste or race or profession of the devotee, he should only surrender himself completely to God, and repeat incessantly, in full faith, the name of God, and he is sure to attain to the highest realisation of God.',
    reference: 'P.G.K.L. page no. 192',
  },
  {
    id: '37',
    category: 'Namasadhan',
    text: 'The innate cataract of ignorance cannot be removed by any other means except by the Name imparted by the Guru.',
    reference: 'P.G.H.L.page no.341/378',
  },
  {
    id: '38',
    category: 'Namasadhan',
    text: 'Repeat the name of God at every step and with every breath, secretly and with a sense of pride, there being no need of resorting to any other means for the realisation of God.',
    reference: 'P.G.K.L.page no.178',
  },
  {
    id: '39',
    category: 'Namasadhan',
    text: 'We should meditate on God in all mental conditions whatsoever. We should utter the name of God under all circumstances. The seed takes root whether it faces upwards or downwards. We must not mind whether we utter the name of God with pleasure or displeasure, in happiness or in grief.',
    reference: 'P.G.H.L.page no. 358/395',
  },
  {
    id: '40',
    category: 'Namasadhan',
    text: 'The uttering of the name of God is indeed an easy way for reaching Him. One need not go to a distant forest. God will Himself come to the house of a Saint. One should sit at a place, concentrate his mind, invoke God with love, and utter His name time after time.',
    reference: 'P.G.M.L.page no.318-319/416.chapter XVI- 53',
  },
  {
    id: '41',
    category: 'Namasadhan',
    text: 'Meditation is possible, so long as physical pain is endurable. But when it goes beyond endurance, meditation becomes impossible. So we should carry on our meditation so long as health is good enough for that. At the same time, we must pray God that when pain gets beyond endurance, He should, by His grace, keep His memory alive in our mind. There is no other remedy to remember God in excessive physical pain.',
    reference: 'Glimpses page no.152/169',
  },
  {
    id: '42',
    category: 'Namasadhan',
    text: 'Determinately and resolutely should one meditate on God by means of His Name. Let the head break off, or let the body fall, we should not leave off the celebration of God\'s Name. Even if we are fasting for a week, we should not fail to sing the Name of God. If the head breaks, or the body is cut in twain, we should not fail in the celebration of God\'s Name. He alone, who determinately utters the Name of God, will be able to find God.',
    reference: 'P.G.M.L.Page no.319/417. chapter XVI-53',
  },
  {
    id: '43',
    category: 'Namasadhan',
    text: 'We should never forget God\'s Name, whether in happiness or in sorrow. Whenever difficulties overcome us, whenever we are down with the worries of life, we should meditate on the Name of God. By the Name of God are all our difficulties dispelled, and all our calamities swept away.... If we only utter it regularly and continuously, Death shall have no power over us. If a man does nothing but only utter the Name of God, God is satisfied and protects His Devotee.',
    reference: 'P.G.M.L. preface page no.16/xxiii',
  },
  {
    id: '44',
    category: 'Namasadhan',
    text: 'Through mystical experience, through devotion, through deceit, through the torments of Samsara, let the name of God always dance upon the tongue.',
    reference: 'P.G.M.L.page no. 194/254. chapter VIII-2',
  },
  {
    id: '45',
    category: 'Namasadhan',
    text: 'Really we should be our own judges of the quality of our meditation. It is in proportion to the bliss we enjoy in meditation. The degree of bliss, however, does not depend upon the expansion of our experience; it depends upon its quality.',
    reference: 'Glimpses page no.124/131',
  },
  {
    id: '46',
    category: 'Namasadhan',
    text: 'The feeling of devotion should naturally well up in the heart as a result of deep meditation and higher spiritual experiences. It should never be worked up.',
    reference: 'Glimpses page no.125/132',
  },
  {
    id: '47',
    category: 'Namasadhan',
    text: 'Our daily meditation should be coupled with the holy company of saints. Then alone will it bear proper fruit. It is in the company of saints that we would realise the real value of meditation. If we try to live in their company for a good many days and observe their behaviour minutely, we would understand how they have realised their identity with God.',
    reference: 'Glimpses page no. 116/120-121',
  },
  {
    id: '48',
    category: 'Namasadhan',
    text: 'There is no use in calling upon the name of God aloud. He who hears the sound of an ant\'s feet, will He not know the quality of your heart?',
    reference: 'P.G.H.L.page no.353/390',
  },
  {
    id: '49',
    category: 'Namasadhan',
    text: 'One should not wait for a suitable opportunity to turn up to meditate on God. One should begin immediately. One can never hope to be so un-perturbed as to give oneself unmolested to mere meditation on God. If a man says that he will meditate on God when matters are comparatively easy, that will never come to pass.',
    reference: 'P.G.M.L.page no.317/414. chapter XVI-51',
  },
  {
    id: '50',
    category: 'Namasadhan',
    text: 'Meditation on divine name is the only means of generating, developing and stabilising spiritual energy in us. This spiritual energy, Atman, Absolute, God or Divinity are one and the same. When this energy is generated, it affects the centres in our brain as a result of which we get the supersenous experiences of Nada (sound), Bindu (form) and Kala (light) etc.',
    reference: 'Glimpses page no.138/148-149',
  },
  {
    id: '51',
    category: 'Namasadhan',
    text: "There is no use in calling mechanically upon God, 'unknowingly;' there is no use in calling upon God without Bhava and Bhakti. The aspirant must have Bhava and Bhakti. It is only when you have definite devotion towards God, that God may listen to you. Otherwise, you may call upon him orally or 'strenuously with a bugle', and yet he may not appear before you at all. What is wanted is a devout heart for God, and not a mere oral or mechanical or verbal calling upon him.",
    reference: "P.G.K.L.page no.65",
  },
  {
    id: '52',
    category: 'Namasadhan',
    text: "The Methodology of Meditation by means of which God may be attained - The first of these is evidently the Name of God, by the help of which the Teacher directs his disciple to meditate on God. Secondly, we are told that this meditation must be of a fully concentrated type. And thirdly, this meditation must be immediate, must be practised here and now and must not suffer any loss of time. When all these criteria are fulfilled, the disciple may regard himself definitely as on the way to God.",
    reference: "Spiritual Awakening in Gandhi and other Indian Saints. page no.167",
  },
  {
    id: '53',
    category: 'Namasadhan',
    text: "In the process of uttering the name of God through our breath, there ought to be also devotion to God. It is not merely a mechanical utterance of the name of God, but a remembering of the Name of God through devotion..... Our breath should be tied to our devotion to God. The two must go together. Holy indeed is the body which is given to the utterance of God's Name.",
    reference: "P.G.H.L.page no.166/201 & P.G.M.L.page no. 400/521 chapter xix-43",
  },
  {
    id: '54',
    category: 'Namasadhan',
    text: "God should be the sole object of the aspirant's meditation, even in dreams and in sleep. His mind should know no other object of contemplation. The natural bent of the senses should be in the direction of God, and the eyes should ever seek His vision.",
    reference: "P.G.M.L.Page.no.317/414. chapter XVI-51",
  },
  {
    id: '55',
    category: 'Namasadhan',
    text: "To meditate on God conceiving his Form in our mind is Sakama (with expectation of reward) and to meditate on God without conceiving his Form is Nishkama. God comes with greater love, to the man who meditates on His Name without thinking about His Form.",
    reference: "P.G.H.L. page no.147/181-182",
  },
  {
    id: '56',
    category: 'Namasadhan',
    text: "Whatever be the difficulties in which one may be placed, one should offer prayers to God. One should call in the help of God, when calamities befall him. Then God will not wait, but ward off those calamities by his personal intervention. By meditation on God's name, obstacles will vanish away in different directions. One need only surrender his life to God.",
    reference: "P.G.M.L.page no.317/414. chapter XVI- 51",
  },
  {
    id: '57',
    category: 'Namasadhan',
    text: "Any Asana, in which we can continue our God-meditation for a long time and in a happy mood is the Asana that is useful for us.",
    reference: "B.G.P.G.R. page no. 249/221",
  },
  {
    id: '58',
    category: 'Namasadhan',
    text: "Spiritual energy, when generated, produces in us such emotions as love, compassion, modesty, dispassion, wonder, terror and bliss. The compassion and dispassion produced as a result of the growth of this energy, would alone be stable and enduring. Hence real dispassion, desirelessness and fearlessness would be possible only when spiritual experiences develop. Self-effort alone cannot achieve them. However, as these virtues are contributory to spiritual experience, we should try to cultivate them. But their perfection can be achieved only by intense Namasmarana.",
    reference: "Glimpses page no. 138/149",
  },
  {
    id: '59',
    category: 'Namasadhan',
    text: "Ideal Sage should lead an intensely active life for some time, and should immediately engage himself in intensive meditation. In that way, both his meditation and his activity become strengthened and the mind becomes tranquil and powerful.",
    reference: "P.G.M.L.page no. 418/545-546. chapter XIX-73",
  },
  {
    id: '60',
    category: 'Namasadhan',
    text: "We should meditate on God, for God holds the keys of success in His hands.",
    reference: "P.G.M.L.page no.400 21. chapter XIX-44",
  },
  {
    id: '61',
    category: 'Namasadhan',
    text: "If a man meditates on the Name of God, all his sins and miseries would come to an end. God's Name alone shatters to pieces mountains of sins.",
    reference: "P.G.M.L. page no. 379/492-493. chapter XIX-8 & E.B.V. page no.60",
  },
  {
    id: '62',
    category: 'Namasadhan',
    text: "God's name destroys the three kinds of miseries, and sins are burnt away like camphor by fire. One should repeat the name while eating and drinking, while sleeping and while awake. In fact at all times we should continuously concentrate our thoughts on the name of God.",
    reference: "P.G.K.L. page no. 183",
  },
  {
    id: '63',
    category: 'Namasadhan',
    text: "Progress in spiritual life is of two types: One is slow and cumulative and the other is quick and sudden. One is called पिपिलिका मार्ग (an ant's way) while the other is called विहंगम मार्ग (a bird's way). If we are once in possession of the aeroplane of Name that carries with it divine power, we may rise to any height. The divine grace received through our intense Sadhana of Namasmarana or meditation on Nama would definitely ensure rapid progress.",
    reference: "Glimpses page no.141/152",
  },
  {
    id: '64',
    category: 'Namasadhan',
    text: "There is only one favour that we should ask of God: that we should always think of Him in our heart; that we should always utter His name by our mouth; that we should always see Him with our eyes; that our hands should worship only Him; that our head be placed always at His feet; that our ears should only hear of God's exploits; that He should show Himself always to our right and to our left, before and after, and at the end of our life. We should ask God of no other favour except this.",
    reference: "P.G.M.L.page no.200/262. chapter VIII-5",
  },
  {
    id: '65',
    category: 'Namasadhan',
    text: "We cannot meditate unless the object of meditation is realised by us; but we cannot have realisation unless we meditate.",
    reference: "पुण्यस्मृती, पा. क्र. ६६",
  },
  {
    id: '66',
    category: 'Namasadhan',
    text: "Mortal things remain in this world and nobody can take them away for a future existence. Hence we should grow indifferent to all things, and give ourselves up to contemplation, by which the infinite profit of God will be attained.",
    reference: "P.G.M.L.page no. 387/504. chapter XIX-23",
  },
  {
    id: '67',
    category: 'Namasadhan',
    text: "One who repeats the name of God incessantly, has no fear of death. It is the purifier of the most sinful; it yields the fruit which is equal to the performance of crores of sacrifices and is the only means of securing the highest spiritual experience in life.",
    reference: "P.G.K.L. page no.191",
  },
  {
    id: '68',
    category: 'Namasadhan',
    text: "There is greater possibility of भाव being generated by devoting longer time to meditation; but once भाव is created, there is no need of longer time.",
    reference: "पुण्यस्मृती, पा. क्र. ६६",
  },
  {
    id: '69',
    category: 'Namasadhan',
    text: "If you meditate on the name of Govinda, then you will become Govinda yourself. There will be no difference between you and God. The mind will be filled with joy, and the eyes will shed down tears of love.",
    reference: "P.G.M.L.page no 280/363.chapter XV-12",
  },
  {
    id: '70',
    category: 'Namasadhan',
    text: "God may remain concealed; but He cannot conceal His name. When we have once uttered His name, He cannot escape from us.",
    reference: "P.G.M.L.page no.195/255 chapter VIII-2",
  },
  {
    id: '71',
    category: 'Namasadhan',
    text: "A true omen, is the vision of God. When one remembers God, all benefits will necessarily accrue. By meditating on the Name of God, all speech will become holy, and the quarters full of auspiciousness.",
    reference: "P.G.M.L.page no. 354/ 464.chapter XVI-88",
  },
  {
    id: '72',
    category: 'Namasadhan',
    text: "Good meditation is an outcome of the grace of God. According to the law of tropism, God Himself attracts the devotee and draws him nearer and nearer. It is the growing attractive power of the 'Vastu' that heightens the quality of meditation.",
    reference: "Glimpses page no.128/125",
  },
  {
    id: '73',
    category: 'Namasadhan',
    text: "Meditation on the Name of God is alone sufficient to bring to us untold benefits. Life and birth would thus come to an end.",
    reference: "P.G.M.L.page no. 344/451.chapter XVI-78",
  },
  {
    id: '74',
    category: 'Namasadhan',
    text: "It is only after God-realisation through intense meditation that genuine dedication of actions to God is possible. Still, in the beginning we should try to practise dedication by way of preliminary preparation.",
    reference: "Glimpses page no. 114/119",
  },
  {
    id: '75',
    category: 'Namasadhan',
    text: "One should not flutter about, but should remain steady, believing in the efficacy of God's Name. God will give you imperishable happiness, and the round of incarnations will cease. You will even be able to confer obligations upon others. That itself will be a great asset. The Name of God will save you in this life as well as in the next. If you leave off the pursuit of evanescent things, you will attain to incalculable bliss.",
    reference: "P.G.M.L.page no.321/419. chapter XVI-55",
  },
  {
    id: '76',
    category: 'Namasadhan',
    text: "A single utterance of the name of God creates panic among sins. As soon as God's name is uttered, the divine recorder ceases to record. God Himself comes forth to receive His devotee with materials of worship.",
    reference: "P.G.M.L.page no.200/262. chapter VIII-5",
  },
  {
    id: '77',
    category: 'Namasadhan',
    text: "As we sit down and sing the praise of God, God stands before us. As in devotion we stand up and call on the name of God, God dances before us. God Indeed loves his Kirtana so much that He forthwith comes to the suecour of His devotees in the midst of difficulties.",
    reference: "P.G.M.L. page no 200-262 chapter VIII-5",
  },
  {
    id: '78',
    category: 'Namasadhan',
    text: "We can not stop at the stage of the Yogic processes like posture or breath-control, or for that matter, even concentration. We must be one with the 'नाम'. For that, continuous meditation is quite essential. Meditation should be silent and must be done with intense 'भाव' (one-pointed devotion), and must be carried on for a long time. The aspirant then approaches the stage of 'Passive Alertness'. Devotion must be unswerving, it should not decrease and should not come to an end.",
    reference: "Gurudev R.D.Ranade A Glance At His Allahabad University Days And Other Essays page No.68",
  },
  {
    id: '79',
    category: 'Namasadhan',
    text: "While we are contemplating God, both body and mind are entirely transformed. 'When the Self has been transformed in God, and when the mind has been suffused in illumination, the whole of creation looks divine, and all of a sudden the influx of God fills the whole world.'",
    reference: "P.G.M.L.page no.346/453.chapter XVI-81",
  },
  {
    id: '80',
    category: 'Namasadhan',
    text: "We pass through the three-fold process of purification, clarification and sanctification from the moral, intellectual and spiritual points of view respectively. In the first place, our mind must become pure before we could have any experience of the sublime. Secondly, this purity must lead to the clarification of intellect, and finally this clarification must culminate in a state of sanctification. It is not without reason that people, who have come out of spiritual meditation, have described how a new world has been created for them.",
    reference: "B.G.P.G.R.page no.292/261",
  },
  {
    id: '81',
    category: 'Namasadhan',
    text: "He who utters the name of God while walking, gets the merit of a Sacrifice at every step. Blessed is his body. It is itself a place of pilgrimage. He who says God while doing his work, is always merged in Samadhi. He who utters the name of God while eating, gets the merit of a fast even though he may have taken his meals. He who utters the name of God without intermission receives liberation though living.",
    reference: "P.G.M.L. Page no. 320/418. chapter XVI-55",
  },
  {
    id: '82',
    category: 'Namasadhan',
    text: "Think of God in thought, word and deed and you will be one with God in this very birth.",
    reference: "E.B.V. page no.95",
  },
  {
    id: '83',
    category: 'Namasadhan',
    text: "Enclose the Name of God in your mouth. Think constantly of what is valuable and what is not valuable. By meditation on God, all difficulties will vanish. We shall thus be able to cross the uncrossable ocean of life. The whole lineage will become pure, by the utterance of God's Name.",
    reference: "P.G.M.L page no321/418. chapter XVI-55",
  },
  {
    id: '84',
    category: 'Namasadhan',
    text: "Remember God's Name with all speed, and then God cannot hold Himself back. He will hasten and come ahead of His swift-winged Eagle. He cannot contain His love, and will run to the devotee's help.",
    reference: "P.G.M.L. page no.346/453.chapter XVI-80",
  },
  {
    id: '85',
    category: 'Namasadhan',
    text: "Sadhana indeed is a necessity of the body, and so long as the body exists, it must be subjected to Sadhana. Sadhana is necessary at all stages, and that even though a man may have reached the end of spiritual life, it is still necessary for him to continue his Sadhana.",
    reference: "P.G.M.L.page no. 408/532-533. chapter XIX-56",
  },
  {
    id: '86',
    category: 'Namasadhan',
    text: "When we shut all the sense organs to outer perceptions, then probably by proper meditation on God, and by His Grace, internal senses open and we are able to perceive, hear and speak things which it would be ordinarily impossible for human beings to do.",
    reference: "P.G.H.L.page no. 200/230",
  },
  {
    id: '87',
    category: 'Namasadhan',
    text: "One does not know when the body may fall. One does not know what calamities may befall us. Hence, we should always be on the alert, should do all that we can for spiritual life, and fill the world with the holy name of God.",
    reference: "P.G.M.L. page no.419/547. chapter XIX-75",
  },
  {
    id: '88',
    category: 'Namasadhan',
    text: "The highest eight-fold emotions, Ashtasatvik bhavas are evoked in the heart of the Bhakta when he sings with one-pointed devotion the name of God.",
    reference: "P.G.K.L.page.no.197",
  },
  {
    id: '89',
    category: 'Namasadhan',
    text: "It is much better to die than to forget the name of God.",
    reference: "P.G.K.L.page no.86",
  },
  {
    id: '90',
    category: 'Namasadhan',
    text: "By Meditation on God, whatever we may desire from the bottom of our heart shall come to take place by the grace of God, and all obstacles will come to an end.",
    reference: "P.G.M.L.page no.376/489. chapter XIX-5",
  },
  {
    id: '91',
    category: 'Namasadhan',
    text: "Rest which we should have handed over to God for our spiritual contemplation, we are handing over to the body in order to make ourselves degenerate. Do not sleep like an ordinary man. If you sleep, sleep like an ecstatic.",
    reference: "P.G.K.L.page no.30-31",
  },
  {
    id: '92',
    category: 'Namasadhan',
    text: "Name of God is the oil in which the wick of the self is to be drenched, and then ignited by the fire of God. The Name is the material cause, and God the instrumental cause, for bringing to fruition the qualities of the Self.",
    reference: "P.G.H.L.page no.144/179",
  },
  {
    id: '93',
    category: 'Namasadhan',
    text: "One should not identify oneself with one's body which is to perish one day. One should meditate on the name of God, think of the Lord secretly, devoutly and silently within the innermost recesses of one's own heart, and without any consideration of time, unmindful of day or night, for the realization of God.",
    reference: "P.G.K.L.page no.178",
  },
  {
    id: '94',
    category: 'Namasadhan',
    text: "If you want to translate your grief into joy, you must necessarily take recourse to the contemplation of God.",
    reference: "P.G.H.L. page no. 42/76",
  },
  {
    id: '95',
    category: 'Namasadhan',
    text: "The aspirant would be able to see the glittering light of God inside the tabernacle of his heart. This is an indication of God's presence and grace, and a sure harbinger of future progress. It is the Name, therefore, which thus brings together the Self and God.",
    reference: "P.G.H.L. page no. 145/179",
  },
  {
    id: '96',
    category: 'Namasadhan',
    text: "We are full of joy when we are in the contemplation and realisation of God. That state of beatification is itself our liberation. Liberation is not to be found after death. But to know God, to do His work, to enjoy His presence and to devote oneself to His service are exactly what a Jivan-mukta ought to do.",
    reference: "B.G.P.G.R. page no. 190/169",
  },
  {
    id: '97',
    category: 'Namasadhan',
    text: "'There is no end other than Nama' is the opinion held by some while others opine, 'There is no means other than Nama.' Both opinions are equally valid. Nama is both the end as well as the means. Nama shows the Rupa (Form) of God. Hence it is a means to the seeker. But to those who are out, exclusively to meditate on Nama, without caring for the vision of God, it is an End in itself.",
    reference: "Glimpses page no.148/164-165",
  },
  {
    id: '98',
    category: 'Namasadhan',
    text: "By the power of the Name of God, one shall come to know what one does not know. One shall see what cannot be seen. One will be able to speak what cannot be spoken. One shall meet what cannot be ordinarily met. Incalculable will be the gain of uttering the Name.",
    reference: "P.G.M.L.page no. 320/418. chapter XVI-55",
  },
  {
    id: '99',
    category: 'Namasadhan',
    text: "It is only by uttering the name of God with devotion that our thirst is quenched, and our mind is composed. Ordinary men cannot understand its essential nature, its function, and its secret inherent power. The very Name of God makes passion void of passion in a devotee.",
    reference: "P.G.K.L. page no.193 & E.B.V. page no.46",
  },
  {
    id: '100',
    category: 'Namasadhan',
    text: "The last element necessary for the success of our spiritual meditation (नामस्मरण) is the Grace of God. It is not simply by performing our devotional acts that we may be able to achieve our highest goal. God must be moved and it is only when He is moved that He will move the world by His Grace.",
    reference: "B.G.P.G.R. page no. 255/226",
  }
];