// export const parmarthMandirIndex = [
//   { id: 'section_1', title: '१. अर्पणपत्रिका' },
//   { id: 'section_2', title: '२. द्वितीय आवृत्तीसंबंधी निवेदन' },
//   { id: 'section_3', title: '३. निवेदन (प्रथमावृत्ती)' },
//   { id: 'section_4', title: '४. प्रस्तावना (प्रथमावृत्ती )' },
//   { id: 'section_5', title: '५. संप्रदायाचे चार महापुरुष - छायाचित्रे, संक्षिप्त बोधवचनांसह' },
//   { id: 'section_6', title: '६. श्री भाऊसाहेब उमदीकर महाराज यांचे बोधवचनामृत' },
//   { id: 'section_7', title: '७. श्री सद्गुरुनाथ निंबर्गी महाराजांची १३ पदे' },
//   {
//     id: 'section_8',
//     title: '८. अनुभव-पदे',
//     subsections: [
//         { id: 'section_8_a', title: 'अ' },
//         { id: 'section_8_aa', title: 'आ' },
//         { id: 'section_8_i', title: 'इ' },
//         { id: 'section_8_ii', title: 'ई' },
//         { id: 'section_8_u', title: 'उ' },
//         { id: 'section_8_uu', title: 'ऊ' },
//         { id: 'section_8_e', title: 'ए' },
//         { id: 'section_8_ai', title: 'ऐ' },
//         { id: 'section_8_o', title: 'ओ' },
//         { id: 'section_8_au', title: 'औ' },
//         { id: 'section_8_am', title: 'अं' },
//         { id: 'section_8_aha', title: 'अः' },
//         { id: 'section_8_ru', title: 'ऋ' },
//         { id: 'section_8_ka', title: 'क' },
//         { id: 'section_8_kha', title: 'ख' },
//         { id: 'section_8_ga', title: 'ग' },
//         { id: 'section_8_gha', title: 'घ' },
//         { id: 'section_8_na', title: 'ङ' },
//         { id: 'section_8_cha', title: 'च' },
//         { id: 'section_8_chha', title: 'छ' },
//         { id: 'section_8_ja', title: 'ज' },
//         { id: 'section_8_jha', title: 'झ' },
//         { id: 'section_8_nya', title: 'ञ' },
//         { id: 'section_8_ta', title: 'ट' },
//         { id: 'section_8_tha', title: 'ठ' },
//         { id: 'section_8_da', title: 'ड' },
//         { id: 'section_8_dha', title: 'ढ' },
//         { id: 'section_8_nna', title: 'ण' },
//         { id: 'section_8_tta', title: 'त' },
//         { id: 'section_8_ttha', title: 'थ' },
//         { id: 'section_8_dda', title: 'द' },
//         { id: 'section_8_ddha', title: 'ध' },
//         { id: 'section_8_n', title: 'न' },
//         { id: 'section_8_pa', title: 'प' },
//         { id: 'section_8_pha', title: 'फ' },
//         { id: 'section_8_ba', title: 'ब' },
//         { id: 'section_8_bha', title: 'भ' },
//         { id: 'section_8_ma', title: 'म' },
//         { id: 'section_8_ya', title: 'य' },
//         { id: 'section_8_ra', title: 'र' },
//         { id: 'section_8_la', title: 'ल' },
//         { id: 'section_8_va', title: 'व' },
//         { id: 'section_8_sha', title: 'श' },
//         { id: 'section_8_ssha', title: 'ष' },
//         { id: 'section_8_sa', title: 'स' },
//         { id: 'section_8_ha', title: 'ह' },
//         { id: 'section_8_lla', title: 'ळ' },
//         { id: 'section_8_ksha', title: 'क्ष' },
//         { id: 'section_8_dnya', title: 'ज्ञ' },
//     ],
//   },
//   { id: 'section_9', title: '९. भुपाळ्या' },
//   { id: 'section_10', title: '१०. आरत्या' },
//   { id: 'section_11', title: '११. प्रार्थना' },
//   { id: 'section_12', title: '१२. स्तवने' },
//   { id: 'section_13', title: '१३. भारुडे' },
// ];

// assets/text/parmarthMandirContent.ts

export default {
  section_1: `Placeholder text for Section 1 (अर्पणपत्रिका).`,
  section_2: `Placeholder text for Section 2 (द्वितीय आवृत्तीसंबंधी निवेदन).`,
  section_3: `Placeholder text for Section 3 (निवेदन प्रथमावृत्ती).`,
  section_4: `Placeholder text for Section 4 (प्रस्तावना प्रथमावृत्ती).`,
  section_5: `Placeholder text for Section 5 (संप्रदायाचे चार महापुरुष).`,
  section_6: `Placeholder text for Section 6 (श्री भाऊसाहेब उमदीकर महाराज यांचे बोधवचनामृत).`,
  section_7: `Placeholder text for Section 7 (श्री सद्गुरुनाथ निंबर्गी महाराजांची १३ पदे).`,
  
  // Section 8 Subsections ( अनुभव-पदे )
  section_8_a: `Placeholder text for Section 8, subsection अ.`,
  section_8_aa: `Placeholder text for Section 8, subsection आ.`,
  section_8_i: `Placeholder text for Section 8, subsection इ.`,
  section_8_ii: `Placeholder text for Section 8, subsection ई.`,
  section_8_u: `Placeholder text for Section 8, subsection उ.`,
  section_8_uu: `Placeholder text for Section 8, subsection ऊ.`,
  section_8_e: `Placeholder text for Section 8, subsection ए.`,
  section_8_ai: `Placeholder text for Section 8, subsection ऐ.`,
  section_8_o: `Placeholder text for Section 8, subsection ओ.`,
  section_8_au: `Placeholder text for Section 8, subsection औ.`,
  section_8_am: `Placeholder text for Section 8, subsection अं.`,
  section_8_aha: `Placeholder text for Section 8, subsection अः.`,
  section_8_ru: `Placeholder text for Section 8, subsection ऋ.`,
  section_8_ka: `Placeholder text for Section 8, subsection क.`,
  section_8_kha: `Placeholder text for Section 8, subsection ख.`,
  section_8_ga: `Placeholder text for Section 8, subsection ग.`,
  section_8_gha: `Placeholder text for Section 8, subsection घ.`,
  section_8_na: `Placeholder text for Section 8, subsection ङ.`,
  section_8_cha: `Placeholder text for Section 8, subsection च.`,
  section_8_chha: `Placeholder text for Section 8, subsection छ.`,
  section_8_ja: `Placeholder text for Section 8, subsection ज.`,
  section_8_jha: `Placeholder text for Section 8, subsection झ.`,
  section_8_nya: `Placeholder text for Section 8, subsection ञ.`,
  section_8_ta: `Placeholder text for Section 8, subsection ट.`,
  section_8_tha: `Placeholder text for Section 8, subsection ठ.`,
  section_8_da: `Placeholder text for Section 8, subsection ड.`,
  section_8_dha: `Placeholder text for Section 8, subsection ढ.`,
  section_8_nna: `Placeholder text for Section 8, subsection ण.`,
  section_8_tta: `Placeholder text for Section 8, subsection त.`,
  section_8_ttha: `Placeholder text for Section 8, subsection थ.`,
  section_8_dda: `Placeholder text for Section 8, subsection द.`,
  section_8_ddha: `Placeholder text for Section 8, subsection ध.`,
  section_8_n: `Placeholder text for Section 8, subsection न.`,
  section_8_pa: `Placeholder text for Section 8, subsection प.`,
  section_8_pha: `Placeholder text for Section 8, subsection फ.`,
  section_8_ba: `Placeholder text for Section 8, subsection ब.`,
  section_8_bha: `Placeholder text for Section 8, subsection भ.`,
  section_8_ma: `Placeholder text for Section 8, subsection म.`,
  section_8_ya: `Placeholder text for Section 8, subsection य.`,
  section_8_ra: `Placeholder text for Section 8, subsection र.`,
  section_8_la: `Placeholder text for Section 8, subsection ल.`,
  section_8_va: `Placeholder text for Section 8, subsection व.`,
  section_8_sha: `Placeholder text for Section 8, subsection श.`,
  section_8_ssha: `Placeholder text for Section 8, subsection ष.`,
  section_8_sa: `Placeholder text for Section 8, subsection स.`,
  section_8_ha: `Placeholder text for Section 8, subsection ह.`,
  section_8_lla: `Placeholder text for Section 8, subsection ळ.`,
  section_8_ksha: `Placeholder text for Section 8, subsection क्ष.`,
  section_8_dnya: `Placeholder text for Section 8, subsection ज्ञ.`, 
  section_8_shra: `Placeholder text for Section 8, subsection श्र.`, 

  section_9: `Placeholder text for Section 9 (भुपाळ्या).`,
  section_10: `Placeholder text for Section 10 (आरत्या).`,
  section_11: `Placeholder text for Section 11 (प्रार्थना).`,
  section_12: `Placeholder text for Section 12 (स्तवने).`,
  section_13: `Placeholder text for Section 13 (भारुडे).`,
};

// { id: 'section_8_dnya', title: 'श्र' },