export const sadhguru = [
  {
    id: '1',
    text: 'The spiritual teacher is verily the King of all the Saints. Him we may call an ocean of happiness, or a mine of love, or a mountain of courage, or the source of dispassion. The spiritual teacher is an invariable protector of his disciple. Like a wish tree, he yields all desires to a devotee. He punishes the wicked, and destroys all sin.',
    reference: 'M.M.chapter V-3.Page no.168/222',
    category: 'Sadhguru',
  },
  {
    id: '2',
    text: 'Whatever emotions or feelings, conceptions or aspirations, we might entertain about God, might as well be entertained about a spiritual teacher, who is His replica upon earth.',
    reference: 'P.G.H.L.page no.143/178.',
    category: 'Sadhguru',
  },
  {
    id: '3',
    text: 'Only him should we call our Guru, who is able to show God directly to our sight; him we should hand over all our wealth and mind and body, and take from him the Atman for whom we aspire',
    reference: 'M.M.chapter V-2.Page no.167/221',
    category: 'Sadhguru',
  },
  {
    id: '4',
    text: 'There is a final identity between the spiritual teacher and God. He is none else but verily Brahman incarnate.',
    reference: 'P.G.K.L.page no.63.',
    category: 'Sadhguru',
  },
  {
    id: '5',
    text: 'Wherever the eye is cast, Sadguru is able to see only God and nothing else: In between all the things and himself is God who prevents the vision of the other things. The Sadguru is able to see outside exactly what he sees inside. There is in such a realiser a perfect parity between internal and external perception.',
    reference: 'P.G.H.L.. page no. 141/175',
    category: 'Sadhguru',
  },
  {
    id: '6',
    text: 'The spiritual teacher always enjoys the state of Sahaja Samadhi. This expression means that he has merely to look out to see God.',
    reference: 'P.G.H.L. page no.140/174',
    category: 'Sadhguru',
  },
  {
    id: '7',
    text: 'He who instils into our mind the light of the Self and dispels the darkness of ignorance, he who brings into unison the Individual and the Universal Selves - he alone is entitled to be called a Guru.',
    reference: 'M.M.chapter XIX-34.Page no.393/512',
    category: 'Sadhguru',
  },
  {
    id: '8',
    text: "God's power has filled the whole world; a real spiritual teacher is he who enjoys bliss by playing with that power, which is a very difficult thing; and a real spiritual disciple is he who is satisfied with contemplating on that enjoyment.",
    reference: 'P.G.K.L.page no.166.',
    category: 'Sadhguru',
  },
  {
    id: '9',
    text: 'The function of the real spiritual teacher is not the breathing of the Mantra into the ears of his disciple, but the showing of the form of God to his vision.',
    reference: 'P.G.H.L. page no.338/375',
    category: 'Sadhguru',
  },
  {
    id: '10',
    text: 'The great characteristic of a spiritual teacher is that he enables his disciple to abide in God. To him there should be no distinction between हंसः and सोऽहं and no return to the mundane world.',
    reference: 'P.G.H.L. page no.143/178',
    category: 'Sadhguru',
  },
  {
    id: '11',
    text: 'We wave a rosary of beads, and mutter numbers of prayers; but He who makes us wave the rosary, and inspires us with the saying of prayers, Him we do not know even though He is inside our hearts. He alone is the Spiritual Teacher, who can show the Atman directly to our vision.',
    reference: 'M.M.chapter VIII-11.Page no.205/269',
    category: 'Sadhguru',
  },
  {
    id: '12',
    text: 'The real Guru is he, at whose instance his disciples have walked on the path of God, taking note of the landmarks and the sign boards on the way until they have reached their ठिकाना ठौर, their final destination from which there is no return.',
    reference: 'P.G.H.L. page no.338/375',
    category: 'Sadhguru',
  },
  {
    id: '13',
    text: 'Unless the spiritual teacher be really of a superior calibre, spiritual knowledge would be hard of attainment, and again, that unless the initiation comes from a Spiritual Teacher who has realised his identity with the Self, there can be no knowledge of the subtle path which transcends all power of logic and argumentation.',
    reference: 'C.S.U.P. page no.242/330.',
    category: 'Sadhguru',
  },
  {
    id: '14',
    text: 'The spiritual teacher is beyond all inference, and beyond all modes of proof; he is indescribable in words, which become silent in his oneness which tolerates no duality',
    reference: 'M.M.chapter IV-19.Page no.162/215',
    category: 'Sadhguru',
  },
  {
    id: '15',
    text: "The spiritual teacher is beyond the triad of saluter, salutation, and salutee; He is the greatest mystery possible. One cannot love him without being lost to his bodily self, and there remains no difference between master and pupil. The words 'master and disciple,' therefore, mean but one thing, and the master alone lives in both",
    reference: 'M.M.chapter IV-19.Page no.162 216',
    category: 'Sadhguru',
  },
  {
    id: '16',
    text: 'He alone deserves to be a Spiritual Teacher, who regards his disciples as gods. He, who does not accept service from his disciples and regards them as gods, is alone worthy of being a Teacher.',
    reference: 'M.M.chapter XVI-52.Page no.317/414',
    category: 'Sadhguru',
  },
  {
    id: '17',
    text: 'He alone who relieves people of the sufferings of existence, and takes them out of the meshes of illusion, is entitled to be called a Guru.',
    reference: 'M.M.chapter XIN-34.Page no.393/512',
    category: 'Sadhguru',
  },
  {
    id: '18',
    text: 'Guru is the veritable magician, who pours the celestial Mantra into the ears of the disciple and makes him forget his body-consciousness, whereby the disciple becomes the eternal but unattached spectator of all existence.',
    reference: 'P.G.K.L.page no.62.',
    category: 'Sadhguru',
  },
  {
    id: '19',
    text: 'The primary characteristic of a Guru is that he possesses immaculate Self-knowledge, and the satisfaction of a determinate life in the Self.',
    reference: 'M.Mchapter XIX-34.Page no.393/513',
    category: 'Sadhguru',
  },
  {
    id: '20',
    text: 'The spiritual Guide or Guru - is not one of the means of Self-Realisation but self-incarnate.',
    reference: 'E.B.V. page no.105.',
    category: 'Sadhguru',
  },
  {
    id: '21',
    text: "Sadguru must be a master of methodology, and must teach his disciples the proper method of achieving the ideal... The methodology might be regarded as successful, only when the disciple has seen the 'light of God' and the spiritual teacher has shown him the absolute Reality.",
    reference: 'P.G.K.L.page no.63-64.',
    category: 'Sadhguru',
  },
  {
    id: '22',
    text: 'According to the law of Spiritual Gravitation, the experience of a worthy Spiritual Teacher must automatically descend to his disciples. As water at a higher level must descend to a lower level, so the experience of a spiritual teacher must descend automatically to those who are walking on the path which he has trodden.',
    reference: 'P.G.H.L. page no.142/176',
    category: 'Sadhguru',
  },
  {
    id: '23',
    text: 'Knowledge, dispassionateness, devotion, rightful conduct, Sadhana, spiritual discussion, meditation, morality, justice, and the observation of the mean constitute the chief characteristics of a Guru.',
    reference: 'M.M.chapter XIX-34.Page no.394.513',
    category: 'Sadhguru',
  },
  {
    id: '24',
    text: 'Arise, Awake, and learn from those who are better than you; for the path of realisation is as hard to tread as the edge of a razor. Very wisely have sages called it an inaccessible path. The knowledge of Self could not be attained by an individual striving for himself on his own behalf; the knowledge is so subtle and mystic that nobody could by his own individual effort ever hope to attain it. It is necessary that the Teacher to whom we go to seek wisdom must have realised his identity with the ultimate Self.',
    reference: 'C.S.U.P. page no. 242 330',
    category: 'Sadhguru',
  },
  {
    id: '25',
    text: "The only adequate way of expressing one's appreciation of the greatness of the Guru is to submit in silence to the feet of the Guru, for the greatness of the Guru can never be adequately praised.",
    reference: 'M.M.chapter III-6.page no.50/63',
    category: 'Sadhguru',
  },
  {
    id: '26',
    text: 'Wherever the spiritual teacher is, there is bound to be auspiciousness and prosperity.',
    reference: 'P.G.K.L.page no.75.',
    category: 'Sadhguru',
  },
  {
    id: '27',
    text: 'As when a tree is watered at the bottom, it goes out to the branches and the foliage; as when a man has taken a bath in the sea, he may be said to have bathed in all the holy waters of the world; as when nectar has once been enjoyed, all the flavours are forthwith enjoyed; similarly, when the Guru has been worshipped, all the desires become fulfilled.',
    reference: 'M.M.chapter III-6-page no.48-49/62-63.',
    category: 'Sadhguru',
  },
  {
    id: '28',
    text: 'The real secret of the Grace of the Guru is that a man should thereby see the whole world as God. Whatever one sees with his eyes, or hears with his ears, or tastes with his tongue, should all be of the nature of God.',
    reference: 'M.M.chapter XI-3 page no.220/287',
    category: 'Sadhguru',
  },
  {
    id: '29',
    text: 'Joy is the first characteristic of a Sadguru. Lassitude, weariness, neglect and dissatisfaction do not find a place in his being. He keeps fire of Yoga aflame in the midst of enjoyment. He maintains full actionlessness in the midst of action. He enters the region of the fearless.',
    reference: 'P.G.H.L. page no. 138/172',
    category: 'Sadhguru',
  },
  {
    id: '30',
    text: 'As when the sun shines on the horizon, the moon fades away in the background, similarly when the Guru shines, all the sciences fade away.',
    reference: 'M.M.chapter III-6.Page no.50/63',
    category: 'Sadhguru',
  },
  {
    id: '31',
    text: 'All the sciences that we may have studied, or all the Yoga that we may have practised, become successful only when the Guru sends down his Grace.',
    reference: 'M.M.chapter III-74.page no.113 148.',
    category: 'Sadhguru',
  },
  {
    id: '32',
    text: "Who can direct the ship of a man's life, except a spiritual guide, who knows the danger spots and situations, and possesses the power to carry the ship successfully to the other shore of existence?",
    reference: 'P.G.H.L.. page no.137 171.',
    category: 'Sadhguru',
  },
  {
    id: '33',
    text: 'The comparative value of the knowledge to be obtained from books, and the knowledge to be obtained from a teacher by word of mouth :- The first is entirely lifeless the second is the outcome of the full-fledged life of the master. This makes all the difference in the world; Books can never be expected to solve the actual difficulties in the path of Self-realisation, while a Teacher who has walked on the path may take his aspiring disciple from step to step on the ladder of spiritual perfection.',
    reference: 'C.S.U.P. page no.243/331',
    category: 'Sadhguru',
  },
  {
    id: '34',
    text: 'The efficacy of the Guru consists in the revelation to the disciple of the true way to God.',
    reference: 'M.M.chapter XIX-31.Page no.392/510',
    category: 'Sadhguru',
  },
  {
    id: '35',
    text: 'The Spiritual Teacher confers a new birth on the disciple as a result of which the disciple sees the form of God and is filled with illimitable joy.',
    reference: 'P.G.K.L.page no.77.',
    category: 'Sadhguru',
  },
  {
    id: '36',
    text: "A spiritual teacher takes away all the defects and deficiencies of his disciple's mind, enlarges his receptivity and makes of him a worthy disciple capable of performing the functions he wills.",
    reference: 'P.G.H.L. page no.336-337/373-374.',
    category: 'Sadhguru',
  },
  {
    id: '37',
    text: 'In the midst of the calamities and misfortunes which might fall to the lot of his disciple, the spiritual teacher gives him internal and continuous support, and enables him to face boldly his trials and tribulations.',
    reference: 'P.G.H.L.page no.337/374',
    category: 'Sadhguru',
  },
  {
    id: '38',
    text: 'Fixing of the gaze on the tip or top of the nose, observation of the incoming and outgoing breath, mental repetition of the Name along with the breaths distinctly - all these are, no doubt, important factors in the process of meditation. They are all, really, very useful for concentration. But with all that, if the Name has not been imparted by a worthy spiritual teacher, it would never enable a seeker to attain spiritual realisation. The efficacy of the Name rests in the intense Sadhana and spiritual realisation of the Sadguru.',
    reference: 'Glimpses page no.149/166.',
    category: 'Sadhguru',
  },
  {
    id: '39',
    text: 'It is extremely difficult to meet a man who has reached the highest spiritual end... It is only he who has realised his identity with God, is capable of imparting the secret of spiritual life. Such persons are rare.',
    reference: 'B.G.P.G.R. page no.237/211',
    category: 'Sadhguru',
  },
  {
    id: '40',
    text: 'The Guru gives the key of The Spiritual treasure. The Grace of the Master is indeed the key which illumines the intellect, breaks open the door of dualism, takes us to infinite happiness, and lands us forever in the supersensuous state.',
    reference: 'M.M.chapter XIX-31.Page no.392/510',
    category: 'Sadhguru',
  },
  {
    id: '41',
    text: 'The Guru separates Vyavahara from Paramartha, matter from spirit, just as the swan separates water from milk. This is the principal function which a spiritual teacher performs for the upliftment of his disciple.',
    reference: 'P.G.H.L.page no.335/372.',
    category: 'Sadhguru',
  },
  {
    id: '42',
    text: 'Without a Guru we can never attain to real knowledge... One may practise any Sadhana one pleases; but it would be all useless without a Guru. The light of knowledge shines only by the Word which the Guru imparts.',
    reference: 'M.M.chapter XIX-30.Page no.391-392/510.',
    category: 'Sadhguru',
  },
  {
    id: '43',
    text: 'Scorning by the Guru is nothing but stimulation for knowledge in a disciple.',
    reference: 'E.B.V. page no.102.',
    category: 'Sadhguru',
  },
  {
    id: '44',
    text: "Without a Guru one's life would be useless. Without a Guru, one has only to sink in suffering. Without a Guru, the storms of the heart shall never be appeased. By the protecting hand of the Guru, God would reveal Himself.",
    reference: 'M.M.chapter XIX-30.Page no.392/510',
    category: 'Sadhguru',
  },
  {
    id: '45',
    text: "A spiritual teacher not only drinks the juice of God's name but also makes others drink it. The ambrosial experience which a teacher gains is thus automatically transferred to the disciples. If the teacher is able to fasten his mind on the अलक्ष्य, the disciples also are able to see the unseen form of God. He lifts up the curtain of darkness, and makes them visualise the Paramatman. If he is an expert in amalgamating himself with spiritual sound, his disciples also automatically find themselves experiencing the Shabda and coming into unison with it.",
    reference: 'P.G.H.L. Page по.142/176',
    category: 'Sadhguru',
  },
  {
    id: '46',
    text: "One can acquire the virtue of 'mauna' only by being in the company of the spiritual master and of the saints. They are verily the embodiments of tranquility.",
    reference: 'P.G.K.L.page no.49.',
    category: 'Sadhguru',
  },
  {
    id: '47',
    text: 'Your spiritual master will easily remove the various difficulties and doubts in your spiritual life, and bring you illumination and joy:',
    reference: 'P.G.K.L.page no.58.',
    category: 'Sadhguru',
  },
  {
    id: '48',
    text: 'Spiritual teacher after driving away such vicious enemies as illusion and infatuation and egoism, establishes unison between the individual soul and the universal soul, and thereby confers beatification on the individual.',
    reference: 'P.G.K.L.page no.77.',
    category: 'Sadhguru',
  },
  {
    id: '49',
    text: 'The power of the spiritual teacher enables the disciple to visualise the form of God wherever his eyes are cast. Such vision itself constitutes the essence of liberation.',
    reference: 'P.G.K.L.page no.78.',
    category: 'Sadhguru',
  },
  {
    id: '50',
    text: 'The Guru is a great ocean of mercy (dayasindhu) and makes us participate in beatification. On account of his mercifulness he takes us on to the plane of bliss or beatification.',
    reference: 'P.G.K.L.page no.80.',
    category: 'Sadhguru',
  },
  {
    id: '51',
    text: "The spiritual teacher is as it were a spring to the garden of an aspirant's endeavours for self-realisation, and though formless, as it were, the form of mercy incarnate. He makes no distinction of great and small in distributing the wealth of final emancipation.",
    reference: 'M. M.chapter IV-19.page no. 161 215',
    category: 'Sadhguru',
  },
  {
    id: '52',
    text: 'The Spiritual teacher enables us to transcend our philosophic doubts. It is only the power of realisation which will carry you beyond these philosophic doubts.',
    reference: 'P.G.K.L.page no.102.',
    category: 'Sadhguru',
  },
  {
    id: '53',
    text: 'The Spiritual teacher communicates to the disciple - "Now do not turn back from your spiritual path. I have given everything that you wanted. I have given you everything that I have. I have given you the foundational Mantra. Now it is your business to perfect it."',
    reference: 'P.G.K.L.page no.104-105.',
    category: 'Sadhguru',
  },
  {
    id: '54',
    text: "A man can do no wrong either on account of his own reflection on the Guru's spiritual instruction, or on account of the meritorious life which his spiritual teacher has led.",
    reference: 'P.G.K.L.page no.88.',
    category: 'Sadhguru',
  },
  {
    id: '55',
    text: 'It is necessary that the Teacher to whom we go to seek wisdom must have realised his identity with the ultimate Self. For, unless the Teacher has realised such an identity, unless, in other words, he stands on the lofty pedestal of unitive experience, the knowledge which he can impart can never be expected to be fructified in any individual who receives it.',
    reference: 'C.S.U.P.page no.242-243/330.',
    category: 'Sadhguru',
  },
  {
    id: '56',
    text: 'A real spiritual teacher does not shut the doorways of sense, nor does he feel any necessity for controlling his breath. His spiritual joy enables him to control his motor and sensory organs automatically, without his playing any active part in the process... All the while, he is in the consciousness of the spiritual realisation to which he has attained. He remains always self-poised in the midst of all his activities.',
    reference: 'P.G.H.L. page no. 139. 173',
    category: 'Sadhguru',
  },
  {
    id: '57',
    text: 'A real saint is he who enjoys beatification as well as fearlessness. Joy and fearlessness are thus the two chief moral characteristics of a Sadguru.',
    reference: 'S.A.G.I.S.. page no.143',
    category: 'Sadhguru',
  },
];