export const saint = [
  {
    id: '1',
    text: 'A Saint is a man of supreme insight, for his vision is set upon God. He is immaculate, because he holds in vision the spotless Brahman. In fact the Saint has attained to the highest of all qualities, namely, the abiding life in God. That indeed is the primary characteristic of the Saint.',
    reference: 'M.M.chapter XIX-35.page no.395/514.',
    category: 'Saint',
  },
  {
    id: '2',
    text: 'A Saint is he who has left no desires in him, and has no anger in him; his desires are centred in the Self, and his treasure is the Name. When one is shut up on all sides by one\'s own Self, one is always merged in bliss, and no arrogance is possible in such a man.',
    reference: 'M.M.chapter XIX-35.page no.394/514.',
    category: 'Saint',
  },
  {
    id: '3',
    text: 'The Saints by their perfect morality and devotion raise themselves to the position of the Godhead. Gods are Saints, and Saints Gods. Images are merely the occasional cause of worship... The impersonal God cannot satisfy our wants. But the Devotee satisfies all. God and Saint are merely the obverse and the reverse sides of the same spiritual coin.',
    reference: 'M.M.chapter XVI-75.page no.341/445.',
    category: 'Saint',
  },
  {
    id: '4',
    text: 'Saint when born shines in his own native lustre even like a superb form of spiritual experience to which nothing else can be compared and which stands supreme above all other forms.',
    reference: 'P.G.H.L.page no. 303/339.',
    category: 'Saint',
  },
  {
    id: '5',
    text: 'The God-realiser rises superior to the considerations of the body, and is indifferent to its growth or decay because he has attained to liberation while living and though living.',
    reference: 'P.G.K.L page no.280.',
    category: 'Saint',
  },
  {
    id: '6',
    text: 'The ideal sage is always like the full moon, and spreads his light on good and bad things equally. His equanimity is unbroken. His compassion for all the beings of the earth is unsurpassed. His mind never undergoes any change. He is never filled by delight on account of something good, nor does he fall a prey to dejection when anything bad occurs. The ideal sage, therefore, is without joy, and without sorrow, and always full of the knowledge of the Self.',
    reference: 'M.M.chapter III-89.page no.123/162.',
    category: 'Saint',
  },
  {
    id: '7',
    text: 'A Realised sage cares equally for all, and obtains the vision of world-unity. He is himself the supreme place of pilgrimage. His very sight is meritorious. In his company, even an infatuated man may enter into the being of God.',
    reference: 'M.M.chapter III-89.page no. 123/162.',
    category: 'Saint',
  },
  {
    id: '8',
    text: 'A Realised sage seems to have taken on a body, he is equal, in fact, to the great God, because he has subdued all his senses.',
    reference: 'M.M.chapter 111-89.page no.123/162.',
    category: 'Saint',
  },
  {
    id: '9',
    text: 'The first characteristic of a Saint is that he is always looking at the Self, and he is outside the world even though he happens to be in it.',
    reference: 'M.M.chapter XIX-35.page no.394/513.',
    category: 'Saint',
  },
  {
    id: '10',
    text: 'A saint is ever free from fear of any kind as he is thoroughly convinced, through actual experience, that his \'Vastu\' would never fail to protect him. A saint who has realised the bliss of Brahman, will never be afraid of anything or anybody.',
    reference: 'Glimpses 139-140',
    category: 'Saint',
  },
  {
    id: '11',
    text: 'The ideal sage raises his hand only to show protection; he stretches his hand only to succour the fallen; he moves his hand only to touch the afflicted; In a similar way, such a man is harmless even when he sees; he does not look at other things for fear that they may take away his vision of God who is immanent in all things.',
    reference: 'M.M.chapter III-34.page no.74/95.',
    category: 'Saint',
  },
  {
    id: '12',
    text: 'Epoche, Humility, Equanimity Self-surrender, and Altruism are the moral characteristics, which single out the God-realiser from others.',
    reference: 'P.G.H.L.page no.394/432.',
    category: 'Saint',
  },
  {
    id: '13',
    text: 'The first virtue of the God-realiser is epoche. The perfected Saint remains silent and merged in God; he remains absolutely mute and dumb, enjoying all the while the vision and the presence of God.',
    reference: 'P.G.H.L.page no.394/433',
    category: 'Saint',
  },
  {
    id: '14',
    text: 'The second characteristic of a God-realiser is his great humility. It is this great humility and unconsciousness of one\'s own powers, that constitute another mark of God realisation.',
    reference: 'P.G.H.L.page no.395/433-434.',
    category: 'Saint',
  },
  {
    id: '15',
    text: 'The third characteristic of the God-realiser is his great equanimity. He stands in the market-place, without any partiality. He has neither friends nor foes.',
    reference: 'P.G.H.L..page no.396/434-435.',
    category: 'Saint',
  },
  {
    id: '16',
    text: 'The fourth mark of a God-realiser is his absolute self-surrender and the last characteristic of a God-realiser is his great altruism.',
    reference: 'P.G.H.L.page no.396/435-436.',
    category: 'Saint',
  },
  {
    id: '17',
    text: 'Saint might be regarded as the Personal, and God as the Impersonal aspect of Reality.',
    reference: 'P.G.H.L.page no.8/15 general introduction.',
    category: 'Saint',
  },
  {
    id: '18',
    text: 'The sage lives in solitude, always gives himself to meditation, and spends his time usefully in the service of God along with other men.....He cultivates in himself the best of qualities, and teaches them to the people. He always has some work to do, and leads people to the service of God.',
    reference: 'M.M.chapter XIX-66.page no.414.540.',
    category: 'Saint',
  },
  {
    id: '19',
    text: 'A Saint never cares for what is going to happen; for living as he does in the Self, he knows that all will be well for him.',
    reference: 'M.M.chapter XIX-35.page no.395/514.',
    category: 'Saint',
  },
  {
    id: '20',
    text: 'As the Sun\'s light cannot be hidden in the sky, similarly, the greatness of a Saint cannot be hidden in the world.',
    reference: 'M.M.chapter XI-6.page no.224.293.',
    category: 'Saint',
  },
  {
    id: '21',
    text: 'The characteristic of the Self-realiser is that his Sadhana is a Sadhana without any scope for doubt. His mind becomes motionless, and is one with God.... Whether his body rests motionless in a place or moves away, his Self is always motionless.',
    reference: 'M.M.chapter XIN-35.page no.394/513-514.',
    category: 'Saint',
  },
  {
    id: '22',
    text: 'He, the God realizer is firmly fixed in the form of God internally, but behaves like an ordinary man externally. He does not command his senses, nor is he afraid of the objects of sense; and whatever is to be done, he does at the proper time. He does not feel any necessity for training up his sense-organs while doing actions, nor is he affected by their influence. Desire has no power over him. He never becomes infatuated, and is as clean as a lotus-leaf when it is sprinkled with water.',
    reference: 'M.M.chapter III-89.page no.122-123/161.',
    category: 'Saint',
  },
  {
    id: '23',
    text: 'He alone, we may say, has reached ecstasy, who looks upon honour and dishonour alike. He alone is the beloved of God, who looks upon friend and enemy alike. He alone is the king of Yogins who looks upon gold and a portion of mud with equal eye. Such a one is a great purifying power, and makes all the three worlds pure by his presence. The very gods worship the water of his feet. A mere remembrance of him puts an end to all sin,',
    reference: 'M.M.chapter VIII 4. page no. 198/259',
    category: 'Saint',
  },
  {
    id: '24',
    text: 'As opposed to the transmigrating process, lies the state of Absolution reached only by the select few who have gone beyond the realm of the Sattva, Rajas and Tamas qualities, and who, by their devotion, have reached identity with God during this life...when they have gone to the End, they never return therefrom.',
    reference: 'M.M.chapter III-13.page no.57 73.',
    category: 'Saint',
  },
  {
    id: '25',
    text: 'Saints indeed take on a body when the path of religion vanishes, and when irreligion reigns. By the power of God\'s name, the Saints come to the succour of the ignorant and the fallen. By the force of their devotion, they destroy heresy and all pseudo-religion.',
    reference: 'M.M.chapter XI-6.page no.225/293-294',
    category: 'Saint',
  },
  {
    id: '26',
    text: 'The Saints have in them the power of giving what nobody else can give. The esoteric knowledge of the Godhead which is impossible to be attained by men, becomes possible only by contact with Saints.',
    reference: 'M.M.chapter XIX-36.page no.395/514-515.',
    category: 'Saint',
  },
  {
    id: '27',
    text: 'A Saint is a spiritual washerman. He applies the soap of illumination, washes on the slab of tranquillity, purifies in the river of knowledge, and takes away the spots of sin.',
    reference: 'M.M.chapter VIII-4.page no.198/259',
    category: 'Saint',
  },
  {
    id: '28',
    text: 'The ideal sage regards the very atoms as consisting of life and therefore he walks softly as if by compassion. The road on which he walks is itself a road of compassion the direction, in which he walks, is a direction of love; he spreads his life, as it were, below the feet of other beings, in order that he may be a source of happiness to all beings... If one would want to see what non-injury is, one must go to the ideal sage, for he is non-injury incarnate,',
    reference: 'M.M.chapter III-34.page no.73/94-96',
    category: 'Saint',
  },
  {
    id: '29',
    text: 'As trees do not know honour and dishonour, as they are equal to those who worship them and those who cut them, similarly, the saints in their supreme courage look upon honour and dishonour alike.',
    reference: 'M.M.chapter VIII-4.page no.198.259.',
    category: 'Saint',
  },
  {
    id: '30',
    text: 'Without the favour of Saints, the secret of spiritual life does not reach our hands. The names of God are various; but unless the saints confer favour upon us, we shall not know how to meditate on the name of God.',
    reference: 'M.M.chapter VIII-4.page no.198-199/260.',
    category: 'Saint',
  },
  {
    id: '31',
    text: 'That is the supreme Law of Saint-hood, which regards as necessary a perfect belief in the efficacy of God\'s name, and which requires us to eradicate all our other desires.',
    reference: 'M.M.chapter VIII-4.page no. 198/259.',
    category: 'Saint',
  },
  {
    id: '32',
    text: 'The distribution of spiritual wealth becomes the chief task of the God-realiser...It thus becomes the duty of the Saint not to keep his spiritual accumulation only for himself, but to utilise it for the upliftment of humanity.',
    reference: 'P.G.H.L.page no.397/435-436.',
    category: 'Saint',
  },
  {
    id: '33',
    text: 'Not all mystics need be philosophers; not all mystics need lead a life of emotion; not all mystics need be activists; but wherever true Mysticism is, one of these faculties must predominate; and unless we see in a mystic a full-fledged exercise of at least one of these faculties, we may not say that he is entitled to the name of a Mystic at all. Hence intellectual power and absolute clarity of thought seem to be the first criterion of mystical experience.',
    reference: 'P.G.H.L.page no.3/9.',
    category: 'Saint',
  },
  {
    id: '34',
    text: 'Saints show that God could be realised in any walk of life; but they also show that God is very jealous God, who would not allow any love to be given to any other object beside himself.',
    reference: 'M.M.chapter IX general review. Page no.210/275',
    category: 'Saint',
  },
  {
    id: '35',
    text: 'A Bhakta uplifts not merely himself, but others also. He ceases to grieve; he ceases to hate; he feels no enjoyment in other things; he feels no enthusiasm for other things; he becomes intoxicated with love; he remains silent; Spiritual "Epoche" is the mark of the saint.',
    reference: 'M.M.chapter 1-9.page no.14/20.',
    category: 'Saint',
  },
  {
    id: '36',
    text: 'Saint looks upon prosperity, woman, and gold as vomit, and contemplates God alone. His love of God increases from moment to moment. He does not allow a single minute to be wasted without the contemplation of God. At all times, his heart is full of the fire of devotion.',
    reference: 'M.M.chapter XIX-48.page no.402/524.',
    category: 'Saint',
  },
  {
    id: '37',
    text: 'The Ideal Saint pleases all, and fills the minds of all with discrimination and good thoughts. There is no limit to the disciples he makes. All of these he leads on the spiritual pathway.. Whatever he knows, he teaches the people, and makes them wise. Whenever they get into difficulty, he is ready to help them. He makes the minds of all pure and holy.',
    reference: 'M.M.chapter XIX-71.page no.416-417 544.',
    category: 'Saint',
  },
  {
    id: '38',
    text: 'The Saints indeed teach us the way to God, who is beyond the region of illusion....... They are the abode of bliss. They are the root of satisfaction. They are the source of rest. They are the end of devotion...... They are the home of ecstasy.',
    reference: 'M.M.chapter XIX-36.page no.395/515.',
    category: 'Saint',
  },
  {
    id: '39',
    text: 'The Saints indeed are truly the rich; for they possess in their hands the keys of the spiritual treasure. The spiritually poor have been made by them spiritual Kings of men.',
    reference: 'M.M.chapter XIX-36.page no.395/515.',
    category: 'Saint',
  },
  {
    id: '40',
    text: 'Emperors and kings have lived erewhile, but none of them has been able to make a grant of God. The Saints confer a boon which nobody else can confer. There is no limit to the greatness of the Saints, for it is on account of them that God reveals Himself.',
    reference: 'M.M.chapter XIX-36.page no.395/515.',
    category: 'Saint',
  },
  {
    id: '41',
    text: 'The Saints are an ocean of happiness, God is their treasure. They speak no other language but of God. One should find rest only in the Saints."',
    reference: 'M.M.chapter XVI-51.page no. 317/413-414',
    category: 'Saint',
  },
  {
    id: '42',
    text: 'If we cling to the feet of the saints, we shall be relieved of all suffering. If we serve at their door, we shall be relieved of all infatuation. If we partake of their "prasada", our life-span shall increase. The saints are an ocean of mercy, and they bestow upon us knowledge, devotion, and love.',
    reference: 'M.M.chapter VIII-4.page no.198/260.',
    category: 'Saint',
  },
  {
    id: '43',
    text: 'A Saint has no reason for logic-chopping, nor does he show hatred, jealousy, or hypocrisy towards others...... When he has seen the Self, he has no reason for grief, or infatuation, or fear. ... His egoism comes to an end, and his heart is set upon the eternal.',
    reference: 'M.M.chapter XIX-35.page no.395/514.',
    category: 'Saint',
  },
  {
    id: '44',
    text: 'To the extent to which a philosopher might be regarded as being above one, who is materially satisfied, to that extent a mystic might be regarded as being above a philosopher.',
    reference: 'P.G.K.L. page no.81',
    category: 'Saint',
  },
  {
    id: '45',
    text: 'The Saint calls himself a beggar who lives merely on alms, and therefore is not in need of help from anybody. He describes himself as a lunatic who lives in the enjoyment of his spiritual intoxication. Finally, he calls himself the king of his mind, in fact, the king of all he surveys.',
    reference: 'P.G.H.L.page no.254/292.',
    category: 'Saint',
  },
  {
    id: '46',
    text: 'The Mystic may be a Philosopher, but is not necessarily so. His mystic experience is sufficient for his own elevation into Divinity; but if he philosophises, he may raise thinking humanity into a Divine Kingdom of Ends.',
    reference: 'MM page no.494.',
    category: 'Saint',
  },
  {
    id: '47',
    text: 'Those who have seen God, lose all sense of false shame. For them exist no duties of caste and colour. They are forever filled with the joy of unitive life. We should ask of only one favour from God; namely, that we should be the pollen on the feet of such saints.',
    reference: 'M.M.chapter VIII-4.page no.198/260.',
    category: 'Saint',
  },
  {
    id: '48',
    text: 'When a Saint takes the immortal wine of God-love, he becomes free from infatuation and doubt. He reaches a state of perfect equanimity. The pauper and the prince are to him alike. The Saint lives in such a perfect state of equanimity. He has a hidden vision. Valuing his own soul, he cares for nobody, and sits in divine contemplation.',
    reference: 'P.G.H.L.page no.236-237/274.',
    category: 'Saint',
  },
  {
    id: '49',
    text: 'The Saint does not perform miracles: God performs them for him.... It is the devotional character of the people themselves that enables them to perceive the miracles.',
    reference: 'M.M.chapter XIX-38.page no.396/516-517.',
    category: 'Saint',
  },
  {
    id: '50',
    text: 'God becomes so happy in the house of the Saints, that He does not depart from their house, even though He is thrown out of the house. God enjoys the company of the Saints, and keeps returning to them even though He is driven away.',
    reference: 'M.M.chapter XI-7.page no.226/295.',
    category: 'Saint',
  },
  {
    id: '51',
    text: 'The mystic while enjoying ecstatic bliss, might appear to others as sleeping, whereas he is really fully awake. How can such a man sleep when God\'s presence always keeps him awake?',
    reference: 'P.G.K.L. page no.305.',
    category: 'Saint',
  },
  {
    id: '52',
    text: 'One has only to remember that it becomes the mission of a God Realiser to spread the gospel of God whenever and wherever it becomes possible for him to do so. One God, One World, One Humanity should be his maxim, theo-polity his doctrine.',
    reference: 'B.G.P.G.R.page no.136/121-122.',
    category: 'Saint',
  },
  {
    id: '53',
    text: 'So far as the utility of the mystic to the society is concerned, we may almost take it to be a truism, that a mystic who is not of supreme service to the society is not a mystic at all.',
    reference: 'P.G.H.L.page no.4/10.',
    category: 'Saint',
  },
  {
    id: '54',
    text: 'A good man should act as he speaks....It is much better not to talk at all, than to talk and not to do....If we talk, our actions should follow our words....The saints act as they speak, and it is for this reason that they attain to divinity.',
    reference: 'P.G.H.L. page no.52/86',
    category: 'Saint',
  },
  {
    id: '55',
    text: 'God realizer lives in the midst of contacts, and looks like an ordinary man. But he is not affected by them, as the Sun\'s disc is not affected by the water in which it is reflected. If we look at him in an external way, he looks like an ordinary man; but if we try to determine his real nature, we cannot really know him.',
    reference: 'M.M.chapter III-89.page no.123/161.',
    category: 'Saint',
  },
  {
    id: '56',
    text: 'By the words of a Realised sage, religion lives. His look is the cause of the highest prosperity. The happiness of the heavenly world is merely a play to him; and if one were to remember him even accidentally, one may acquire so much merit as to be equal to him.',
    reference: 'M.M.chapter III-89.page no.123/162',
    category: 'Saint',
  },
  {
    id: '57',
    text: 'The Yoga of Namasmarana is the only path that can enable the Sadhaka to attain God-head. This path alone can take a Sadhaka into the inner sanctuary and grant him the vision and bliss of divinity. there is no other path for going there. All the saints of the world, have followed the same Pathway and have bequeathed its knowledge to posterity.',
    reference: 'Glimpses page no.147/164.',
    category: 'Saint',
  },
  {
    id: '58',
    text: 'Saints perform a Kirtana in such a manner that the form of God is thereby firmly set before the minds of men.',
    reference: 'M.M.chapter XI-5.Page no.223/291',
    category: 'Saint',
  },
  {
    id: '59',
    text: 'God-realisers constitute a blessed community, and on account of their intense love for afflicted mankind, they live only for its benefaction and betterment, proclaiming from pole to pole, like a rumbling cloud, the eternal Gospel of God from everlasting to everlasting.',
    reference: 'P.G.K.L page no.318',
    category: 'Saint',
  },
  {
    id: '60',
    text: 'He alone may be said to have reached the end of Sadhana who has attained to the realisation of the Self. The Saints, are as untouched by happenings, as the Sun\'s disc is untouched by the sky.',
    reference: 'M.M.chapter XIX-35.page no.394/513 & M.M.chapter V-3.page no.168/223',
    category: 'Saint',
  },
  {
    id: '61',
    text: 'When one meets a Saint, one feels as if one is endowed with four hands. After meeting the Saints, all the toil of life ceases. What the Saints are able to confer is more valuable than a wish-tree, or a touch stone, or a wish-jewel',
    reference: 'M.M.chapter V-3.page no.168/223',
    category: 'Saint',
  },
  {
    id: '62',
    text: 'The discrimination of the sage merges in the determination of the nature of Atman,... his mind cannot give rise to passions...his mind does not know the surges of passions... As the full moon is full on all sides, similarly, having realized the Self, he exhibits no deficiency of desire in any quarter".',
    reference: 'M.M.chapter III-90.page no.124/163',
    category: 'Saint',
  },
  {
    id: '63',
    text: 'Whosoever realises the unity or the presence of God can never but direct his life in such a way that the greatness of God becomes not merely understood but also achievable.',
    reference: 'B.G.P.G.R.page no.136/121-122.',
    category: 'Saint',
  },
  {
    id: '64',
    text: 'It is only in Saints\' company that you will get something which will be worth your while. It is from them that you might learn to turn your own body and mind to their proper spiritual use.',
    reference: 'P.G.H.L.page no.29/62-63',
    category: 'Saint',
  },
  {
    id: '65',
    text: 'When the Saints who have attained to spiritual experience meet each other, they verily enjoy solitude, and their talk determines the nature of Brahman.',
    reference: 'M.M.chapter XIX-19.page no.386/502.',
    category: 'Saint',
  },
  {
    id: '66',
    text: 'When the Self is seen, a Saint ceases to care for worldly life and engages himself in teaching others the knowledge of the Self.',
    reference: 'M.M.chapter XIX-35.page no.394/513.',
    category: 'Saint',
  },
  {
    id: '67',
    text: 'Saints possess a reservoir of spiritual energy which oozes through them. The company of such saints intensifies our fervour. Even an exchange of thought with them will be of great help. Their mere presence is quite enough. Even a graceful glance of their Kurm-drishti would be valuable.',
    reference: 'Glimpses 151',
    category: 'Saint',
  },
  {
    id: '68',
    text: 'The Saints are really more generous than even a cloud. They fulfill all desires. They turn away the minds of men from empty and insignificant things, and make them worthy of themselves. They rescue them from the clutches of Death. There is no saviour except Saints when a calamity befalls a man; for the gods become weary of the evil-doers, but the Saints accept them also.',
    reference: 'M.M.chapter XI-6.page no.224/292-293',
    category: 'Saint',
  },
  {
    id: '69',
    text: 'The ideal sage is harmless even in speech; his love moves first, and then move the words from his mouth; compassion comes first, and then the words.',
    reference: 'M.M.chapter III-34.page no.74/95.',
    category: 'Saint',
  },
  {
    id: '70',
    text: 'Saints Grace, - The highest power in the world that enslaves God, & destroys birth & death.',
    reference: 'E.B.V. page no. 13',
    category: 'Saint',
  },
  {
    id: '71',
    text: 'Blessed is that Assembly, where the devotees are filling the heaven with the sounds of God\'s name. Blessed is that Assembly where satisfaction of various kinds accrues, where all doubts are set at rest, where God\'s form stands motionless before the mind.',
    reference: 'M.M.chapter XIX-37page no.396/515',
    category: 'Saint',
  },
  {
    id: '72',
    text: 'We can take hold of a ray of light and walk thereon to heaven; but we cannot know the full significance of the company of the saints. We can go to the nether world and cross the highest ocean; but we cannot know the value of the company of the saints.',
    reference: 'M.M.chapter VIII-4.page no. 199/260.',
    category: 'Saint',
  },
  {
    id: '73',
    text: 'In the case of fore-fulfilment, the events are so manipulated by God that the desires are fulfilled before they arise in a man\'s mind and victory is gained for the Saint.',
    reference: 'P.G.H.L.page no.325/362.',
    category: 'Saint',
  },
  {
    id: '74',
    text: 'The sage is a royal swan, who separates the water of the not-Self from the milk of the Self, and feeds upon the latter. He collects together by his spiritual vision the form of the Godhead, which, in the absence of the knowledge of the Self, is dispersed in different directions.',
    reference: 'M.M.chapter III-90.page no.124/163',
    category: 'Saint',
  },
  {
    id: '75',
    text: 'Having realised God in every nook and corner of the universe, and in fact in all forms of existence--cosmic, psychic, epistemological and mystical--the saint plunges himself into a wonderful rapture.',
    reference: 'P.G.K.L. page no.284.',
    category: 'Saint',
  },
];